import type { MapDef } from "./types";

/// 🏙️ MAP 1 — GWAVE CITY (မြို့တော်)
///
/// ခံစားချက် — နေ့ခင်းက တောက်ပ၊ ညက ပြတင်းပေါက်တွေ လင်းလာတယ်။
/// ★ အဆောက်အအုံတွေကို **လက်နဲ့ နေရာချထားတယ်** (random မဟုတ်) — ကျပန်း
///   ဆောက်ရင် လမ်းတွေ ပိတ်ကုန်ပြီး ပိတ်မိတဲ့ ထောင့်တွေ ဖြစ်တတ်တယ်။

const RED = 0xe94f37;
const BLUE = 0x3f88c5;
const YELLOW = 0xf6ae2d;
const TEAL = 0x44bba4;
const PURPLE = 0xa06cd5;
const GREY = 0x6c757d;

export const CITY: MapDef = {
  id: "city",
  name: "ဂွေ့ဗ် မြို့တော်",
  emoji: "🏙️",
  blurb: "မီးရောင်စုံ မြို့လယ်၊ တိုက်ရိုက်လွှင့်မှု မျက်နှာပြင်ကြီးနဲ့",
  spawn: { x: 0, y: 0, z: 12, ry: Math.PI },
  worldRadius: 90,
  palette: {
    ground: 0x3a3f4a,
    grid: 0x4a5560,
    skyDay: 0x87ceeb,
    skyDusk: 0xff8c42,
    skyNight: 0x0a0e24,
    fogDay: 0xb8d4e8,
    fogNight: 0x0d1220,
    fogNear: 40,
    fogFar: 130,
  },
  terrain: { kind: "flat" },

  buildings: [
    // ── ထဲဝင်လို့ရတဲ့ ၆ ခု ────────────────────────────────────────────────
    {
      x: -26,
      z: -22,
      w: 12,
      h: 18,
      d: 12,
      color: RED,
      emissive: 0xffd28a,
      label: "☕ Rooftop Cafe",
      interior: {
        w: 10,
        h: 4,
        d: 8,
        floorColor: 0x6b4f3a,
        wallColor: 0xf3e5d0,
        door: { side: "S", width: 2.4 },
        props: [
          { kind: "counter", x: -3, y: 0, z: -2.6, color: 0x8b5a2b },
          { kind: "table", x: -2, y: 0, z: 1 },
          { kind: "table", x: 2, y: 0, z: 1 },
          { kind: "table", x: -2, y: 0, z: 2.6 },
          { kind: "table", x: 2, y: 0, z: 2.6 },
          { kind: "chair", x: -3, y: 0, z: 1 },
          { kind: "chair", x: -1, y: 0, z: 1, ry: Math.PI },
          { kind: "chair", x: 1, y: 0, z: 1 },
          { kind: "chair", x: 3, y: 0, z: 1, ry: Math.PI },
          { kind: "plant", x: 4, y: 0, z: -3 },
        ],
        lights: [{ x: 0, y: 3.2, z: 0, color: 0xffd9a0, intensity: 1.4 }],
      },
    },
    {
      x: -10,
      z: -30,
      w: 14,
      h: 10,
      d: 14,
      color: BLUE,
      emissive: 0xbfe6ff,
      label: "🛒 Marketplace",
      interior: {
        w: 12,
        h: 5,
        d: 12,
        floorColor: 0x4a4f58,
        wallColor: 0xdfe7ef,
        door: { side: "S", width: 3 },
        props: [
          { kind: "shelf", x: -4, y: 0, z: -3 },
          { kind: "shelf", x: -4, y: 0, z: 0 },
          { kind: "shelf", x: -4, y: 0, z: 3 },
          { kind: "shelf", x: 4, y: 0, z: -3 },
          { kind: "shelf", x: 4, y: 0, z: 0 },
          { kind: "shelf", x: 4, y: 0, z: 3 },
          { kind: "counter", x: 0, y: 0, z: -4.4 },
          { kind: "screen", x: 0, y: 2.2, z: -5.6, color: 0x1b2a3a },
        ],
        lights: [
          { x: -3, y: 4, z: 0, color: 0xffffff, intensity: 1.1 },
          { x: 3, y: 4, z: 0, color: 0xffffff, intensity: 1.1 },
        ],
      },
    },
    {
      x: 10,
      z: -28,
      w: 14,
      h: 9,
      d: 12,
      color: YELLOW,
      emissive: 0xfff0c0,
      label: "🎓 Classroom",
      interior: {
        w: 12,
        h: 4,
        d: 10,
        floorColor: 0x8a7a5c,
        wallColor: 0xf7f2e4,
        door: { side: "S", width: 2.4 },
        props: [
          { kind: "screen", x: 0, y: 2, z: -4.6, color: 0x14301f },
          { kind: "table", x: -3, y: 0, z: -1 },
          { kind: "table", x: 0, y: 0, z: -1 },
          { kind: "table", x: 3, y: 0, z: -1 },
          { kind: "table", x: -3, y: 0, z: 1.6 },
          { kind: "table", x: 0, y: 0, z: 1.6 },
          { kind: "table", x: 3, y: 0, z: 1.6 },
          { kind: "chair", x: -3, y: 0, z: 0 },
          { kind: "chair", x: 0, y: 0, z: 0 },
          { kind: "chair", x: 3, y: 0, z: 0 },
        ],
        lights: [{ x: 0, y: 3.4, z: 0, color: 0xffffff, intensity: 1.3 }],
      },
    },
    {
      x: 26,
      z: -20,
      w: 12,
      h: 9,
      d: 12,
      color: TEAL,
      emissive: 0xff7ad9,
      label: "🎮 Arcade",
      interior: {
        w: 10,
        h: 4,
        d: 10,
        floorColor: 0x241a33,
        wallColor: 0x2e2244,
        door: { side: "S", width: 2.4 },
        props: [
          { kind: "rug", x: 0, y: 0, z: 0, color: 0x5b2a86, scale: 1.6 },
          { kind: "screen", x: -3.5, y: 1.2, z: -4.2, color: 0xff3b7f },
          { kind: "screen", x: 0, y: 1.2, z: -4.2, color: 0x3bd1ff },
          { kind: "screen", x: 3.5, y: 1.2, z: -4.2, color: 0xffe23b },
          { kind: "screen", x: -3.5, y: 1.2, z: 4.2, color: 0x8f3bff },
          { kind: "screen", x: 0, y: 1.2, z: 4.2, color: 0x3bff9e },
          { kind: "screen", x: 3.5, y: 1.2, z: 4.2, color: 0xff8f3b },
        ],
        lights: [{ x: 0, y: 3.2, z: 0, color: 0xc07bff, intensity: 1.6 }],
      },
    },
    {
      x: 34,
      z: -2,
      w: 10,
      h: 8,
      d: 10,
      color: PURPLE,
      emissive: 0xffd28a,
      label: "🏠 Apartment",
      interior: {
        w: 8,
        h: 3.5,
        d: 8,
        floorColor: 0x7a5a3f,
        wallColor: 0xeee2d0,
        door: { side: "W", width: 2.2 },
        props: [
          { kind: "bed", x: -2, y: 0, z: -2 },
          { kind: "table", x: 2, y: 0, z: 1 },
          { kind: "chair", x: 2, y: 0, z: 2.2 },
          { kind: "shelf", x: 3.2, y: 0, z: -2.6 },
          { kind: "lamp", x: -3, y: 0, z: 2.6 },
        ],
        lights: [{ x: 0, y: 2.8, z: 0, color: 0xffd9a0, intensity: 1.1 }],
      },
    },
    {
      x: 0,
      z: 30,
      w: 18,
      h: 22,
      d: 16,
      color: BLUE,
      roof: "flat",
      emissive: 0xbfe6ff,
      label: "🏛️ Gwave Tower",
      interior: {
        w: 16,
        h: 6,
        d: 14,
        floorColor: 0x2b3038,
        wallColor: 0xdde6f0,
        door: { side: "N", width: 3.4 },
        props: [
          { kind: "counter", x: 0, y: 0, z: -5, color: 0x1f2a36 },
          { kind: "screen", x: 0, y: 3, z: -6.6, color: 0x10202e, scale: 1.8 },
          { kind: "plant", x: -6, y: 0, z: -4 },
          { kind: "plant", x: 6, y: 0, z: -4 },
          { kind: "plant", x: -6, y: 0, z: 4 },
          { kind: "plant", x: 6, y: 0, z: 4 },
          { kind: "rug", x: 0, y: 0, z: 2, color: 0x39506b, scale: 2.2 },
        ],
        lights: [
          { x: -4, y: 5, z: 0, color: 0xffffff, intensity: 1.2 },
          { x: 4, y: 5, z: 0, color: 0xffffff, intensity: 1.2 },
        ],
      },
    },

    // ── ဝင်လို့မရတဲ့ အဆောက်အအုံများ (မြို့ရဲ့ အခင်းအကျင်း) ─────────────
    { x: 28, z: 18, w: 13, h: 16, d: 12, color: BLUE, emissive: 0xbfe6ff },
    { x: -8, z: 46, w: 11, h: 13, d: 12, color: TEAL, emissive: 0xffd28a },
    { x: -26, z: 22, w: 12, h: 19, d: 11, color: YELLOW, emissive: 0xffd28a },
    { x: -36, z: 2, w: 10, h: 15, d: 14, color: PURPLE, emissive: 0xbfe6ff },
    { x: -44, z: -30, w: 9, h: 9, d: 9, color: GREY, roof: "gable", roofColor: 0x4a5058 },
    { x: 44, z: -34, w: 9, h: 11, d: 9, color: GREY, roof: "gable", roofColor: 0x4a5058 },
    { x: 46, z: 34, w: 9, h: 8, d: 9, color: GREY, roof: "pyramid", roofColor: 0x4a5058 },
    { x: -46, z: 36, w: 9, h: 10, d: 9, color: GREY, roof: "pyramid", roofColor: 0x4a5058 },
    { x: 52, z: 4, w: 10, h: 14, d: 10, color: RED, emissive: 0xffd28a },
    { x: -54, z: -8, w: 10, h: 12, d: 10, color: TEAL, emissive: 0xffd28a },
    { x: 18, z: 48, w: 12, h: 9, d: 10, color: YELLOW, roof: "gable", roofColor: 0xb8842a },
    { x: -30, z: -48, w: 11, h: 12, d: 11, color: PURPLE, emissive: 0xbfe6ff },
    { x: 34, z: -46, w: 10, h: 10, d: 10, color: BLUE, roof: "dome", roofColor: 0x2b5f88 },
    { x: 58, z: -20, w: 9, h: 16, d: 9, color: GREY, emissive: 0xffd28a },
    { x: -60, z: 20, w: 9, h: 13, d: 9, color: GREY, emissive: 0xffd28a },
    { x: 8, z: -50, w: 12, h: 11, d: 11, color: RED, roof: "gable", roofColor: 0xa03528 },
  ],

  water: [
    { kind: "pool", x: 0, z: 0, radius: 6, level: 0.12, color: 0x2f7fbf, opacity: 0.72 },
    {
      kind: "river",
      points: [
        [-90, -60],
        [-50, -46],
        [-20, -52],
        [14, -62],
        [52, -70],
      ],
      level: 0.05,
      color: 0x2a6ea8,
      opacity: 0.68,
      flow: 0.4,
    },
  ],

  fires: [
    { x: -9, z: 6, scale: 1 },
    { x: 9, z: 6, scale: 1 },
    { x: -16, z: -2, scale: 0.55 },
    { x: 16, z: -2, scale: 0.55 },
    { x: -16, z: 14, scale: 0.55 },
    { x: 16, z: 14, scale: 0.55 },
  ],

  trees: [
    { x: -20, z: 10, kind: "broadleaf", scale: 1 },
    { x: 20, z: 10, kind: "broadleaf", scale: 1 },
    { x: -22, z: 40, kind: "broadleaf", scale: 1.2 },
    { x: 22, z: 40, kind: "broadleaf", scale: 1.2 },
    { x: -40, z: -14, kind: "pine", scale: 1.1 },
    { x: 40, z: -14, kind: "pine", scale: 1.1 },
    { x: -52, z: 46, kind: "broadleaf", scale: 0.9 },
    { x: 52, z: 46, kind: "broadleaf", scale: 0.9 },
  ],

  lamps: [
    { x: -14, z: -8, color: 0xffc879 },
    { x: 14, z: -8, color: 0xffc879 },
    { x: -14, z: 10, color: 0xffc879 },
    { x: 14, z: 10, color: 0xffc879 },
    { x: 0, z: -18, color: 0xffc879 },
    { x: 0, z: 20, color: 0xffc879 },
    { x: -30, z: 0, color: 0xffc879 },
    { x: 30, z: 0, color: 0xffc879 },
    { x: -40, z: 30, color: 0x9ad7ff },
    { x: 40, z: 30, color: 0x9ad7ff },
  ],

  vehicles: [
    { kind: "car", x: -20, z: 18, ry: 0 },
    { kind: "car", x: 20, z: 18, ry: Math.PI },
    { kind: "car", x: -34, z: -8, ry: Math.PI / 2 },
    { kind: "car", x: 34, z: 24, ry: -Math.PI / 2 },
    { kind: "drone", x: -6, z: -6, ry: 0 },
    { kind: "drone", x: 6, z: -6, ry: 0 },
    // 🕹 Game Zone ရှေ့က drone တွေ — 🚁 Drone ပြိုင်ပွဲအတွက် တန်းစီးလို့ရအောင်
    { kind: "drone", x: -16, z: 22, ry: Math.PI },
    { kind: "drone", x: 16, z: 22, ry: Math.PI },
    { kind: "drone", x: 0, z: 24, ry: Math.PI },
  ],

  weather: { default: "clear", allowed: ["clear", "rain", "storm", "fog"] },
  ambientSound: "city",
  gwaveLink: { kind: "live", x: 0, z: -14 },
};
