// Extra SQL lessons that take the SQL course from 10 to 30 lessons. Every
// lesson is runnable (kind "sql") against the same in-browser SQLite database
// seeded in sql-playground.tsx — `growers(id, name, city, plants)` and
// `strains(id, name, type, weeks, grower_id)`. Original tutorial content
// written for GreenWave. Pure data, safe to import from server and client.

import type { Lesson } from "@/lib/learn/lessons";

// Small helper so each lesson stays terse and consistent. Every extra lesson is
// a runnable SQL lesson with an explanation section, a "try it" section and a
// starter query.
function sq(
  slug: string,
  title: string,
  summary: string,
  minutes: number,
  explainHeading: string,
  explainBody: string,
  explainCode: string,
  tryBody: string,
  sqlCode: string,
): Lesson {
  return {
    slug,
    title,
    summary,
    minutes,
    kind: "sql",
    sections: [
      { heading: explainHeading, body: explainBody, code: explainCode },
      { heading: "Try it", body: tryBody },
    ],
    sqlCode,
  };
}

export const SQL_EXTRA: Lesson[] = [
  sq(
    "sql-column-alias",
    "Column Aliases (AS)",
    "Rename columns in the result so they read clearly.",
    8,
    "Giving columns a nicer name",
    "AS renames a column in the result only — the table is untouched. Aliases make headings readable ('Grower' instead of 'name') and are essential once you calculate new columns. The word AS is optional in SQLite, but writing it makes the intent obvious.",
    "SELECT name AS grower, city AS town\nFROM growers;",
    "Run the query to see the renamed headings. Then add `plants AS plant_count` to the list and run again.",
    "SELECT name AS grower, city AS town\nFROM growers;",
  ),
  sq(
    "sql-calculations",
    "Calculations in SELECT",
    "Do arithmetic on columns right inside the query.",
    9,
    "Maths in a query",
    "A SELECT can contain expressions, not just column names. Use `+ - * /` on numbers and give the result an alias. Here we estimate pots needed at two plants per pot. The original `plants` column never changes — you only shape the output.",
    "SELECT name, plants, plants * 2 AS leaves_est\nFROM growers;",
    "The query doubles each grower's plant count. Change `* 2` to `/ 2` or `+ 5` and run again to see the numbers update.",
    "SELECT name, plants, plants * 2 AS leaves_est\nFROM growers;",
  ),
  sq(
    "sql-like",
    "LIKE: Pattern Matching",
    "Find text that starts with, ends with or contains something.",
    10,
    "Searching text with wildcards",
    "LIKE matches text against a pattern. `%` stands for any run of characters and `_` stands for exactly one character. `'Y%'` means 'starts with Y', `'%a'` means 'ends with a', and `'%ma%'` means 'contains ma'. LIKE ignores case in SQLite for plain ASCII letters.",
    "SELECT name FROM growers WHERE name LIKE 'S%';\nSELECT city FROM growers WHERE city LIKE '%y%';",
    "The query finds growers whose name starts with S. Change the pattern to `'%a'` to find names ending in a, then run again.",
    "SELECT name, city\nFROM growers\nWHERE name LIKE 'S%';",
  ),
  sq(
    "sql-in",
    "IN: Match a List",
    "Test whether a value is one of several choices.",
    8,
    "One column, several allowed values",
    "IN checks whether a value appears in a list you give in brackets. It is a shorter, clearer way to write several OR conditions. `city IN ('Yangon', 'Mandalay')` means the same as `city = 'Yangon' OR city = 'Mandalay'`. Add NOT IN to exclude a list instead.",
    "SELECT name, city\nFROM growers\nWHERE city IN ('Yangon', 'Mandalay');",
    "The query keeps growers in Yangon or Mandalay. Change IN to NOT IN and run again to see everyone else.",
    "SELECT name, city\nFROM growers\nWHERE city IN ('Yangon', 'Mandalay');",
  ),
  sq(
    "sql-between",
    "BETWEEN: Ranges",
    "Match values that fall inside a range, endpoints included.",
    8,
    "Filtering a range",
    "BETWEEN a AND b keeps values from a to b, including both ends. It works on numbers, text and dates. `plants BETWEEN 8 AND 15` is the same as `plants >= 8 AND plants <= 15` but shorter to read.",
    "SELECT name, plants\nFROM growers\nWHERE plants BETWEEN 8 AND 15;",
    "The query keeps growers with 8 to 15 plants. Widen the range to `5 AND 20` and run again to include everyone.",
    "SELECT name, plants\nFROM growers\nWHERE plants BETWEEN 8 AND 15;",
  ),
  sq(
    "sql-not",
    "NOT & Combining Conditions",
    "Invert a condition and mix AND, OR and NOT safely.",
    9,
    "Saying 'not this'",
    "NOT flips a condition from true to false. Combine it with AND and OR to build precise filters. When you mix AND and OR, wrap the OR part in brackets so the logic is clear — brackets decide what groups together, just like in maths.",
    "SELECT name, city, plants\nFROM growers\nWHERE NOT city = 'Yangon';\n\nSELECT name FROM growers\nWHERE plants > 10 AND (city = 'Yangon' OR city = 'Mandalay');",
    "The query lists growers not in Yangon. Change `NOT city = 'Yangon'` to `city <> 'Mandalay'` and run again — both ways say 'not equal'.",
    "SELECT name, city, plants\nFROM growers\nWHERE NOT city = 'Yangon';",
  ),
  sq(
    "sql-order-multi",
    "Sorting by Several Columns",
    "Break ties by sorting on a second column.",
    9,
    "First key, then tie-breaker",
    "ORDER BY can list more than one column. Rows are sorted by the first column; where those are equal, the next column decides. Each column can have its own ASC or DESC. Here growers sort by city, and within each city by plants from most to fewest.",
    "SELECT name, city, plants\nFROM growers\nORDER BY city ASC, plants DESC;",
    "The query groups by city then ranks plants inside each city. Swap the two sort columns around and run again to see the order change.",
    "SELECT name, city, plants\nFROM growers\nORDER BY city ASC, plants DESC;",
  ),
  sq(
    "sql-limit-offset",
    "LIMIT & OFFSET: Paging",
    "Take a page of rows, skipping the ones before it.",
    9,
    "Showing results one page at a time",
    "LIMIT sets how many rows come back; OFFSET skips rows before it starts counting. Together they build 'pages': OFFSET 0 LIMIT 2 is page one, OFFSET 2 LIMIT 2 is page two. Always pair paging with ORDER BY, or the order is not guaranteed.",
    "SELECT name, plants FROM growers\nORDER BY plants DESC\nLIMIT 2 OFFSET 2;",
    "The query returns the second page of two rows. Change OFFSET to 0 for the first page, then 4 for the last, and run each time.",
    "SELECT name, plants\nFROM growers\nORDER BY plants DESC\nLIMIT 2 OFFSET 2;",
  ),
  sq(
    "sql-count-distinct",
    "COUNT(DISTINCT)",
    "Count how many different values a column has.",
    8,
    "Counting unique values",
    "COUNT(*) counts rows, but COUNT(DISTINCT column) counts how many different values appear. 'How many cities have growers?' is COUNT(DISTINCT city) — five growers, but fewer distinct cities. This pattern answers 'how many unique …' questions.",
    "SELECT COUNT(*) AS growers,\n       COUNT(DISTINCT city) AS cities\nFROM growers;",
    "The query counts growers and distinct cities side by side. Change `city` to `plants` to count how many different plant totals exist.",
    "SELECT COUNT(*) AS growers,\n       COUNT(DISTINCT city) AS cities\nFROM growers;",
  ),
  sq(
    "sql-min-max-group",
    "MIN & MAX per Group",
    "Find the smallest and largest value inside each group.",
    10,
    "Extremes within groups",
    "MIN and MAX are aggregates like SUM and AVG, so they combine with GROUP BY. Grouping by city and asking for MAX(plants) gives the biggest grower in each city. You can return several aggregates in one query to get a compact summary.",
    "SELECT city,\n       MIN(plants) AS smallest,\n       MAX(plants) AS largest\nFROM growers\nGROUP BY city;",
    "The query shows the smallest and largest grower per city. Add `, AVG(plants) AS average` to the SELECT list and run again.",
    "SELECT city,\n       MIN(plants) AS smallest,\n       MAX(plants) AS largest\nFROM growers\nGROUP BY city;",
  ),
  sq(
    "sql-having-deep",
    "HAVING: Filtering Groups",
    "Keep only the groups whose summary meets a condition.",
    10,
    "WHERE for groups",
    "WHERE filters rows before grouping; HAVING filters the groups afterwards, using an aggregate. 'Only cities whose growers total more than 20 plants' cannot be written with WHERE because the total does not exist until after grouping — that is exactly HAVING's job.",
    "SELECT city, SUM(plants) AS total\nFROM growers\nGROUP BY city\nHAVING SUM(plants) > 20;",
    "The query keeps cities with over 20 plants in total. Change the threshold to `> 10` and run again to include more cities.",
    "SELECT city, SUM(plants) AS total\nFROM growers\nGROUP BY city\nHAVING SUM(plants) > 20;",
  ),
  sq(
    "sql-left-join",
    "LEFT JOIN: Keep Every Row",
    "Include rows that have no match on the other side.",
    11,
    "Nobody left behind",
    "A plain JOIN drops rows with no match. A LEFT JOIN keeps every row from the left table and fills the missing right-side columns with NULL (empty). Growers Aung and Kyaw grow no strains, so a LEFT JOIN still lists them — with a blank strain — while a plain JOIN would hide them.",
    "SELECT growers.name AS grower, strains.name AS strain\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id;",
    "The query lists every grower, even those with no strain. Change LEFT JOIN back to JOIN and run again — the growers with no strain disappear.",
    "SELECT growers.name AS grower, strains.name AS strain\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id;",
  ),
  sq(
    "sql-null",
    "Working with NULL",
    "Test for missing values with IS NULL and IS NOT NULL.",
    9,
    "The empty value",
    "NULL means 'no value' — not zero and not an empty string. Because NULL is unknown, you cannot test it with `=`; you must use IS NULL or IS NOT NULL. A LEFT JOIN creates NULLs where there was no match, so this is how you find growers with no strain.",
    "SELECT growers.name AS grower\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id\nWHERE strains.id IS NULL;",
    "The query finds growers who grow no strain. Change IS NULL to IS NOT NULL and run again to list growers who do have strains.",
    "SELECT growers.name AS grower\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id\nWHERE strains.id IS NULL;",
  ),
  sq(
    "sql-join-aggregate",
    "JOIN + GROUP BY",
    "Count and summarise across joined tables.",
    12,
    "Summaries over linked data",
    "Joins and aggregates combine naturally. Join growers to strains, group by the grower, and COUNT to answer 'how many strains does each grower have?'. Use a LEFT JOIN so growers with zero strains still appear with a count of 0.",
    "SELECT growers.name AS grower,\n       COUNT(strains.id) AS strain_count\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id\nGROUP BY growers.id;",
    "The query counts strains per grower. Add `ORDER BY strain_count DESC` at the end to rank the busiest growers, then run again.",
    "SELECT growers.name AS grower,\n       COUNT(strains.id) AS strain_count\nFROM growers\nLEFT JOIN strains ON strains.grower_id = growers.id\nGROUP BY growers.id;",
  ),
  sq(
    "sql-subquery",
    "Subqueries in WHERE",
    "Use one query's result inside another.",
    12,
    "A query inside a query",
    "A subquery is a SELECT written inside another statement, in brackets. The inner query runs first and its result feeds the outer one. Here the inner query finds the average plant count, and the outer query keeps growers above that average — without you typing the number by hand.",
    "SELECT name, plants\nFROM growers\nWHERE plants > (SELECT AVG(plants) FROM growers);",
    "The query lists growers with more than the average plants. Change `>` to `<` and run again to find below-average growers.",
    "SELECT name, plants\nFROM growers\nWHERE plants > (SELECT AVG(plants) FROM growers);",
  ),
  sq(
    "sql-subquery-in",
    "Subqueries with IN",
    "Filter by a list that another query produces.",
    11,
    "Match against a computed list",
    "A subquery can return a whole column, which you then test with IN. Here the inner query collects the grower_id of every indica strain, and the outer query keeps growers whose id is in that list — the growers who grow at least one indica.",
    "SELECT name, city\nFROM growers\nWHERE id IN (\n  SELECT grower_id FROM strains WHERE type = 'indica'\n);",
    "The query finds growers of indica strains. Change 'indica' to 'sativa' and run again to find sativa growers.",
    "SELECT name, city\nFROM growers\nWHERE id IN (\n  SELECT grower_id FROM strains WHERE type = 'indica'\n);",
  ),
  sq(
    "sql-case",
    "CASE: If/Then in SQL",
    "Turn values into labels with conditional logic.",
    11,
    "Choosing a result per row",
    "CASE is SQL's if/then. It checks conditions in order and returns the first matching result, or the ELSE value if none match. Use it to bucket numbers into labels — here plant counts become 'small', 'medium' or 'large' garden sizes.",
    "SELECT name, plants,\n  CASE\n    WHEN plants >= 15 THEN 'large'\n    WHEN plants >= 8  THEN 'medium'\n    ELSE 'small'\n  END AS size\nFROM growers;",
    "The query labels each grower's garden size. Change the `15` threshold to `12` and run again to see labels shift.",
    "SELECT name, plants,\n  CASE\n    WHEN plants >= 15 THEN 'large'\n    WHEN plants >= 8  THEN 'medium'\n    ELSE 'small'\n  END AS size\nFROM growers;",
  ),
  sq(
    "sql-string-funcs",
    "Text Functions",
    "Reshape text with UPPER, LENGTH, SUBSTR and ||.",
    10,
    "Cleaning and joining text",
    "SQLite has handy text functions. UPPER and LOWER change case, LENGTH counts characters, SUBSTR(text, start, count) cuts out part of a string, and `||` glues strings together. Combine them to build readable labels straight from the data.",
    "SELECT UPPER(name) AS shout,\n       LENGTH(city) AS city_len,\n       name || ' of ' || city AS label\nFROM growers;",
    "The query shows three text tricks at once. Change UPPER to LOWER, or change the `' of '` text between the names, and run again.",
    "SELECT UPPER(name) AS shout,\n       LENGTH(city) AS city_len,\n       name || ' of ' || city AS label\nFROM growers;",
  ),
  sq(
    "sql-round",
    "Numbers: ROUND & AVG",
    "Tidy up averages and other decimals.",
    9,
    "Rounding results",
    "AVG often produces long decimals. ROUND(value, places) trims them to a set number of decimal places — ROUND(x, 1) keeps one. Wrapping an aggregate in ROUND gives clean, presentable numbers. You can round any expression, not just averages.",
    "SELECT type,\n       ROUND(AVG(weeks), 1) AS avg_weeks\nFROM strains\nGROUP BY type;",
    "The query shows the average flowering weeks per strain type, rounded to one decimal. Change the `1` to `0` and run again for whole numbers.",
    "SELECT type,\n       ROUND(AVG(weeks), 1) AS avg_weeks\nFROM strains\nGROUP BY type;",
  ),
  sq(
    "sql-union",
    "UNION: Stack Results",
    "Combine the rows of two queries into one list.",
    10,
    "Putting result sets on top of each other",
    "UNION stacks the rows of two SELECTs into a single result. Both queries must return the same number of columns with matching types. UNION removes duplicate rows; UNION ALL keeps every row, which is faster when you know there are no duplicates. Here we tag rows from each table before stacking.",
    "SELECT name, 'grower' AS kind FROM growers\nUNION ALL\nSELECT name, 'strain' AS kind FROM strains\nORDER BY kind, name;",
    "The query builds one combined list of growers and strains, each tagged. Change UNION ALL to UNION and run again — with a tag column there are still no duplicates to remove.",
    "SELECT name, 'grower' AS kind FROM growers\nUNION ALL\nSELECT name, 'strain' AS kind FROM strains\nORDER BY kind, name;",
  ),
];
