// SQL course — third batch (30 → 60). Every lesson is runnable (kind "sql")
// against the same in-browser SQLite seeded in sql-playground.tsx —
// growers(id, name, city, plants) and strains(id, name, type, weeks,
// grower_id). SQLite-compatible only (CTEs, window functions, no RIGHT/FULL
// JOIN). Burmese explanations + a YouTube hint. Original content for GreenWave.

import type { Lesson } from "@/lib/learn/lessons";

function sq(
  slug: string,
  title: string,
  summary: string,
  minutes: number,
  youtubeQuery: string,
  explainBody: string,
  explainCode: string,
  tryBody: string,
  sqlCode: string,
): Lesson {
  return {
    slug,
    title,
    summary,
    minutes,
    kind: "sql",
    youtubeQuery,
    sections: [
      { heading: "ရှင်းလင်းချက်", body: explainBody, code: explainCode },
      { heading: "စမ်းကြည့်ပါ", body: tryBody },
    ],
    sqlCode,
  };
}

export const SQL_EXTRA2: Lesson[] = [
  sq(
    "sql-create-table",
    "CREATE TABLE",
    "ဇယားအသစ် တည်ဆောက်ပြီး data ထည့်ခြင်း။",
    9,
    "SQL CREATE TABLE tutorial",
    "`CREATE TABLE` က ဇယားအသစ် ဖန်တီးသည် — column တစ်ခုစီအတွက် နာမည်နဲ့ အမျိုးအစား (INTEGER, TEXT, REAL) သတ်မှတ်ရသည်။ `PRIMARY KEY` က row တစ်ခုစီကို ထူးခြားစေတဲ့ column။",
    "CREATE TABLE tools (id INTEGER PRIMARY KEY, name TEXT, price INTEGER);",
    "အောက်က query က tools ဇယား ဆောက်၊ row နှစ်ခု ထည့်ပြီး ပြန်ဖတ်သည်။ column အမျိုးအစား ပြောင်းကြည့်ပါ။",
    "CREATE TABLE tools (id INTEGER PRIMARY KEY, name TEXT, price INTEGER);\nINSERT INTO tools VALUES (1, 'Trowel', 3000), (2, 'Hose', 8000);\nSELECT * FROM tools;",
  ),
  sq(
    "sql-alter-table",
    "ALTER TABLE",
    "ရှိပြီးသား ဇယားကို column ထပ်ထည့်ခြင်း။",
    8,
    "SQL ALTER TABLE ADD COLUMN tutorial",
    "`ALTER TABLE ... ADD COLUMN` က ဇယားဟောင်းကို data မဖျက်ဘဲ column အသစ် ထပ်ထည့်ပေးသည်။ အသစ်ထည့်တဲ့ column က ရှိပြီးသား row များအတွက် NULL ဖြစ်နေမည်။",
    "ALTER TABLE growers ADD COLUMN region TEXT;",
    "temp ဇယားတစ်ခု ဆောက်ပြီး column ထပ်ထည့်ကြည့်ပါ — မူရင်း growers ကို မထိအောင် tmp သုံးထားသည်။",
    "CREATE TABLE tmp (id INTEGER, name TEXT);\nINSERT INTO tmp VALUES (1, 'A'), (2, 'B');\nALTER TABLE tmp ADD COLUMN score INTEGER;\nSELECT * FROM tmp;",
  ),
  sq(
    "sql-delete-rows",
    "DELETE",
    "စည်းကမ်းနဲ့ ကိုက်ညီတဲ့ row များ ဖျက်ခြင်း။",
    8,
    "SQL DELETE statement tutorial",
    "`DELETE FROM ဇယား WHERE ...` က WHERE နဲ့ ကိုက်တဲ့ row များ ဖျက်သည်။ **WHERE မထည့်ရင် row အားလုံး ပျက်သည် — အလွန်သတိထားပါ။**",
    "DELETE FROM tmp WHERE score < 50;",
    "temp ဇယားမှာ row အချို့ ဖျက်ကြည့်ပါ (မူရင်း data ကို မထိရန် tmp သုံးထားသည်)။",
    "CREATE TABLE tmp (id INTEGER, plants INTEGER);\nINSERT INTO tmp VALUES (1, 5), (2, 20), (3, 3);\nDELETE FROM tmp WHERE plants < 10;\nSELECT * FROM tmp;",
  ),
  sq(
    "sql-cross-join",
    "CROSS JOIN",
    "ဇယားနှစ်ခုရဲ့ row အားလုံး အတွဲဆွဲခြင်း။",
    8,
    "SQL cross join tutorial",
    "`CROSS JOIN` က ဇယား A ရဲ့ row တိုင်းကို ဇယား B ရဲ့ row တိုင်းနဲ့ တွဲ (Cartesian product) — A မှာ ၃ ခု, B မှာ ၄ ခုဆို ၁၂ တွဲ။ ON condition မလို။",
    "SELECT a.name, b.type FROM growers a CROSS JOIN strains b;",
    "grower ၂ ယောက်နဲ့ strain type အားလုံး တွဲကြည့်ပါ — အတွဲ ဘယ်နှစ်ခု ထွက်လဲ ရေတွက်ကြည့်ပါ။",
    "SELECT g.name AS grower, s.type\nFROM growers g\nCROSS JOIN (SELECT DISTINCT type FROM strains) s\nLIMIT 12;",
  ),
  sq(
    "sql-cte",
    "CTE (WITH)",
    "query ကို ဖတ်ရလွယ်အောင် အပိုင်းများ ခွဲရေးခြင်း။",
    10,
    "SQL common table expression WITH tutorial",
    "`WITH နာမည် AS (...)` က subquery ကို ရှေ့မှာ နာမည်တပ်၍ ခေတ္တ ဇယားလို သုံးစေသည် — CTE (Common Table Expression)။ nested subquery ရှုပ်တာထက် အဆင့်လိုက် ဖတ်ရလွယ်။",
    "WITH big AS (SELECT * FROM growers WHERE plants > 10)\nSELECT name FROM big;",
    "plants > 10 ဖြစ်တဲ့ grower များကို CTE နဲ့ ရွေးပြီး ၎င်းတို့ကို ဆက်စစ်ကြည့်ပါ။",
    "WITH big AS (\n  SELECT * FROM growers WHERE plants > 10\n)\nSELECT name, city, plants FROM big ORDER BY plants DESC;",
  ),
  sq(
    "sql-cte-multi",
    "CTE များစွာ",
    "WITH ထဲမှာ ဇယားများစွာ တွဲသုံးခြင်း။",
    10,
    "SQL multiple CTE with clause",
    "`WITH a AS (...), b AS (...)` — comma ခြားပြီး CTE များစွာ ကြေညာနိုင်သည်။ တစ်ခုက အခြားတစ်ခုကို ကိုးကားနိုင်လို့ ရှုပ်ထွေးတဲ့ query ကို အဆင့်ဆင့် တည်ဆောက်နိုင်။",
    "WITH a AS (...), b AS (SELECT * FROM a WHERE ...) SELECT * FROM b;",
    "grower အလိုက် strain အရေအတွက်ကို CTE တစ်ခုမှာ တွက်ပြီး နောက် CTE မှာ စစ်ထုတ်ကြည့်ပါ။",
    "WITH counts AS (\n  SELECT grower_id, COUNT(*) AS n FROM strains GROUP BY grower_id\n),\nbusy AS (\n  SELECT * FROM counts WHERE n >= 2\n)\nSELECT g.name, b.n FROM busy b JOIN growers g ON g.id = b.grower_id;",
  ),
  sq(
    "sql-recursive-cte",
    "Recursive CTE",
    "ကိုယ့်ကိုယ်ကို ကိုးကား၍ sequence/tree ဖန်တီးခြင်း။",
    11,
    "SQL recursive CTE tutorial",
    "`WITH RECURSIVE` က ကိုယ့်ကိုယ်ကို ပြန်ကိုးကား၍ ကိန်းစဉ်, ရက်စွဲစဉ်, tree/hierarchy များ ဖန်တီးသည် — base case + recursive part ကို UNION ALL နဲ့ ဆက်သည်။",
    "WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<5) SELECT x FROM n;",
    "၁ မှ ၁၀ အထိ ကိန်းစဉ် ထုတ်ကြည့်ပါ။ WHERE ရဲ့ ကန့်သတ်ချက်ကို ပြောင်းကြည့်ပါ။",
    "WITH RECURSIVE nums(x) AS (\n  SELECT 1\n  UNION ALL\n  SELECT x + 1 FROM nums WHERE x < 10\n)\nSELECT x FROM nums;",
  ),
  sq(
    "sql-subquery-select",
    "Subquery in SELECT",
    "column တစ်ခုအဖြစ် subquery တွက်ခြင်း။",
    9,
    "SQL subquery in select column",
    "SELECT list ထဲမှာ subquery ထည့်၍ row တစ်ခုစီအတွက် တန်ဖိုးတစ်ခု တွက်နိုင်သည်။ ဥပမာ grower တစ်ယောက်စီရဲ့ strain အရေအတွက်ကို subquery နဲ့ ယူ။",
    "SELECT name, (SELECT COUNT(*) FROM strains WHERE grower_id = g.id) AS n FROM growers g;",
    "grower တစ်ယောက်စီအတွက် ၎င်းရဲ့ strain အရေအတွက်ကို subquery column နဲ့ ပြကြည့်ပါ။",
    "SELECT g.name,\n  (SELECT COUNT(*) FROM strains s WHERE s.grower_id = g.id) AS strain_count\nFROM growers g;",
  ),
  sq(
    "sql-correlated-subquery",
    "Correlated Subquery",
    "အပြင် row ကို ကိုးကားတဲ့ subquery။",
    10,
    "SQL correlated subquery tutorial",
    "correlated subquery က အပြင် query ရဲ့ row တစ်ခုစီအတွက် ပြန်ပြန်ပြီး run သည် — အထဲက query က အပြင် row ကို ကိုးကားသည် (`g.id`)။ 'ပျမ်းမျှထက် များတဲ့' လို နှိုင်းယှဉ်ချက်များအတွက်။",
    "SELECT name FROM growers g WHERE plants > (SELECT AVG(plants) FROM growers);",
    "plants က တစ်နိုင်ငံလုံး ပျမ်းမျှထက် များတဲ့ grower များ ရှာကြည့်ပါ။",
    "SELECT name, plants\nFROM growers g\nWHERE plants > (SELECT AVG(plants) FROM growers)\nORDER BY plants DESC;",
  ),
  sq(
    "sql-exists",
    "EXISTS",
    "ဆက်စပ် row ရှိ/မရှိ စစ်ဆေးခြင်း။",
    9,
    "SQL EXISTS operator tutorial",
    "`EXISTS (subquery)` က subquery မှာ row အနည်းဆုံးတစ်ခု ရှိရင် true ပြန်ပေးသည်။ 'strain ရှိတဲ့ grower' လို ဆက်စပ်မှု စစ်ရာမှာ JOIN ထက် ရိုးရှင်း၊ မြန်တတ်။",
    "SELECT name FROM growers g WHERE EXISTS (SELECT 1 FROM strains s WHERE s.grower_id = g.id);",
    "strain အနည်းဆုံး တစ်ခု ရှိတဲ့ grower များ ရှာကြည့်ပါ။ `NOT EXISTS` နဲ့ တစ်ခုမှ မရှိသူများ ရှာကြည့်ပါ။",
    "SELECT name FROM growers g\nWHERE EXISTS (SELECT 1 FROM strains s WHERE s.grower_id = g.id);",
  ),
  sq(
    "sql-window-over",
    "Window Functions — OVER",
    "row များ အုပ်စုချုံ့မဖျက်ဘဲ တွက်ချက်ခြင်း။",
    11,
    "SQL window functions OVER tutorial",
    "window function က `OVER (...)` နဲ့ တွက်သည် — GROUP BY နဲ့မတူ၊ row များ **မပျောက်** ဘဲ row တစ်ခုစီဘေးမှာ စုစုပေါင်း/ပျမ်းမျှ တွဲပြပေးသည်။",
    "SELECT name, plants, AVG(plants) OVER () AS avg_all FROM growers;",
    "grower တစ်ယောက်စီရဲ့ plants ဘေးမှာ တစ်နိုင်ငံလုံး ပျမ်းမျှကို တွဲပြကြည့်ပါ။",
    "SELECT name, plants,\n  AVG(plants) OVER () AS avg_all,\n  SUM(plants) OVER () AS total\nFROM growers;",
  ),
  sq(
    "sql-row-number",
    "ROW_NUMBER()",
    "row များကို အစဉ်နံပါတ် တပ်ခြင်း။",
    9,
    "SQL ROW_NUMBER window function",
    "`ROW_NUMBER() OVER (ORDER BY ...)` က row များကို သတ်မှတ်ထားတဲ့ အစဉ်အတိုင်း ၁, ၂, ၃ ... နံပါတ်တပ်ပေးသည် — leaderboard, pagination, 'top N per group' အတွက် အခြေခံ။",
    "SELECT name, ROW_NUMBER() OVER (ORDER BY plants DESC) AS rank FROM growers;",
    "plants အများဆုံးကနေ အစဉ်လိုက် နံပါတ်တပ်ကြည့်ပါ။",
    "SELECT name, plants,\n  ROW_NUMBER() OVER (ORDER BY plants DESC) AS position\nFROM growers;",
  ),
  sq(
    "sql-rank",
    "RANK နဲ့ DENSE_RANK",
    "အဆင့်သတ်မှတ်ခြင်း — သရေ ကိုင်တွယ်ပုံ။",
    10,
    "SQL RANK DENSE_RANK difference",
    "`RANK()` က တူညီတန်ဖိုး (သရေ) ကို အဆင့်တူ ပေးပြီး နောက်အဆင့်ကို ကျော်သည် (1,1,3)။ `DENSE_RANK()` က မကျော်ဘဲ ဆက်သည် (1,1,2)။ `ROW_NUMBER` က သရေ မခွဲဘဲ ကွဲကွဲ ပေးသည်။",
    "SELECT name, RANK() OVER (ORDER BY plants DESC) AS r FROM growers;",
    "RANK နဲ့ DENSE_RANK နှစ်ခုကို တစ်ပြိုင်တည်း ပြပြီး ကွာခြားချက် ကြည့်ကြည့်ပါ။",
    "SELECT name, plants,\n  RANK() OVER (ORDER BY plants DESC) AS rnk,\n  DENSE_RANK() OVER (ORDER BY plants DESC) AS dense\nFROM growers;",
  ),
  sq(
    "sql-partition-by",
    "PARTITION BY",
    "အုပ်စုအလိုက် window တွက်ချက်ခြင်း။",
    10,
    "SQL window PARTITION BY tutorial",
    "`OVER (PARTITION BY col ...)` က window ကို အုပ်စုများ (partition) ခွဲ၍ အုပ်စုတစ်ခုစီအတွင်း သီးခြား တွက်သည် — GROUP BY နဲ့ ဆင်ပေမဲ့ row များ မပျောက်။ 'အုပ်စုအလိုက် အဆင့်' အတွက်။",
    "SELECT type, name, RANK() OVER (PARTITION BY type ORDER BY weeks) FROM strains;",
    "strain type တစ်ခုစီအတွင်း weeks နည်းစဉ်လိုက် အဆင့်တပ်ကြည့်ပါ။",
    "SELECT type, name, weeks,\n  RANK() OVER (PARTITION BY type ORDER BY weeks) AS rank_in_type\nFROM strains;",
  ),
  sq(
    "sql-lag-lead",
    "LAG နဲ့ LEAD",
    "အရှေ့/အနောက် row ရဲ့ တန်ဖိုး ယူခြင်း။",
    10,
    "SQL LAG LEAD window function",
    "`LAG(col)` က ရှေ့ row ရဲ့ တန်ဖိုး, `LEAD(col)` က နောက် row ရဲ့ တန်ဖိုးကို ယူသည် — ယခင်နဲ့ ယခု နှိုင်းယှဉ်ခြင်း (ကြီးထွားနှုန်း, ကွာခြားချက်) အတွက်။",
    "SELECT name, plants, LAG(plants) OVER (ORDER BY plants) AS prev FROM growers;",
    "plants အစဉ်လိုက် စီပြီး row တစ်ခုစီရဲ့ ရှေ့တန်ဖိုးကို တွဲပြ — ကွာခြားချက် တွက်ကြည့်ပါ။",
    "SELECT name, plants,\n  LAG(plants) OVER (ORDER BY plants) AS prev_plants,\n  plants - LAG(plants) OVER (ORDER BY plants) AS diff\nFROM growers;",
  ),
  sq(
    "sql-running-total",
    "Running Total",
    "စုစည်း ပေါင်းလဒ် (cumulative sum)။",
    10,
    "SQL running total window function",
    "`SUM(col) OVER (ORDER BY ...)` က row တစ်ခုစီအထိ စုစည်းပေါင်းလဒ် (running total) တွက်ပေးသည် — အရောင်း တဖြည်းဖြည်း တိုးလာပုံ, balance ပြောင်းလဲမှု ခြေရာခံရာမှာ အသုံးဝင်။",
    "SELECT name, plants, SUM(plants) OVER (ORDER BY id) AS running FROM growers;",
    "grower များကို id အစဉ်လိုက် plants စုစည်းပေါင်းလဒ် တွက်ကြည့်ပါ။",
    "SELECT name, plants,\n  SUM(plants) OVER (ORDER BY id) AS running_total\nFROM growers;",
  ),
  sq(
    "sql-ntile",
    "NTILE — အုပ်စုခွဲ",
    "row များကို အညီအမျှ အုပ်စုများ ခွဲခြင်း။",
    9,
    "SQL NTILE window function tutorial",
    "`NTILE(n)` က row များကို အစဉ်လိုက် n အုပ်စု (bucket) အညီအမျှ ခွဲပေးသည် — quartile (၄ ပိုင်း), percentile band, top/mid/bottom အုပ်စု ခွဲရာမှာ သုံးသည်။",
    "SELECT name, NTILE(3) OVER (ORDER BY plants DESC) AS tier FROM growers;",
    "grower များကို plants အလိုက် ၃ အုပ်စု (အထက်/အလယ်/အောက်) ခွဲကြည့်ပါ။",
    "SELECT name, plants,\n  NTILE(3) OVER (ORDER BY plants DESC) AS tier\nFROM growers;",
  ),
  sq(
    "sql-coalesce",
    "COALESCE နဲ့ NULLIF",
    "NULL ကို ကိုင်တွယ်ခြင်း။",
    8,
    "SQL COALESCE NULLIF tutorial",
    "`COALESCE(a, b, c)` က ပထမဆုံး NULL မဟုတ်တဲ့ တန်ဖိုးကို ပြန်ပေးသည် — NULL နေရာမှာ default ထည့်ရာမှာ သုံး။ `NULLIF(a, b)` က a=b ဆို NULL ပြန်ပေးသည် (သုညနဲ့ စားခြင်း ကာကွယ်ရာမှာ အသုံးဝင်)။",
    "SELECT COALESCE(NULL, 'unknown');  -- 'unknown'",
    "city ကို ယူပြီး NULL ဆိုရင် 'N/A' အစားထိုးကြည့်ပါ (temp data နဲ့)။",
    "SELECT name, COALESCE(city, 'N/A') AS city\nFROM growers;",
  ),
  sq(
    "sql-cast",
    "CAST — အမျိုးအစားပြောင်း",
    "column ရဲ့ data type ပြောင်းလဲခြင်း။",
    8,
    "SQL CAST convert type tutorial",
    "`CAST(value AS type)` က တန်ဖိုးတစ်ခုကို အမျိုးအစားအသစ် (INTEGER, REAL, TEXT) ပြောင်းပေးသည် — string ကို ဂဏန်းအဖြစ်, ဂဏန်းကို စာသားအဖြစ် ပြောင်းရာမှာ။",
    "SELECT CAST(plants AS REAL) / 2 FROM growers;",
    "plants ကို REAL အဖြစ် ပြောင်းပြီး ၂ နဲ့ စားကြည့်ပါ — integer စားခြင်းနဲ့ ရလဒ် ကွာသည်။",
    "SELECT name, plants,\n  CAST(plants AS REAL) / 3 AS third\nFROM growers;",
  ),
  sq(
    "sql-conditional-sum",
    "Conditional Aggregation",
    "SUM(CASE WHEN ...) — အခြေအနေအလိုက် ပေါင်းခြင်း။",
    10,
    "SQL SUM CASE WHEN conditional aggregation",
    "`SUM(CASE WHEN condition THEN 1 ELSE 0 END)` က အခြေအနေ ကိုက်တဲ့ row များကို ရေတွက်/ပေါင်းသည် — အုပ်စုတစ်ခုအတွင်း အမျိုးအစားများစွာ တစ်ပြိုင်တည်း တွက်ရာမှာ အလွန်အသုံးဝင်။",
    "SELECT SUM(CASE WHEN plants > 10 THEN 1 ELSE 0 END) AS big FROM growers;",
    "grower အားလုံးထဲက 'plants > 10' နဲ့ 'plants <= 10' အရေအတွက်ကို တစ်ကြောင်းတည်း တွက်ကြည့်ပါ။",
    "SELECT\n  SUM(CASE WHEN plants > 10 THEN 1 ELSE 0 END) AS big_growers,\n  SUM(CASE WHEN plants <= 10 THEN 1 ELSE 0 END) AS small_growers\nFROM growers;",
  ),
  sq(
    "sql-pivot",
    "Pivot (CASE)",
    "row များကို column အဖြစ် လှည့်ခြင်း။",
    11,
    "SQL pivot table CASE WHEN",
    "SQLite မှာ PIVOT keyword မရှိ — `SUM(CASE WHEN type='X' THEN 1 ELSE 0 END)` ကို GROUP BY နဲ့ တွဲ၍ row များကို column အဖြစ် လှည့်ပြနိုင်သည်။ report/dashboard အတွက်။",
    "SELECT SUM(CASE WHEN type='indica' THEN 1 END) AS indica FROM strains;",
    "strain type တစ်ခုစီရဲ့ အရေအတွက်ကို column အဖြစ် ဘေးချင်းယှဉ် ပြကြည့်ပါ။",
    "SELECT\n  COUNT(*) AS total,\n  SUM(CASE WHEN type='indica' THEN 1 ELSE 0 END) AS indica,\n  SUM(CASE WHEN type='sativa' THEN 1 ELSE 0 END) AS sativa\nFROM strains;",
  ),
  sq(
    "sql-concat",
    "String Concatenation (||)",
    "စာသားများ ပေါင်းစပ်ခြင်း။",
    7,
    "SQL string concatenation tutorial",
    "SQLite မှာ `||` operator က string များ ပေါင်းသည် (CONCAT မဟုတ်)။ column နဲ့ စာသားကို ရောပြီး ဖတ်ရလွယ်တဲ့ label ဖန်တီးနိုင်။",
    "SELECT name || ' (' || city || ')' AS label FROM growers;",
    "grower name နဲ့ city ကို ပေါင်းပြီး 'Name (City)' ပုံစံ label ဖန်တီးကြည့်ပါ။",
    "SELECT name || ' — ' || plants || ' plants' AS summary\nFROM growers;",
  ),
  sq(
    "sql-substr",
    "SUBSTR — စာသားဖြတ်",
    "string ရဲ့ အပိုင်း ထုတ်ယူခြင်း။",
    8,
    "SQL SUBSTR string function",
    "`SUBSTR(text, start, length)` က string ရဲ့ တစ်စိတ်တစ်ပိုင်း ထုတ်သည် (start က 1 ကနေ စ)။ `LENGTH(text)` က စာလုံးရေ။ code, prefix, initial ထုတ်ရာမှာ။",
    "SELECT SUBSTR(name, 1, 3) FROM growers;",
    "grower name ရဲ့ ပထမ စာလုံး ၃ လုံးနဲ့ စာလုံးရေ စုစုပေါင်းကို ပြကြည့်ပါ။",
    "SELECT name,\n  SUBSTR(name, 1, 3) AS prefix,\n  LENGTH(name) AS len\nFROM growers;",
  ),
  sq(
    "sql-replace-trim",
    "REPLACE, TRIM, UPPER/LOWER",
    "စာသား သန့်စင်/ပြောင်းလဲခြင်း။",
    8,
    "SQL string functions REPLACE TRIM UPPER",
    "`REPLACE(text, a, b)` က a ကို b နဲ့ အစားထိုး, `TRIM(text)` က အစ/အဆုံး ကွက်လပ် ဖယ်, `UPPER`/`LOWER` က စာလုံးအကြီး/အသေး ပြောင်း — data သန့်စင်ရာမှာ အခြေခံ။",
    "SELECT UPPER(name), REPLACE(city, 'a', '*') FROM growers;",
    "name ကို စာလုံးအကြီး, city ထဲက စာလုံးတစ်ခု အစားထိုးကြည့်ပါ။",
    "SELECT name,\n  UPPER(name) AS upper_name,\n  LOWER(city) AS lower_city\nFROM growers;",
  ),
  sq(
    "sql-glob",
    "GLOB Pattern",
    "case-sensitive pattern ရှာခြင်း။",
    8,
    "SQL GLOB pattern matching tutorial",
    "`GLOB` က LIKE နဲ့ ဆင်ပေမဲ့ case-sensitive ဖြစ်ပြီး Unix wildcard (`*` = စာလုံးမည်မျှမဆို, `?` = တစ်လုံး) သုံးသည်။ `[abc]` က စာလုံးအစု။",
    "SELECT name FROM growers WHERE name GLOB 'A*';",
    "'A' နဲ့ စတဲ့ grower name များ ရှာကြည့်ပါ။ pattern ကို ပြောင်းကြည့်ပါ။",
    "SELECT name, city FROM growers\nWHERE name GLOB '[A-M]*';",
  ),
  sq(
    "sql-group-concat",
    "GROUP_CONCAT",
    "အုပ်စုတစ်ခုရဲ့ တန်ဖိုးများ စာသားတစ်ကြောင်းအဖြစ် ပေါင်းခြင်း။",
    9,
    "SQL GROUP_CONCAT aggregate tutorial",
    "`GROUP_CONCAT(col, separator)` က အုပ်စုတစ်ခုအတွင်း တန်ဖိုးများကို comma (သို့ သတ်မှတ်တဲ့ separator) နဲ့ စာသားတစ်ကြောင်းအဖြစ် ပေါင်းသည် — 'grower တစ်ယောက်ရဲ့ strain အားလုံး' စာရင်းလို ပြရာမှာ။",
    "SELECT grower_id, GROUP_CONCAT(name) FROM strains GROUP BY grower_id;",
    "grower တစ်ယောက်စီရဲ့ strain အမည်များကို တစ်ကြောင်းတည်း စုပြကြည့်ပါ။",
    "SELECT g.name AS grower,\n  GROUP_CONCAT(s.name, ', ') AS strains\nFROM growers g\nJOIN strains s ON s.grower_id = g.id\nGROUP BY g.id;",
  ),
  sq(
    "sql-order-case",
    "ORDER BY Expression",
    "စိတ်ကြိုက် အစဉ်လိုက် စီခြင်း။",
    9,
    "SQL ORDER BY case expression custom sort",
    "`ORDER BY` မှာ column တင်မက expression/CASE လည်း သုံးနိုင်သည် — 'featured အရင်, ကျန်တာ နောက်' လို စိတ်ကြိုက် အစဉ်လိုက် စီရာမှာ။",
    "SELECT name FROM strains ORDER BY CASE type WHEN 'sativa' THEN 0 ELSE 1 END, name;",
    "strain များကို 'sativa' အရင်, ကျန်တာ နောက်မှာ ထား၍ စီကြည့်ပါ။",
    "SELECT name, type FROM strains\nORDER BY CASE type WHEN 'sativa' THEN 0 ELSE 1 END, weeks;",
  ),
  sq(
    "sql-views",
    "Views (CREATE VIEW)",
    "query ကို ဇယားတစ်ခုလို သိမ်းထားခြင်း။",
    9,
    "SQL CREATE VIEW tutorial",
    "`CREATE VIEW နာမည် AS SELECT ...` က query တစ်ခုကို 'virtual table' အဖြစ် သိမ်းသည် — ရှုပ်ထွေးတဲ့ query ကို တစ်ကြိမ်ရေး၍ နာမည်နဲ့ ထပ်ခါထပ်ခါ သုံးနိုင်။ data မကူးဘဲ query သာ သိမ်းသည်။",
    "CREATE VIEW big_growers AS SELECT * FROM growers WHERE plants > 10;",
    "big_growers view ဆောက်ပြီး ဇယားလို query လုပ်ကြည့်ပါ။",
    "CREATE VIEW big_growers AS\n  SELECT name, plants FROM growers WHERE plants > 10;\nSELECT * FROM big_growers ORDER BY plants DESC;",
  ),
  sq(
    "sql-having-vs-where",
    "HAVING vs WHERE",
    "စစ်ထုတ်ခြင်း ဘယ်အဆင့်မှာ လုပ်မလဲ။",
    9,
    "SQL HAVING vs WHERE difference",
    "`WHERE` က GROUP BY **မလုပ်ခင်** row များကို စစ်ထုတ်သည်။ `HAVING` က group **လုပ်ပြီးနောက်** အုပ်စုများကို (aggregate ရလဒ်နဲ့) စစ်ထုတ်သည်။ COUNT/SUM နဲ့ စစ်ချင်ရင် HAVING။",
    "SELECT city, COUNT(*) FROM growers GROUP BY city HAVING COUNT(*) > 1;",
    "grower ၂ ယောက်အထက် ရှိတဲ့ မြို့များ ရှာကြည့်ပါ — WHERE နဲ့ လုပ်လို့ မရကြောင်း သတိပြုပါ။",
    "SELECT city, COUNT(*) AS n, AVG(plants) AS avg_plants\nFROM growers\nGROUP BY city\nHAVING COUNT(*) >= 1\nORDER BY n DESC;",
  ),
  sq(
    "sql-project-analytics",
    "Project — Analytics Query",
    "CTE + JOIN + window ပေါင်း၍ report ဆွဲခြင်း။",
    12,
    "SQL analytics query CTE window join",
    "သင်ယူထားသမျှ ပေါင်း — CTE နဲ့ grower အလိုက် strain အရေအတွက် တွက်, JOIN နဲ့ နာမည်ချိတ်, window function (RANK) နဲ့ အဆင့်တပ်။ ဒါက စစ်မှန်တဲ့ data analyst query ရဲ့ ပုံစံ။",
    "WITH s AS (SELECT grower_id, COUNT(*) n FROM strains GROUP BY grower_id) ...",
    "grower အလိုက် strain အရေအတွက် + plants အဆင့်ကို report တစ်ခုအဖြစ် ထုတ်ကြည့်ပါ။",
    "WITH strain_counts AS (\n  SELECT grower_id, COUNT(*) AS strains\n  FROM strains GROUP BY grower_id\n)\nSELECT g.name, g.plants,\n  COALESCE(sc.strains, 0) AS strains,\n  RANK() OVER (ORDER BY g.plants DESC) AS plant_rank\nFROM growers g\nLEFT JOIN strain_counts sc ON sc.grower_id = g.id\nORDER BY plant_rank;",
  ),
];
