// Language-learning module for GreenWave Learn.
//
// Burmese speakers learn English, Thai and Chinese. Everything here is static
// content — no database, no external service. The interactive practice (listen,
// speak-and-check, typing) runs entirely in the browser via the Web Speech API
// (speechSynthesis for text-to-speech, SpeechRecognition for pronunciation
// scoring), so a lesson works offline once the page has loaded.

/** A single vocabulary item / phrase in a unit. */
export interface Phrase {
  /** The word or phrase in the target language (what TTS speaks). */
  target: string;
  /** A romanised pronunciation hint, friendly for a Burmese reader. */
  roman: string;
  /** The Burmese meaning. */
  my: string;
  /** A small illustrative emoji shown on the card. */
  emoji: string;
}

/** A themed unit within a language course. */
export interface LangUnit {
  slug: string;
  /** Unit title in Burmese. */
  title: string;
  /** Unit title in the target language / English, for the sub-label. */
  subtitle: string;
  emoji: string;
  items: Phrase[];
}

/** A full language course. */
export interface LangCourse {
  /** URL slug, e.g. "english". */
  slug: string;
  /** ISO-ish label used in the UI. */
  label: string;
  /** The language's own name. */
  nativeLabel: string;
  flag: string;
  /**
   * BCP-47 tag passed to speechSynthesis + SpeechRecognition so the browser
   * picks the right voice and recogniser (e.g. "en-US", "th-TH", "zh-CN").
   */
  bcp47: string;
  /** Short description in Burmese. */
  description: string;
  units: LangUnit[];
}

// ---------------------------------------------------------------------------
// English
// ---------------------------------------------------------------------------
const ENGLISH: LangCourse = {
  slug: "english",
  label: "English",
  nativeLabel: "English",
  flag: "🇬🇧",
  bcp47: "en-US",
  description: "အင်္ဂလိပ်စကား — နှုတ်ဆက်ခြင်းမှ ခရီးသွားစကားအထိ။",
  units: [
    {
      slug: "greetings",
      title: "နှုတ်ဆက်ခြင်း",
      subtitle: "Greetings",
      emoji: "👋",
      items: [
        { target: "Hello", roman: "ဟဲလို", my: "မင်္ဂလာပါ / ဟယ်လို", emoji: "👋" },
        { target: "Good morning", roman: "ဂွတ် မော်နင်း", my: "မင်္ဂလာနံနက်ခင်းပါ", emoji: "🌅" },
        { target: "Good night", roman: "ဂွတ် နိုက်", my: "ညချမ်းသာပါစေ", emoji: "🌙" },
        { target: "Thank you", roman: "သင့်ကျူး", my: "ကျေးဇူးတင်ပါတယ်", emoji: "🙏" },
        { target: "Sorry", roman: "ဆော်ရီ", my: "တောင်းပန်ပါတယ်", emoji: "😔" },
        { target: "How are you?", roman: "ဟောင်း အာ ယူ", my: "နေကောင်းလား", emoji: "🙂" },
        { target: "I am fine", roman: "အိုင်း အမ် ဖိုင်း", my: "ကျွန်တော် နေကောင်းပါတယ်", emoji: "👍" },
        { target: "Goodbye", roman: "ဂွတ်ဘိုင်း", my: "သွားတော့မယ် / ဘိုင်ဘိုင်", emoji: "👋" },
      ],
    },
    {
      slug: "numbers",
      title: "ဂဏန်းများ",
      subtitle: "Numbers 1–10",
      emoji: "🔢",
      items: [
        { target: "One", roman: "ဝမ်း", my: "တစ် (၁)", emoji: "1️⃣" },
        { target: "Two", roman: "တူး", my: "နှစ် (၂)", emoji: "2️⃣" },
        { target: "Three", roman: "သရီး", my: "သုံး (၃)", emoji: "3️⃣" },
        { target: "Four", roman: "ဖော်", my: "လေး (၄)", emoji: "4️⃣" },
        { target: "Five", roman: "ဖိုက်ဗ်", my: "ငါး (၅)", emoji: "5️⃣" },
        { target: "Six", roman: "စစ်ခ်", my: "ခြောက် (၆)", emoji: "6️⃣" },
        { target: "Seven", roman: "ဆဲဗင်", my: "ခုနစ် (၇)", emoji: "7️⃣" },
        { target: "Ten", roman: "တဲန်", my: "ဆယ် (၁၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "food",
      title: "အစားအသောက်",
      subtitle: "Food & drink",
      emoji: "🍽️",
      items: [
        { target: "Water", roman: "ဝေါ်တာ", my: "ရေ", emoji: "💧" },
        { target: "Rice", roman: "ရိုက်စ်", my: "ထမင်း", emoji: "🍚" },
        { target: "Tea", roman: "တီး", my: "လက်ဖက်ရည်", emoji: "🍵" },
        { target: "Coffee", roman: "ကော်ဖီ", my: "ကော်ဖီ", emoji: "☕" },
        { target: "Delicious", roman: "ဒီးလစ်ရှပ်စ်", my: "စားလို့ကောင်းတယ်", emoji: "😋" },
        { target: "I am hungry", roman: "အိုင်း အမ် ဟန်ဂရီ", my: "ကျွန်တော် ဗိုက်ဆာတယ်", emoji: "🍽️" },
        { target: "The bill, please", roman: "ဒ ဘေး ပလိစ်", my: "ငွေရှင်းမယ်", emoji: "🧾" },
        { target: "How much?", roman: "ဟောင်း မတ်ချ်", my: "ဘယ်လောက်လဲ", emoji: "💰" },
      ],
    },
    {
      slug: "travel",
      title: "ခရီးသွား",
      subtitle: "Getting around",
      emoji: "🧭",
      items: [
        { target: "Where is the toilet?", roman: "ဝဲ အီးစ် ဒ တွိုင်းလက်", my: "အိမ်သာ ဘယ်မှာလဲ", emoji: "🚻" },
        { target: "Help me", roman: "ဟဲလ့်ပ် မီး", my: "ကူညီပါ", emoji: "🆘" },
        { target: "Turn left", roman: "တန်း လက်ဖ်", my: "ဘယ်ဘက်ကွေ့", emoji: "⬅️" },
        { target: "Turn right", roman: "တန်း ရိုက်", my: "ညာဘက်ကွေ့", emoji: "➡️" },
        { target: "Go straight", roman: "ဂို စတရိတ်", my: "တည့်တည့်သွား", emoji: "⬆️" },
        { target: "Stop here", roman: "စတော့ ဟီးယား", my: "ဒီမှာ ရပ်ပါ", emoji: "🛑" },
        { target: "Airport", roman: "အဲရ်ပို့", my: "လေဆိပ်", emoji: "✈️" },
        { target: "Hospital", roman: "ဟော့စ်ပီတယ်", my: "ဆေးရုံ", emoji: "🏥" },
      ],
    },
    {
      slug: "colors",
      title: "အရောင်များ",
      subtitle: "Colors",
      emoji: "🎨",
      items: [
        { target: "Red", roman: "ရက်ဒ်", my: "အနီ", emoji: "🔴" },
        { target: "Blue", roman: "ဘလူး", my: "အပြာ", emoji: "🔵" },
        { target: "Green", roman: "ဂရင်း", my: "အစိမ်း", emoji: "🟢" },
        { target: "Yellow", roman: "ယဲလိုး", my: "အဝါ", emoji: "🟡" },
        { target: "Black", roman: "ဘလက်ခ်", my: "အနက်", emoji: "⚫" },
        { target: "White", roman: "ဝှိုက်", my: "အဖြူ", emoji: "⚪" },
        { target: "Orange", roman: "အော်ရိန်း", my: "လိမ္မော်ရောင်", emoji: "🟠" },
        { target: "Pink", roman: "ပင့်ခ်", my: "ပန်းရောင်", emoji: "🩷" },
      ],
    },
    {
      slug: "family",
      title: "မိသားစု",
      subtitle: "Family",
      emoji: "👨‍👩‍👧",
      items: [
        { target: "Mother", roman: "မာသာ", my: "အမေ", emoji: "👩" },
        { target: "Father", roman: "ဖာသာ", my: "အဖေ", emoji: "👨" },
        { target: "Sister", roman: "ဆစ်စတာ", my: "အစ်မ/ညီမ", emoji: "👧" },
        { target: "Brother", roman: "ဘရာသာ", my: "အစ်ကို/ညီ", emoji: "👦" },
        { target: "Son", roman: "ဆန်း", my: "သား", emoji: "👦" },
        { target: "Daughter", roman: "ဒေါ်တာ", my: "သမီး", emoji: "👧" },
        { target: "Grandmother", roman: "ဂရန်းမာသာ", my: "အဖွား", emoji: "👵" },
        { target: "Grandfather", roman: "ဂရန်းဖာသာ", my: "အဖိုး", emoji: "👴" },
      ],
    },
    {
      slug: "days",
      title: "ရက်သတ္တပတ်",
      subtitle: "Days of the week",
      emoji: "📅",
      items: [
        { target: "Monday", roman: "မန်းဒေး", my: "တနင်္လာ", emoji: "1️⃣" },
        { target: "Tuesday", roman: "ကျူးစ်ဒေး", my: "အင်္ဂါ", emoji: "2️⃣" },
        { target: "Wednesday", roman: "ဝဲန်းစ်ဒေး", my: "ဗုဒ္ဓဟူး", emoji: "3️⃣" },
        { target: "Thursday", roman: "သာစ်ဒေး", my: "ကြာသပတေး", emoji: "4️⃣" },
        { target: "Friday", roman: "ဖရိုင်းဒေး", my: "သောကြာ", emoji: "5️⃣" },
        { target: "Saturday", roman: "ဆက်တာဒေး", my: "စနေ", emoji: "6️⃣" },
        { target: "Sunday", roman: "ဆန်းဒေး", my: "တနင်္ဂနွေ", emoji: "7️⃣" },
      ],
    },
    {
      slug: "numbers-teens",
      title: "ဂဏန်း ၁၁–၂၀",
      subtitle: "Numbers 11–20",
      emoji: "🔢",
      items: [
        { target: "Eleven", roman: "အီလဲဗင်", my: "ဆယ့်တစ် (၁၁)", emoji: "1️⃣" },
        { target: "Twelve", roman: "တွဲလ်ဗ်", my: "ဆယ့်နှစ် (၁၂)", emoji: "2️⃣" },
        { target: "Thirteen", roman: "သာတင်း", my: "ဆယ့်သုံး (၁၃)", emoji: "3️⃣" },
        { target: "Fourteen", roman: "ဖော်တင်း", my: "ဆယ့်လေး (၁၄)", emoji: "4️⃣" },
        { target: "Fifteen", roman: "ဖစ်ဖ်တင်း", my: "ဆယ့်ငါး (၁၅)", emoji: "5️⃣" },
        { target: "Sixteen", roman: "စစ်စ်တင်း", my: "ဆယ့်ခြောက် (၁၆)", emoji: "6️⃣" },
        { target: "Seventeen", roman: "ဆဲဗင်တင်း", my: "ဆယ့်ခုနစ် (၁၇)", emoji: "7️⃣" },
        { target: "Eighteen", roman: "အိတ်တင်း", my: "ဆယ့်ရှစ် (၁၈)", emoji: "8️⃣" },
        { target: "Nineteen", roman: "နိုင်းတင်း", my: "ဆယ့်ကိုး (၁၉)", emoji: "9️⃣" },
        { target: "Twenty", roman: "တွဲန်တီ", my: "နှစ်ဆယ် (၂၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "months",
      title: "လများ (၁၂ လ)",
      subtitle: "Months",
      emoji: "📅",
      items: [
        { target: "January", roman: "ဂျန်နျူအာရီ", my: "ဇန်နဝါရီ", emoji: "❄️" },
        { target: "February", roman: "ဖက်ဗြူအာရီ", my: "ဖေဖော်ဝါရီ", emoji: "💝" },
        { target: "March", roman: "မတ်ချ်", my: "မတ်", emoji: "🌱" },
        { target: "April", roman: "အေပရယ်", my: "ဧပြီ", emoji: "🌧️" },
        { target: "May", roman: "မေ", my: "မေ", emoji: "🌸" },
        { target: "June", roman: "ဂျွန်း", my: "ဇွန်", emoji: "☀️" },
        { target: "July", roman: "ဂျူလိုင်", my: "ဇူလိုင်", emoji: "🎆" },
        { target: "August", roman: "အော်ဂတ်စ်", my: "သြဂုတ်", emoji: "🏖️" },
        { target: "September", roman: "စက်ပ်တင်ဘာ", my: "စက်တင်ဘာ", emoji: "🍂" },
        { target: "October", roman: "အောက်တိုဘာ", my: "အောက်တိုဘာ", emoji: "🎃" },
        { target: "November", roman: "နိုဗင်ဘာ", my: "နိုဝင်ဘာ", emoji: "🍁" },
        { target: "December", roman: "ဒီဇင်ဘာ", my: "ဒီဇင်ဘာ", emoji: "🎄" },
      ],
    },
    {
      slug: "body-parts",
      title: "ခန္ဓာကိုယ် အစိတ်အပိုင်း",
      subtitle: "Body parts",
      emoji: "🧍",
      items: [
        { target: "Head", roman: "ဟဲဒ်", my: "ခေါင်း", emoji: "👤" },
        { target: "Hair", roman: "ဟဲယာ", my: "ဆံပင်", emoji: "💇" },
        { target: "Eye", roman: "အိုင်း", my: "မျက်လုံး", emoji: "👁️" },
        { target: "Ear", roman: "အီးယား", my: "နား", emoji: "👂" },
        { target: "Nose", roman: "နိုးစ်", my: "နှာခေါင်း", emoji: "👃" },
        { target: "Mouth", roman: "မောက်သ်", my: "ပါးစပ်", emoji: "👄" },
        { target: "Tooth", roman: "တုသ်", my: "သွား", emoji: "🦷" },
        { target: "Hand", roman: "ဟန်းဒ်", my: "လက်", emoji: "✋" },
        { target: "Arm", roman: "အာမ်", my: "လက်မောင်း", emoji: "💪" },
        { target: "Leg", roman: "လဲဂ်", my: "ခြေထောက်", emoji: "🦵" },
        { target: "Stomach", roman: "စတမ့်ခ်", my: "ဗိုက်", emoji: "🫃" },
        { target: "Heart", roman: "ဟတ်", my: "နှလုံး", emoji: "❤️" },
      ],
    },
    {
      slug: "weather",
      title: "ရာသီဥတု",
      subtitle: "Weather",
      emoji: "🌦️",
      items: [
        { target: "Sunny", roman: "ဆန်နီ", my: "နေသာသည်", emoji: "☀️" },
        { target: "Rain", roman: "ရိန်း", my: "မိုးရွာ", emoji: "🌧️" },
        { target: "Cloudy", roman: "ကလောင်ဒီ", my: "တိမ်ထူသည်", emoji: "☁️" },
        { target: "Wind", roman: "ဝင်းဒ်", my: "လေ", emoji: "🌬️" },
        { target: "Hot", roman: "ဟော့တ်", my: "ပူသည်", emoji: "🔥" },
        { target: "Cold", roman: "ကိုးလ်ဒ်", my: "အေးသည်", emoji: "🥶" },
        { target: "Storm", roman: "စတော့မ်", my: "မုန်တိုင်း", emoji: "⛈️" },
        { target: "Snow", roman: "စနိုး", my: "နှင်း", emoji: "❄️" },
        { target: "Rainbow", roman: "ရိန်းဘိုး", my: "သက်တံ့", emoji: "🌈" },
        { target: "Fog", roman: "ဖော့ဂ်", my: "မြူဆိုင်း", emoji: "🌫️" },
      ],
    },
    {
      slug: "house-rooms",
      title: "အိမ်နှင့် အခန်းများ",
      subtitle: "House & rooms",
      emoji: "🏠",
      items: [
        { target: "House", roman: "ဟောက်စ်", my: "အိမ်", emoji: "🏠" },
        { target: "Door", roman: "ဒေါ်", my: "တံခါး", emoji: "🚪" },
        { target: "Window", roman: "ဝင်းဒိုး", my: "ပြတင်းပေါက်", emoji: "🪟" },
        { target: "Kitchen", roman: "ကစ်ခ်ချင်", my: "မီးဖိုချောင်", emoji: "🍳" },
        { target: "Bedroom", roman: "ဘဲဒ်ရွမ်", my: "အိပ်ခန်း", emoji: "🛌" },
        { target: "Bathroom", roman: "ဘတ်ရွမ်", my: "ရေချိုးခန်း", emoji: "🛁" },
        { target: "Living room", roman: "လီဗင်း ရွမ်", my: "ဧည့်ခန်း", emoji: "🛋️" },
        { target: "Table", roman: "တေဘယ်", my: "စားပွဲ", emoji: "🍽️" },
        { target: "Chair", roman: "ချဲယာ", my: "ကုလားထိုင်", emoji: "🪑" },
        { target: "Bed", roman: "ဘဲဒ်", my: "ကုတင်", emoji: "🛏️" },
      ],
    },
    {
      slug: "transport",
      title: "သယ်ယူပို့ဆောင်ရေး",
      subtitle: "Transport",
      emoji: "🚗",
      items: [
        { target: "Car", roman: "ကား", my: "ကား", emoji: "🚗" },
        { target: "Bus", roman: "ဘတ်စ်", my: "ဘတ်စ်ကား", emoji: "🚌" },
        { target: "Train", roman: "ထရိန်း", my: "ရထား", emoji: "🚆" },
        { target: "Bicycle", roman: "ဘိုက်ဆီကယ်", my: "စက်ဘီး", emoji: "🚲" },
        { target: "Motorbike", roman: "မိုတာဘိုက်", my: "မော်တော်ဆိုင်ကယ်", emoji: "🏍️" },
        { target: "Airplane", roman: "အဲယားပလိန်း", my: "လေယာဉ်", emoji: "✈️" },
        { target: "Boat", roman: "ဘုတ်", my: "လှေ / သင်္ဘော", emoji: "⛵" },
        { target: "Taxi", roman: "တက်ဆီ", my: "တက္ကစီ", emoji: "🚕" },
        { target: "Truck", roman: "ထရပ်", my: "ကုန်တင်ကား", emoji: "🚚" },
        { target: "Road", roman: "ရုတ်ဒ်", my: "လမ်း", emoji: "🛣️" },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Thai
// ---------------------------------------------------------------------------
const THAI: LangCourse = {
  slug: "thai",
  label: "Thai",
  nativeLabel: "ภาษาไทย",
  flag: "🇹🇭",
  bcp47: "th-TH",
  description: "ထိုင်းစကား — မြန်မာ-ထိုင်း နေ့စဉ်သုံးစကား။",
  units: [
    {
      slug: "greetings",
      title: "နှုတ်ဆက်ခြင်း",
      subtitle: "การทักทาย",
      emoji: "🙏",
      items: [
        { target: "สวัสดี", roman: "ဆဝပ်ဒီး", my: "မင်္ဂလာပါ", emoji: "🙏" },
        { target: "ขอบคุณ", roman: "ခေါ့ခုန်", my: "ကျေးဇူးတင်ပါတယ်", emoji: "🙏" },
        { target: "สบายดีไหม", roman: "ဆဘိုင်ဒီ မိုင်း", my: "နေကောင်းလား", emoji: "🙂" },
        { target: "สบายดี", roman: "ဆဘိုင်ဒီး", my: "နေကောင်းပါတယ်", emoji: "👍" },
        { target: "ขอโทษ", roman: "ခေါ်သုတ်", my: "တောင်းပန်ပါတယ်", emoji: "😔" },
        { target: "ไม่เป็นไร", roman: "မိုင် ပဲန် ရိုင်း", my: "ကိစ္စမရှိပါဘူး", emoji: "🙆" },
        { target: "ลาก่อน", roman: "လာ ကွန်း", my: "သွားတော့မယ်", emoji: "👋" },
        { target: "ยินดี", roman: "ရင်ဒီး", my: "ဝမ်းသာပါတယ်", emoji: "😊" },
      ],
    },
    {
      slug: "numbers",
      title: "ဂဏန်းများ",
      subtitle: "ตัวเลข",
      emoji: "🔢",
      items: [
        { target: "หนึ่ง", roman: "နိုင်း", my: "တစ် (၁)", emoji: "1️⃣" },
        { target: "สอง", roman: "ဆောင်", my: "နှစ် (၂)", emoji: "2️⃣" },
        { target: "สาม", roman: "ဆမ်", my: "သုံး (၃)", emoji: "3️⃣" },
        { target: "สี่", roman: "စီး", my: "လေး (၄)", emoji: "4️⃣" },
        { target: "ห้า", roman: "ဟား", my: "ငါး (၅)", emoji: "5️⃣" },
        { target: "หก", roman: "ဟုတ်", my: "ခြောက် (၆)", emoji: "6️⃣" },
        { target: "เจ็ด", roman: "ဂျက်", my: "ခုနစ် (၇)", emoji: "7️⃣" },
        { target: "สิบ", roman: "ဆစ်ပ်", my: "ဆယ် (၁၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "food",
      title: "အစားအသောက်",
      subtitle: "อาหาร",
      emoji: "🍜",
      items: [
        { target: "น้ำ", roman: "နမ်", my: "ရေ", emoji: "💧" },
        { target: "ข้าว", roman: "ခေါ့", my: "ထမင်း", emoji: "🍚" },
        { target: "อร่อย", roman: "အရွိုင်း", my: "စားလို့ကောင်းတယ်", emoji: "😋" },
        { target: "เผ็ด", roman: "ဖက်", my: "စပ်တယ်", emoji: "🌶️" },
        { target: "ไม่เผ็ด", roman: "မိုင် ဖက်", my: "မစပ်ပါနဲ့", emoji: "🚫" },
        { target: "อิ่มแล้ว", roman: "အင်မ် လဲဝ်", my: "ဗိုက်ပြည့်ပြီ", emoji: "🍽️" },
        { target: "เท่าไหร่", roman: "ထောင်ရိုင်း", my: "ဘယ်လောက်လဲ", emoji: "💰" },
        { target: "เก็บเงิน", roman: "ကဲပ် ငိုန်း", my: "ငွေရှင်းမယ်", emoji: "🧾" },
      ],
    },
    {
      slug: "travel",
      title: "ခရီးသွား",
      subtitle: "การเดินทาง",
      emoji: "🧭",
      items: [
        { target: "ห้องน้ำอยู่ที่ไหน", roman: "ဟောင်နမ် ယူ ထီ နိုင်း", my: "အိမ်သာ ဘယ်မှာလဲ", emoji: "🚻" },
        { target: "ช่วยด้วย", roman: "ချွေ ဒွေး", my: "ကူညီပါ", emoji: "🆘" },
        { target: "เลี้ยวซ้าย", roman: "လျဲဝ် ဆိုင်း", my: "ဘယ်ဘက်ကွေ့", emoji: "⬅️" },
        { target: "เลี้ยวขวา", roman: "လျဲဝ် ခွာ", my: "ညာဘက်ကွေ့", emoji: "➡️" },
        { target: "ตรงไป", roman: "တရုံ ပိုင်း", my: "တည့်တည့်သွား", emoji: "⬆️" },
        { target: "หยุดตรงนี้", roman: "ယွတ် တရုံ နီး", my: "ဒီမှာ ရပ်ပါ", emoji: "🛑" },
        { target: "สนามบิน", roman: "ဆနမ် ဘင်", my: "လေဆိပ်", emoji: "✈️" },
        { target: "โรงพยาบาล", roman: "ရုံ ဖယာဘန်", my: "ဆေးရုံ", emoji: "🏥" },
      ],
    },
    {
      slug: "colors",
      title: "အရောင်များ",
      subtitle: "สี",
      emoji: "🎨",
      items: [
        { target: "สีแดง", roman: "စီ ဒဲင်", my: "အနီ", emoji: "🔴" },
        { target: "สีน้ำเงิน", roman: "စီ နမ်ငိုန်", my: "အပြာ", emoji: "🔵" },
        { target: "สีเขียว", roman: "စီ ခဲဝ်", my: "အစိမ်း", emoji: "🟢" },
        { target: "สีเหลือง", roman: "စီ လွမ်", my: "အဝါ", emoji: "🟡" },
        { target: "สีดำ", roman: "စီ ဒမ်", my: "အနက်", emoji: "⚫" },
        { target: "สีขาว", roman: "စီ ခေါ့", my: "အဖြူ", emoji: "⚪" },
        { target: "สีส้ม", roman: "စီ ဆုမ်", my: "လိမ္မော်ရောင်", emoji: "🟠" },
        { target: "สีชมพู", roman: "စီ ချုမ်ဖူး", my: "ပန်းရောင်", emoji: "🩷" },
      ],
    },
    {
      slug: "family",
      title: "မိသားစု",
      subtitle: "ครอบครัว",
      emoji: "👨‍👩‍👧",
      items: [
        { target: "แม่", roman: "မဲ", my: "အမေ", emoji: "👩" },
        { target: "พ่อ", roman: "ဖေါ်", my: "အဖေ", emoji: "👨" },
        { target: "พี่สาว", roman: "ဖီ ဆော်", my: "အစ်မ", emoji: "👧" },
        { target: "น้องสาว", roman: "နောင် ဆော်", my: "ညီမ", emoji: "👧" },
        { target: "พี่ชาย", roman: "ဖီ ချိုင်း", my: "အစ်ကို", emoji: "👦" },
        { target: "ลูก", roman: "လူးခ်", my: "သားသမီး", emoji: "🧒" },
        { target: "ยาย", roman: "ယိုင်း", my: "အဖွား", emoji: "👵" },
        { target: "ปู่", roman: "ပူး", my: "အဖိုး", emoji: "👴" },
      ],
    },
    {
      slug: "days",
      title: "ရက်သတ္တပတ်",
      subtitle: "วันในสัปดาห์",
      emoji: "📅",
      items: [
        { target: "วันจันทร์", roman: "ဝမ် ဂျန်", my: "တနင်္လာ", emoji: "1️⃣" },
        { target: "วันอังคาร", roman: "ဝမ် အန်ကာန်", my: "အင်္ဂါ", emoji: "2️⃣" },
        { target: "วันพุธ", roman: "ဝမ် ဖုတ်", my: "ဗုဒ္ဓဟူး", emoji: "3️⃣" },
        { target: "วันพฤหัสบดี", roman: "ဝမ် ဖရုဟတ်", my: "ကြာသပတေး", emoji: "4️⃣" },
        { target: "วันศุกร์", roman: "ဝမ် ဆုတ်", my: "သောကြာ", emoji: "5️⃣" },
        { target: "วันเสาร์", roman: "ဝမ် ဆော", my: "စနေ", emoji: "6️⃣" },
        { target: "วันอาทิตย์", roman: "ဝမ် အားတိတ်", my: "တနင်္ဂနွေ", emoji: "7️⃣" },
      ],
    },
    {
      slug: "numbers-teens",
      title: "ဂဏန်း ၁၁–၂၀",
      subtitle: "ตัวเลข 11–20",
      emoji: "🔢",
      items: [
        { target: "สิบเอ็ด", roman: "ဆစ်ပ် အဲတ်", my: "ဆယ့်တစ် (၁၁)", emoji: "1️⃣" },
        { target: "สิบสอง", roman: "ဆစ်ပ် ဆောင်", my: "ဆယ့်နှစ် (၁၂)", emoji: "2️⃣" },
        { target: "สิบสาม", roman: "ဆစ်ပ် ဆမ်", my: "ဆယ့်သုံး (၁၃)", emoji: "3️⃣" },
        { target: "สิบสี่", roman: "ဆစ်ပ် စီး", my: "ဆယ့်လေး (၁၄)", emoji: "4️⃣" },
        { target: "สิบห้า", roman: "ဆစ်ပ် ဟား", my: "ဆယ့်ငါး (၁၅)", emoji: "5️⃣" },
        { target: "สิบหก", roman: "ဆစ်ပ် ဟုတ်", my: "ဆယ့်ခြောက် (၁၆)", emoji: "6️⃣" },
        { target: "สิบเจ็ด", roman: "ဆစ်ပ် ဂျက်", my: "ဆယ့်ခုနစ် (၁၇)", emoji: "7️⃣" },
        { target: "สิบแปด", roman: "ဆစ်ပ် ပဲတ်", my: "ဆယ့်ရှစ် (၁၈)", emoji: "8️⃣" },
        { target: "สิบเก้า", roman: "ဆစ်ပ် ကောင်", my: "ဆယ့်ကိုး (၁၉)", emoji: "9️⃣" },
        { target: "ยี่สิบ", roman: "ယီး ဆစ်ပ်", my: "နှစ်ဆယ် (၂၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "months",
      title: "လများ (၁၂ လ)",
      subtitle: "เดือน",
      emoji: "📅",
      items: [
        { target: "มกราคม", roman: "မော့ ကရာ ခွမ်", my: "ဇန်နဝါရီ", emoji: "❄️" },
        { target: "กุมภาพันธ์", roman: "ကွမ် ဖာ ပန်", my: "ဖေဖော်ဝါရီ", emoji: "💝" },
        { target: "มีนาคม", roman: "မီ နာ ခွမ်", my: "မတ်", emoji: "🌱" },
        { target: "เมษายน", roman: "မေ ဆာ ယွန်", my: "ဧပြီ", emoji: "🌧️" },
        { target: "พฤษภาคม", roman: "ဖရိတ် ဆ ဖာ ခွမ်", my: "မေ", emoji: "🌸" },
        { target: "มิถุนายน", roman: "မိ ထု နာ ယွန်", my: "ဇွန်", emoji: "☀️" },
        { target: "กรกฎาคม", roman: "ကာ ရ က ဒါ ခွမ်", my: "ဇူလိုင်", emoji: "🎆" },
        { target: "สิงหาคม", roman: "စိင် ဟာ ခွမ်", my: "သြဂုတ်", emoji: "🏖️" },
        { target: "กันยายน", roman: "ကန် ယာ ယွန်", my: "စက်တင်ဘာ", emoji: "🍂" },
        { target: "ตุลาคม", roman: "တု လာ ခွမ်", my: "အောက်တိုဘာ", emoji: "🎃" },
        { target: "พฤศจิกายน", roman: "ဖရိတ် ဆ ဂျိ ကာ ယွန်", my: "နိုဝင်ဘာ", emoji: "🍁" },
        { target: "ธันวาคม", roman: "သန် ဝါ ခွမ်", my: "ဒီဇင်ဘာ", emoji: "🎄" },
      ],
    },
    {
      slug: "body-parts",
      title: "ခန္ဓာကိုယ် အစိတ်အပိုင်း",
      subtitle: "ร่างกาย",
      emoji: "🧍",
      items: [
        { target: "หัว", roman: "ဟွ (hǔa)", my: "ခေါင်း", emoji: "👤" },
        { target: "ผม", roman: "ဖုမ် (phǒm)", my: "ဆံပင်", emoji: "💇" },
        { target: "ตา", roman: "တာ (taa)", my: "မျက်လုံး", emoji: "👁️" },
        { target: "หู", roman: "ဟူး (hǔu)", my: "နား", emoji: "👂" },
        { target: "จมูก", roman: "ဂျ မုက် (jamùuk)", my: "နှာခေါင်း", emoji: "👃" },
        { target: "ปาก", roman: "ပါက် (pàak)", my: "ပါးစပ်", emoji: "👄" },
        { target: "ฟัน", roman: "ဖန် (fan)", my: "သွား", emoji: "🦷" },
        { target: "มือ", roman: "မိုး (mʉʉ)", my: "လက်", emoji: "✋" },
        { target: "แขน", roman: "ခဲန် (khǎen)", my: "လက်မောင်း", emoji: "💪" },
        { target: "ขา", roman: "ခါ (khǎa)", my: "ခြေထောက်", emoji: "🦵" },
        { target: "ท้อง", roman: "ထောင် (tháawng)", my: "ဗိုက်", emoji: "🫃" },
        { target: "หัวใจ", roman: "ဟွ ဂျိုင် (hǔajai)", my: "နှလုံး", emoji: "❤️" },
      ],
    },
    {
      slug: "weather",
      title: "ရာသီဥတု",
      subtitle: "อากาศ",
      emoji: "🌦️",
      items: [
        { target: "แดด", roman: "ဒဲ့ (dàet)", my: "နေသာ", emoji: "☀️" },
        { target: "ฝน", roman: "ဖုန် (fǒn)", my: "မိုး", emoji: "🌧️" },
        { target: "เมฆ", roman: "မဲက် (mêek)", my: "တိမ်", emoji: "☁️" },
        { target: "ลม", roman: "လုမ် (lom)", my: "လေ", emoji: "🌬️" },
        { target: "ร้อน", roman: "ရောန် (ráawn)", my: "ပူသည်", emoji: "🔥" },
        { target: "หนาว", roman: "နောင် (nǎaw)", my: "အေးသည်", emoji: "🥶" },
        { target: "พายุ", roman: "ဖာယု (phaayú)", my: "မုန်တိုင်း", emoji: "⛈️" },
        { target: "หิมะ", roman: "ဟိမ (hìmá)", my: "နှင်း", emoji: "❄️" },
        { target: "รุ้ง", roman: "ရုင် (rúng)", my: "သက်တံ့", emoji: "🌈" },
        { target: "หมอก", roman: "မောက် (màawk)", my: "မြူ", emoji: "🌫️" },
      ],
    },
    {
      slug: "house-rooms",
      title: "အိမ်နှင့် အခန်းများ",
      subtitle: "บ้าน",
      emoji: "🏠",
      items: [
        { target: "บ้าน", roman: "ဘန် (bâan)", my: "အိမ်", emoji: "🏠" },
        { target: "ประตู", roman: "ပရတူး (pratuu)", my: "တံခါး", emoji: "🚪" },
        { target: "หน้าต่าง", roman: "နာ တာင် (nâatàang)", my: "ပြတင်းပေါက်", emoji: "🪟" },
        { target: "ครัว", roman: "ခရွ (khrua)", my: "မီးဖိုချောင်", emoji: "🍳" },
        { target: "ห้องนอน", roman: "ဟောင် နောန် (hâawngnaawn)", my: "အိပ်ခန်း", emoji: "🛌" },
        { target: "ห้องน้ำ", roman: "ဟောင် နာမ် (hâawngnáam)", my: "ရေချိုးခန်း", emoji: "🛁" },
        { target: "ห้องนั่งเล่น", roman: "ဟောင် နန် လေန် (hâawngnânglên)", my: "ဧည့်ခန်း", emoji: "🛋️" },
        { target: "โต๊ะ", roman: "တော့ (tó)", my: "စားပွဲ", emoji: "🍽️" },
        { target: "เก้าอี้", roman: "ကောင် အီး (kâo-îi)", my: "ကုလားထိုင်", emoji: "🪑" },
        { target: "เตียง", roman: "တျန် (tiang)", my: "ကုတင်", emoji: "🛏️" },
      ],
    },
    {
      slug: "transport",
      title: "သယ်ယူပို့ဆောင်ရေး",
      subtitle: "การเดินทาง",
      emoji: "🚗",
      items: [
        { target: "รถยนต์", roman: "ရုတ် ယွန် (rótyon)", my: "ကား", emoji: "🚗" },
        { target: "รถเมล์", roman: "ရုတ် မေး (rótmee)", my: "ဘတ်စ်ကား", emoji: "🚌" },
        { target: "รถไฟ", roman: "ရုတ် ဖိုင် (rótfai)", my: "ရထား", emoji: "🚆" },
        { target: "จักรยาน", roman: "ဂျက် ကရ ယာန် (jàkkrayaan)", my: "စက်ဘီး", emoji: "🚲" },
        { target: "มอเตอร์ไซค์", roman: "မော်တာ ဆိုင် (mawtəəsai)", my: "မော်တော်ဆိုင်ကယ်", emoji: "🏍️" },
        { target: "เครื่องบิน", roman: "ခရွမ်း ဗင် (khrʉ̂ang bin)", my: "လေယာဉ်", emoji: "✈️" },
        { target: "เรือ", roman: "ရွ (rʉa)", my: "လှေ / သင်္ဘော", emoji: "⛵" },
        { target: "แท็กซี่", roman: "ထဲက် ဆီး (tháeksîi)", my: "တက္ကစီ", emoji: "🚕" },
        { target: "รถบรรทุก", roman: "ရုတ် ဗန် ထုက် (rót banthúk)", my: "ကုန်တင်ကား", emoji: "🚚" },
        { target: "ถนน", roman: "ထ နွန် (thanǒn)", my: "လမ်း", emoji: "🛣️" },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Chinese (Mandarin)
// ---------------------------------------------------------------------------
const CHINESE: LangCourse = {
  slug: "chinese",
  label: "Chinese",
  nativeLabel: "中文",
  flag: "🇨🇳",
  bcp47: "zh-CN",
  description: "တရုတ်စကား (မန်ဒရင်း) — pinyin ဖြင့် အခြေခံ။",
  units: [
    {
      slug: "greetings",
      title: "နှုတ်ဆက်ခြင်း",
      subtitle: "问候",
      emoji: "🙏",
      items: [
        { target: "你好", roman: "နီ ဟောင် (nǐ hǎo)", my: "မင်္ဂလာပါ", emoji: "👋" },
        { target: "谢谢", roman: "ရှဲ့ ရှဲ့ (xièxie)", my: "ကျေးဇူးတင်ပါတယ်", emoji: "🙏" },
        { target: "你好吗", roman: "နီ ဟောင် မာ (nǐ hǎo ma)", my: "နေကောင်းလား", emoji: "🙂" },
        { target: "我很好", roman: "ဝေါ် ဟင်း ဟောင် (wǒ hěn hǎo)", my: "ကျွန်တော် နေကောင်းပါတယ်", emoji: "👍" },
        { target: "对不起", roman: "တွေ့ ပူ ချီ (duìbuqǐ)", my: "တောင်းပန်ပါတယ်", emoji: "😔" },
        { target: "没关系", roman: "မေ့ ကွမ်း ရှီ (méi guānxi)", my: "ကိစ္စမရှိပါ", emoji: "🙆" },
        { target: "再见", roman: "ဇိုင် ကျဲန် (zàijiàn)", my: "သွားတော့မယ်", emoji: "👋" },
        { target: "欢迎", roman: "ဟွမ်း ယင်း (huānyíng)", my: "ကြိုဆိုပါတယ်", emoji: "🎉" },
      ],
    },
    {
      slug: "numbers",
      title: "ဂဏန်းများ",
      subtitle: "数字",
      emoji: "🔢",
      items: [
        { target: "一", roman: "ရီ (yī)", my: "တစ် (၁)", emoji: "1️⃣" },
        { target: "二", roman: "အာ (èr)", my: "နှစ် (၂)", emoji: "2️⃣" },
        { target: "三", roman: "ဆန်း (sān)", my: "သုံး (၃)", emoji: "3️⃣" },
        { target: "四", roman: "စ (sì)", my: "လေး (၄)", emoji: "4️⃣" },
        { target: "五", roman: "ဝူး (wǔ)", my: "ငါး (၅)", emoji: "5️⃣" },
        { target: "六", roman: "လျို့ (liù)", my: "ခြောက် (၆)", emoji: "6️⃣" },
        { target: "七", roman: "ချီ (qī)", my: "ခုနစ် (၇)", emoji: "7️⃣" },
        { target: "十", roman: "ရှစ် (shí)", my: "ဆယ် (၁၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "food",
      title: "အစားအသောက်",
      subtitle: "食物",
      emoji: "🍜",
      items: [
        { target: "水", roman: "ရွှေ (shuǐ)", my: "ရေ", emoji: "💧" },
        { target: "米饭", roman: "မီ ဖန် (mǐfàn)", my: "ထမင်း", emoji: "🍚" },
        { target: "茶", roman: "ချာ (chá)", my: "လက်ဖက်ရည်", emoji: "🍵" },
        { target: "好吃", roman: "ဟောင် ချ (hǎochī)", my: "စားလို့ကောင်းတယ်", emoji: "😋" },
        { target: "我饿了", roman: "ဝေါ် အာ့ လ (wǒ è le)", my: "ကျွန်တော် ဗိုက်ဆာတယ်", emoji: "🍽️" },
        { target: "多少钱", roman: "တွော် ရှောင် ချဲန် (duōshao qián)", my: "ဘယ်လောက်လဲ", emoji: "💰" },
        { target: "买单", roman: "မိုင် တန်း (mǎidān)", my: "ငွေရှင်းမယ်", emoji: "🧾" },
        { target: "好喝", roman: "ဟောင် ဟ (hǎohē)", my: "သောက်လို့ကောင်းတယ်", emoji: "🥤" },
      ],
    },
    {
      slug: "travel",
      title: "ခရီးသွား",
      subtitle: "出行",
      emoji: "🧭",
      items: [
        { target: "厕所在哪里", roman: "ဆဲ ဆော် ဇိုင် နာ လီ (cèsuǒ zài nǎlǐ)", my: "အိမ်သာ ဘယ်မှာလဲ", emoji: "🚻" },
        { target: "帮帮我", roman: "ပန်း ပန်း ဝေါ် (bāng bāng wǒ)", my: "ကူညီပါ", emoji: "🆘" },
        { target: "左转", roman: "ဇွော် ကျွမ်း (zuǒ zhuǎn)", my: "ဘယ်ဘက်ကွေ့", emoji: "⬅️" },
        { target: "右转", roman: "ယို့ ကျွမ်း (yòu zhuǎn)", my: "ညာဘက်ကွေ့", emoji: "➡️" },
        { target: "一直走", roman: "ရီ ကျ ဇို့ (yìzhí zǒu)", my: "တည့်တည့်သွား", emoji: "⬆️" },
        { target: "停这里", roman: "သင်း ကျဲ့ လီ (tíng zhèlǐ)", my: "ဒီမှာ ရပ်ပါ", emoji: "🛑" },
        { target: "机场", roman: "ကျီ ချမ်း (jīchǎng)", my: "လေဆိပ်", emoji: "✈️" },
        { target: "医院", roman: "ရီ ယွမ်း (yīyuàn)", my: "ဆေးရုံ", emoji: "🏥" },
      ],
    },
    {
      slug: "colors",
      title: "အရောင်များ",
      subtitle: "颜色",
      emoji: "🎨",
      items: [
        { target: "红色", roman: "ဟုံ့ စ (hóngsè)", my: "အနီ", emoji: "🔴" },
        { target: "蓝色", roman: "လန် စ (lánsè)", my: "အပြာ", emoji: "🔵" },
        { target: "绿色", roman: "လွစ် စ (lǜsè)", my: "အစိမ်း", emoji: "🟢" },
        { target: "黄色", roman: "ဟွမ်း စ (huángsè)", my: "အဝါ", emoji: "🟡" },
        { target: "黑色", roman: "ဟေး စ (hēisè)", my: "အနက်", emoji: "⚫" },
        { target: "白色", roman: "ပိုင် စ (báisè)", my: "အဖြူ", emoji: "⚪" },
        { target: "橙色", roman: "ချုန်း စ (chéngsè)", my: "လိမ္မော်ရောင်", emoji: "🟠" },
        { target: "粉色", roman: "ဖင့် စ (fěnsè)", my: "ပန်းရောင်", emoji: "🩷" },
      ],
    },
    {
      slug: "family",
      title: "မိသားစု",
      subtitle: "家人",
      emoji: "👨‍👩‍👧",
      items: [
        { target: "妈妈", roman: "မားမ (māma)", my: "အမေ", emoji: "👩" },
        { target: "爸爸", roman: "ပါ့ပ (bàba)", my: "အဖေ", emoji: "👨" },
        { target: "姐姐", roman: "ကျဲ့ကျဲ့ (jiějie)", my: "အစ်မ", emoji: "👧" },
        { target: "妹妹", roman: "မေ့မေ့ (mèimei)", my: "ညီမ", emoji: "👧" },
        { target: "哥哥", roman: "ကဲကဲ (gēge)", my: "အစ်ကို", emoji: "👦" },
        { target: "儿子", roman: "အာ့ဇ (érzi)", my: "သား", emoji: "👦" },
        { target: "女儿", roman: "နွယ် အာ (nǚ'ér)", my: "သမီး", emoji: "👧" },
        { target: "奶奶", roman: "နိုင်နိုင် (nǎinai)", my: "အဖွား", emoji: "👵" },
      ],
    },
    {
      slug: "days",
      title: "ရက်သတ္တပတ်",
      subtitle: "星期",
      emoji: "📅",
      items: [
        { target: "星期一", roman: "ရှင်းချီရီ (xīngqīyī)", my: "တနင်္လာ", emoji: "1️⃣" },
        { target: "星期二", roman: "ရှင်းချီအာ (xīngqī'èr)", my: "အင်္ဂါ", emoji: "2️⃣" },
        { target: "星期三", roman: "ရှင်းချီဆန်း (xīngqīsān)", my: "ဗုဒ္ဓဟူး", emoji: "3️⃣" },
        { target: "星期四", roman: "ရှင်းချီစ (xīngqīsì)", my: "ကြာသပတေး", emoji: "4️⃣" },
        { target: "星期五", roman: "ရှင်းချီဝူး (xīngqīwǔ)", my: "သောကြာ", emoji: "5️⃣" },
        { target: "星期六", roman: "ရှင်းချီလျို့ (xīngqīliù)", my: "စနေ", emoji: "6️⃣" },
        { target: "星期日", roman: "ရှင်းချီရစ် (xīngqīrì)", my: "တနင်္ဂနွေ", emoji: "7️⃣" },
      ],
    },
    {
      slug: "numbers-teens",
      title: "ဂဏန်း ၁၁–၂၀",
      subtitle: "数字 11–20",
      emoji: "🔢",
      items: [
        { target: "十一", roman: "ရှစ် ရီ (shíyī)", my: "ဆယ့်တစ် (၁၁)", emoji: "1️⃣" },
        { target: "十二", roman: "ရှစ် အာ (shí'èr)", my: "ဆယ့်နှစ် (၁၂)", emoji: "2️⃣" },
        { target: "十三", roman: "ရှစ် ဆန်း (shísān)", my: "ဆယ့်သုံး (၁၃)", emoji: "3️⃣" },
        { target: "十四", roman: "ရှစ် စ (shísì)", my: "ဆယ့်လေး (၁၄)", emoji: "4️⃣" },
        { target: "十五", roman: "ရှစ် ဝူး (shíwǔ)", my: "ဆယ့်ငါး (၁၅)", emoji: "5️⃣" },
        { target: "十六", roman: "ရှစ် လျို့ (shíliù)", my: "ဆယ့်ခြောက် (၁၆)", emoji: "6️⃣" },
        { target: "十七", roman: "ရှစ် ချီ (shíqī)", my: "ဆယ့်ခုနစ် (၁၇)", emoji: "7️⃣" },
        { target: "十八", roman: "ရှစ် ပာ (shíbā)", my: "ဆယ့်ရှစ် (၁၈)", emoji: "8️⃣" },
        { target: "十九", roman: "ရှစ် ကျို့ (shíjiǔ)", my: "ဆယ့်ကိုး (၁၉)", emoji: "9️⃣" },
        { target: "二十", roman: "အာ ရှစ် (èrshí)", my: "နှစ်ဆယ် (၂၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "months",
      title: "လများ (၁၂ လ)",
      subtitle: "月份",
      emoji: "📅",
      items: [
        { target: "一月", roman: "ရိ ယွဲ့ (yīyuè)", my: "ဇန်နဝါရီ", emoji: "❄️" },
        { target: "二月", roman: "အာ ယွဲ့ (èryuè)", my: "ဖေဖော်ဝါရီ", emoji: "💝" },
        { target: "三月", roman: "ဆန်း ယွဲ့ (sānyuè)", my: "မတ်", emoji: "🌱" },
        { target: "四月", roman: "စ ယွဲ့ (sìyuè)", my: "ဧပြီ", emoji: "🌧️" },
        { target: "五月", roman: "ဝူ ယွဲ့ (wǔyuè)", my: "မေ", emoji: "🌸" },
        { target: "六月", roman: "လျို့ ယွဲ့ (liùyuè)", my: "ဇွန်", emoji: "☀️" },
        { target: "七月", roman: "ချီ ယွဲ့ (qīyuè)", my: "ဇူလိုင်", emoji: "🎆" },
        { target: "八月", roman: "ပါ ယွဲ့ (bāyuè)", my: "သြဂုတ်", emoji: "🏖️" },
        { target: "九月", roman: "ကျို့ ယွဲ့ (jiǔyuè)", my: "စက်တင်ဘာ", emoji: "🍂" },
        { target: "十月", roman: "ရှစ် ယွဲ့ (shíyuè)", my: "အောက်တိုဘာ", emoji: "🎃" },
        { target: "十一月", roman: "ရှစ် ရိ ယွဲ့ (shíyīyuè)", my: "နိုဝင်ဘာ", emoji: "🍁" },
        { target: "十二月", roman: "ရှစ် အာ ယွဲ့ (shí'èryuè)", my: "ဒီဇင်ဘာ", emoji: "🎄" },
      ],
    },
    {
      slug: "body-parts",
      title: "ခန္ဓာကိုယ် အစိတ်အပိုင်း",
      subtitle: "身体部位",
      emoji: "🧍",
      items: [
        { target: "头", roman: "ထို့ (tóu)", my: "ခေါင်း", emoji: "👤" },
        { target: "头发", roman: "ထို့ ဖ (tóufa)", my: "ဆံပင်", emoji: "💇" },
        { target: "眼睛", roman: "ယဲန် ကျင်း (yǎnjing)", my: "မျက်လုံး", emoji: "👁️" },
        { target: "耳朵", roman: "အာ တွော (ěrduo)", my: "နား", emoji: "👂" },
        { target: "鼻子", roman: "ပီ ဇ (bízi)", my: "နှာခေါင်း", emoji: "👃" },
        { target: "嘴", roman: "ကျွေ (zuǐ)", my: "ပါးစပ်", emoji: "👄" },
        { target: "牙齿", roman: "ယာ ချ (yáchǐ)", my: "သွား", emoji: "🦷" },
        { target: "手", roman: "ရှို့ (shǒu)", my: "လက်", emoji: "✋" },
        { target: "手臂", roman: "ရှို့ ပိ (shǒubì)", my: "လက်မောင်း", emoji: "💪" },
        { target: "腿", roman: "ထွေ (tuǐ)", my: "ခြေထောက်", emoji: "🦵" },
        { target: "肚子", roman: "တူ ဇ (dùzi)", my: "ဗိုက်", emoji: "🫃" },
        { target: "心", roman: "ရှင်း (xīn)", my: "နှလုံး", emoji: "❤️" },
      ],
    },
    {
      slug: "weather",
      title: "ရာသီဥတု",
      subtitle: "天气",
      emoji: "🌦️",
      items: [
        { target: "晴天", roman: "ချင်း ထျန် (qíngtiān)", my: "နေသာ", emoji: "☀️" },
        { target: "雨", roman: "ယု (yǔ)", my: "မိုး", emoji: "🌧️" },
        { target: "云", roman: "ယွန် (yún)", my: "တိမ်", emoji: "☁️" },
        { target: "风", roman: "ဖုန်း (fēng)", my: "လေ", emoji: "🌬️" },
        { target: "热", roman: "ရဲ့ (rè)", my: "ပူသည်", emoji: "🔥" },
        { target: "冷", roman: "လုန် (lěng)", my: "အေးသည်", emoji: "🥶" },
        { target: "暴风雨", roman: "ပေါက် ဖုန်း ယု (bàofēngyǔ)", my: "မုန်တိုင်း", emoji: "⛈️" },
        { target: "雪", roman: "ရွှယ် (xuě)", my: "နှင်း", emoji: "❄️" },
        { target: "彩虹", roman: "ဆိုင်း ဟုန် (cǎihóng)", my: "သက်တံ့", emoji: "🌈" },
        { target: "雾", roman: "ဝူ (wù)", my: "မြူ", emoji: "🌫️" },
      ],
    },
    {
      slug: "house-rooms",
      title: "အိမ်နှင့် အခန်းများ",
      subtitle: "房子",
      emoji: "🏠",
      items: [
        { target: "房子", roman: "ဖန် ဇ (fángzi)", my: "အိမ်", emoji: "🏠" },
        { target: "门", roman: "မွန် (mén)", my: "တံခါး", emoji: "🚪" },
        { target: "窗户", roman: "ချွမ်း ဟု (chuānghu)", my: "ပြတင်းပေါက်", emoji: "🪟" },
        { target: "厨房", roman: "ချူ ဖန် (chúfáng)", my: "မီးဖိုချောင်", emoji: "🍳" },
        { target: "卧室", roman: "ဝေါ့ ရှစ် (wòshì)", my: "အိပ်ခန်း", emoji: "🛌" },
        { target: "浴室", roman: "ယု ရှစ် (yùshì)", my: "ရေချိုးခန်း", emoji: "🛁" },
        { target: "客厅", roman: "ခဲ ထင်း (kètīng)", my: "ဧည့်ခန်း", emoji: "🛋️" },
        { target: "桌子", roman: "ကျွိုး ဇ (zhuōzi)", my: "စားပွဲ", emoji: "🍽️" },
        { target: "椅子", roman: "ရိ ဇ (yǐzi)", my: "ကုလားထိုင်", emoji: "🪑" },
        { target: "床", roman: "ချွမ်း (chuáng)", my: "ကုတင်", emoji: "🛏️" },
      ],
    },
    {
      slug: "transport",
      title: "သယ်ယူပို့ဆောင်ရေး",
      subtitle: "交通",
      emoji: "🚗",
      items: [
        { target: "汽车", roman: "ချီ ချဲ (qìchē)", my: "ကား", emoji: "🚗" },
        { target: "公交车", roman: "ကုန်း ကျောင် ချဲ (gōngjiāochē)", my: "ဘတ်စ်ကား", emoji: "🚌" },
        { target: "火车", roman: "ဟွော ချဲ (huǒchē)", my: "ရထား", emoji: "🚆" },
        { target: "自行车", roman: "ဇ ရှင်း ချဲ (zìxíngchē)", my: "စက်ဘီး", emoji: "🚲" },
        { target: "摩托车", roman: "မော ထွိုး ချဲ (mótuōchē)", my: "မော်တော်ဆိုင်ကယ်", emoji: "🏍️" },
        { target: "飞机", roman: "ဖေ ကျီ (fēijī)", my: "လေယာဉ်", emoji: "✈️" },
        { target: "船", roman: "ချွမ်း (chuán)", my: "သင်္ဘော", emoji: "⛵" },
        { target: "出租车", roman: "ချူ ဇူ ချဲ (chūzūchē)", my: "တက္ကစီ", emoji: "🚕" },
        { target: "卡车", roman: "ခါ ချဲ (kǎchē)", my: "ကုန်တင်ကား", emoji: "🚚" },
        { target: "路", roman: "လူ (lù)", my: "လမ်း", emoji: "🛣️" },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Japanese
// ---------------------------------------------------------------------------
const JAPANESE: LangCourse = {
  slug: "japanese",
  label: "Japanese",
  nativeLabel: "日本語",
  flag: "🇯🇵",
  bcp47: "ja-JP",
  description: "ဂျပန်စကား — romaji ဖြင့် အခြေခံ။",
  units: [
    {
      slug: "greetings",
      title: "နှုတ်ဆက်ခြင်း",
      subtitle: "あいさつ",
      emoji: "🙇",
      items: [
        { target: "こんにちは", roman: "ကွန်နိချိဝ (konnichiwa)", my: "မင်္ဂလာပါ (နေ့ခင်း)", emoji: "👋" },
        { target: "おはよう", roman: "အိုဟာယော် (ohayō)", my: "မင်္ဂလာနံနက်ခင်းပါ", emoji: "🌅" },
        { target: "こんばんは", roman: "ကွန်ဘန်ဝ (konbanwa)", my: "မင်္ဂလာ ညနေခင်းပါ", emoji: "🌆" },
        { target: "ありがとう", roman: "အာရိဂတော် (arigatō)", my: "ကျေးဇူးတင်ပါတယ်", emoji: "🙏" },
        { target: "すみません", roman: "ဆုမိမာဆဲန် (sumimasen)", my: "တောင်းပန်ပါတယ် / ခွင့်ပြုပါ", emoji: "😔" },
        { target: "はい", roman: "ဟိုင် (hai)", my: "ဟုတ်ကဲ့", emoji: "✅" },
        { target: "いいえ", roman: "အီးအဲ (iie)", my: "မဟုတ်ဘူး", emoji: "❌" },
        { target: "さようなら", roman: "ဆာယောနာရ (sayōnara)", my: "သွားတော့မယ်", emoji: "👋" },
      ],
    },
    {
      slug: "numbers",
      title: "ဂဏန်းများ",
      subtitle: "数字",
      emoji: "🔢",
      items: [
        { target: "一", roman: "အိချိ (ichi)", my: "တစ် (၁)", emoji: "1️⃣" },
        { target: "二", roman: "နိ (ni)", my: "နှစ် (၂)", emoji: "2️⃣" },
        { target: "三", roman: "ဆန် (san)", my: "သုံး (၃)", emoji: "3️⃣" },
        { target: "四", roman: "ရှိ / ယွန် (shi/yon)", my: "လေး (၄)", emoji: "4️⃣" },
        { target: "五", roman: "ဂေါ် (go)", my: "ငါး (၅)", emoji: "5️⃣" },
        { target: "六", roman: "ရော်ကု (roku)", my: "ခြောက် (၆)", emoji: "6️⃣" },
        { target: "七", roman: "နာနာ / ရှိချိ (nana)", my: "ခုနစ် (၇)", emoji: "7️⃣" },
        { target: "十", roman: "ဂျူး (jū)", my: "ဆယ် (၁၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "food",
      title: "အစားအသောက်",
      subtitle: "食べ物",
      emoji: "🍱",
      items: [
        { target: "水", roman: "မိဇု (mizu)", my: "ရေ", emoji: "💧" },
        { target: "ご飯", roman: "ဂိုဟန် (gohan)", my: "ထမင်း", emoji: "🍚" },
        { target: "お茶", roman: "အိုချ (ocha)", my: "လက်ဖက်ရည်", emoji: "🍵" },
        { target: "おいしい", roman: "အွိုင်ရှီး (oishii)", my: "စားလို့ကောင်းတယ်", emoji: "😋" },
        { target: "いただきます", roman: "အိတဒကိမာစု (itadakimasu)", my: "စားတော့မယ် (မစားခင်)", emoji: "🍽️" },
        { target: "いくらですか", roman: "အိကုရ ဒက်စ်က (ikura desu ka)", my: "ဘယ်လောက်လဲ", emoji: "💰" },
        { target: "お会計", roman: "အိုကိုင်းကေး (okaikei)", my: "ငွေရှင်းမယ်", emoji: "🧾" },
        { target: "お腹すいた", roman: "အိုနာက ဆွိုက်တ (onaka suita)", my: "ဗိုက်ဆာတယ်", emoji: "😩" },
      ],
    },
    {
      slug: "travel",
      title: "ခရီးသွား",
      subtitle: "移動",
      emoji: "🧭",
      items: [
        { target: "トイレはどこですか", roman: "တွိုင်းရေ ဝ ဒေါ်ကို ဒက်စ်က (toire wa doko desu ka)", my: "အိမ်သာ ဘယ်မှာလဲ", emoji: "🚻" },
        { target: "助けて", roman: "တစုကေတဲ (tasukete)", my: "ကူညီပါ", emoji: "🆘" },
        { target: "左", roman: "ဟိဒရိ (hidari)", my: "ဘယ်ဘက်", emoji: "⬅️" },
        { target: "右", roman: "မိဂိ (migi)", my: "ညာဘက်", emoji: "➡️" },
        { target: "まっすぐ", roman: "မတ်ဆုဂု (massugu)", my: "တည့်တည့်", emoji: "⬆️" },
        { target: "ここで止まって", roman: "ကိုကို ဒဲ တိုမတ်တဲ (koko de tomatte)", my: "ဒီမှာ ရပ်ပါ", emoji: "🛑" },
        { target: "空港", roman: "ကူးကော် (kūkō)", my: "လေဆိပ်", emoji: "✈️" },
        { target: "病院", roman: "ဗျိုးအင် (byōin)", my: "ဆေးရုံ", emoji: "🏥" },
      ],
    },
    {
      slug: "colors",
      title: "အရောင်များ",
      subtitle: "色",
      emoji: "🎨",
      items: [
        { target: "赤", roman: "အက (aka)", my: "အနီ", emoji: "🔴" },
        { target: "青", roman: "အအို (ao)", my: "အပြာ", emoji: "🔵" },
        { target: "緑", roman: "မိဒေါ်ရိ (midori)", my: "အစိမ်း", emoji: "🟢" },
        { target: "黄色", roman: "ကီးရော် (kiiro)", my: "အဝါ", emoji: "🟡" },
        { target: "黒", roman: "ကုရော် (kuro)", my: "အနက်", emoji: "⚫" },
        { target: "白", roman: "ရှိရော် (shiro)", my: "အဖြူ", emoji: "⚪" },
        { target: "オレンジ", roman: "အိုရဲန်ဂျိ (orenji)", my: "လိမ္မော်ရောင်", emoji: "🟠" },
        { target: "ピンク", roman: "ပင်းကု (pinku)", my: "ပန်းရောင်", emoji: "🩷" },
      ],
    },
    {
      slug: "family",
      title: "မိသားစု",
      subtitle: "家族",
      emoji: "👨‍👩‍👧",
      items: [
        { target: "母", roman: "ဟဟ (haha)", my: "အမေ", emoji: "👩" },
        { target: "父", roman: "ချိချိ (chichi)", my: "အဖေ", emoji: "👨" },
        { target: "姉", roman: "အနဲ (ane)", my: "အစ်မ", emoji: "👧" },
        { target: "妹", roman: "အိမိုတော် (imōto)", my: "ညီမ", emoji: "👧" },
        { target: "兄", roman: "အနိ (ani)", my: "အစ်ကို", emoji: "👦" },
        { target: "息子", roman: "မုစုကော် (musuko)", my: "သား", emoji: "👦" },
        { target: "娘", roman: "မုစုမဲ (musume)", my: "သမီး", emoji: "👧" },
        { target: "祖母", roman: "ဆိုဘော် (sobo)", my: "အဖွား", emoji: "👵" },
      ],
    },
    {
      slug: "days",
      title: "ရက်သတ္တပတ်",
      subtitle: "曜日",
      emoji: "📅",
      items: [
        { target: "月曜日", roman: "ဂက်ဆုယောဘိ (getsuyōbi)", my: "တနင်္လာ", emoji: "1️⃣" },
        { target: "火曜日", roman: "ကယောဘိ (kayōbi)", my: "အင်္ဂါ", emoji: "2️⃣" },
        { target: "水曜日", roman: "ဆွိုင်ယောဘိ (suiyōbi)", my: "ဗုဒ္ဓဟူး", emoji: "3️⃣" },
        { target: "木曜日", roman: "မိုကုယောဘိ (mokuyōbi)", my: "ကြာသပတေး", emoji: "4️⃣" },
        { target: "金曜日", roman: "ကင်းယောဘိ (kinyōbi)", my: "သောကြာ", emoji: "5️⃣" },
        { target: "土曜日", roman: "ဒိုယောဘိ (doyōbi)", my: "စနေ", emoji: "6️⃣" },
        { target: "日曜日", roman: "နိချိယောဘိ (nichiyōbi)", my: "တနင်္ဂနွေ", emoji: "7️⃣" },
      ],
    },
    {
      slug: "numbers-teens",
      title: "ဂဏန်း ၁၁–၂၀",
      subtitle: "数字 11–20",
      emoji: "🔢",
      items: [
        { target: "十一", roman: "ဂျူးအိချိ (jūichi)", my: "ဆယ့်တစ် (၁၁)", emoji: "1️⃣" },
        { target: "十二", roman: "ဂျူးနိ (jūni)", my: "ဆယ့်နှစ် (၁၂)", emoji: "2️⃣" },
        { target: "十三", roman: "ဂျူးဆန် (jūsan)", my: "ဆယ့်သုံး (၁၃)", emoji: "3️⃣" },
        { target: "十四", roman: "ဂျူးယွန် (jūyon)", my: "ဆယ့်လေး (၁၄)", emoji: "4️⃣" },
        { target: "十五", roman: "ဂျူးဂေါ် (jūgo)", my: "ဆယ့်ငါး (၁၅)", emoji: "5️⃣" },
        { target: "十六", roman: "ဂျူးရော်ကု (jūroku)", my: "ဆယ့်ခြောက် (၁၆)", emoji: "6️⃣" },
        { target: "十七", roman: "ဂျူးနာနာ (jūnana)", my: "ဆယ့်ခုနစ် (၁၇)", emoji: "7️⃣" },
        { target: "十八", roman: "ဂျူးဟာချိ (jūhachi)", my: "ဆယ့်ရှစ် (၁၈)", emoji: "8️⃣" },
        { target: "十九", roman: "ဂျူးကျူး (jūkyū)", my: "ဆယ့်ကိုး (၁၉)", emoji: "9️⃣" },
        { target: "二十", roman: "နီဂျူး (nijū)", my: "နှစ်ဆယ် (၂၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "months",
      title: "လများ (၁၂ လ)",
      subtitle: "月 (つき)",
      emoji: "📅",
      items: [
        { target: "一月", roman: "အိချိ ဂါဆု (ichigatsu)", my: "ဇန်နဝါရီ", emoji: "❄️" },
        { target: "二月", roman: "နိ ဂါဆု (nigatsu)", my: "ဖေဖော်ဝါရီ", emoji: "💝" },
        { target: "三月", roman: "ဆန် ဂါဆု (sangatsu)", my: "မတ်", emoji: "🌱" },
        { target: "四月", roman: "ရှိ ဂါဆု (shigatsu)", my: "ဧပြီ", emoji: "🌧️" },
        { target: "五月", roman: "ဂို ဂါဆု (gogatsu)", my: "မေ", emoji: "🌸" },
        { target: "六月", roman: "ရော့ကု ဂါဆု (rokugatsu)", my: "ဇွန်", emoji: "☀️" },
        { target: "七月", roman: "ရှိချိ ဂါဆု (shichigatsu)", my: "ဇူလိုင်", emoji: "🎆" },
        { target: "八月", roman: "ဟာချိ ဂါဆု (hachigatsu)", my: "သြဂုတ်", emoji: "🏖️" },
        { target: "九月", roman: "ကု ဂါဆု (kugatsu)", my: "စက်တင်ဘာ", emoji: "🍂" },
        { target: "十月", roman: "ဂျူး ဂါဆု (jūgatsu)", my: "အောက်တိုဘာ", emoji: "🎃" },
        { target: "十一月", roman: "ဂျူးအိချိ ဂါဆု (jūichigatsu)", my: "နိုဝင်ဘာ", emoji: "🍁" },
        { target: "十二月", roman: "ဂျူးနိ ဂါဆု (jūnigatsu)", my: "ဒီဇင်ဘာ", emoji: "🎄" },
      ],
    },
    {
      slug: "body-parts",
      title: "ခန္ဓာကိုယ် အစိတ်အပိုင်း",
      subtitle: "体 (からだ)",
      emoji: "🧍",
      items: [
        { target: "頭", roman: "အတမ (atama)", my: "ခေါင်း", emoji: "👤" },
        { target: "髪", roman: "ကမိ (kami)", my: "ဆံပင်", emoji: "💇" },
        { target: "目", roman: "မဲ (me)", my: "မျက်လုံး", emoji: "👁️" },
        { target: "耳", roman: "မိမိ (mimi)", my: "နား", emoji: "👂" },
        { target: "鼻", roman: "ဟန (hana)", my: "နှာခေါင်း", emoji: "👃" },
        { target: "口", roman: "ကုချိ (kuchi)", my: "ပါးစပ်", emoji: "👄" },
        { target: "歯", roman: "ဟ (ha)", my: "သွား", emoji: "🦷" },
        { target: "手", roman: "တဲ (te)", my: "လက်", emoji: "✋" },
        { target: "腕", roman: "အုဒဲ (ude)", my: "လက်မောင်း", emoji: "💪" },
        { target: "足", roman: "အရှိ (ashi)", my: "ခြေထောက်", emoji: "🦵" },
        { target: "お腹", roman: "အိုနက (onaka)", my: "ဗိုက်", emoji: "🫃" },
        { target: "心臓", roman: "ရှင်ဇို (shinzō)", my: "နှလုံး", emoji: "❤️" },
      ],
    },
    {
      slug: "weather",
      title: "ရာသီဥတု",
      subtitle: "天気 (てんき)",
      emoji: "🌦️",
      items: [
        { target: "晴れ", roman: "ဟရဲ (hare)", my: "နေသာ", emoji: "☀️" },
        { target: "雨", roman: "အမဲ (ame)", my: "မိုး", emoji: "🌧️" },
        { target: "雲", roman: "ကုမော (kumo)", my: "တိမ်", emoji: "☁️" },
        { target: "風", roman: "ကဇဲ (kaze)", my: "လေ", emoji: "🌬️" },
        { target: "暑い", roman: "အဆွိ (atsui)", my: "ပူသည်", emoji: "🔥" },
        { target: "寒い", roman: "ဆမွိ (samui)", my: "အေးသည်", emoji: "🥶" },
        { target: "嵐", roman: "အရရှိ (arashi)", my: "မုန်တိုင်း", emoji: "⛈️" },
        { target: "雪", roman: "ယုကိ (yuki)", my: "နှင်း", emoji: "❄️" },
        { target: "虹", roman: "နိဂျိ (niji)", my: "သက်တံ့", emoji: "🌈" },
        { target: "霧", roman: "ကိရိ (kiri)", my: "မြူ", emoji: "🌫️" },
      ],
    },
    {
      slug: "house-rooms",
      title: "အိမ်နှင့် အခန်းများ",
      subtitle: "家 (いえ)",
      emoji: "🏠",
      items: [
        { target: "家", roman: "အိအဲ (ie)", my: "အိမ်", emoji: "🏠" },
        { target: "ドア", roman: "ဒိုအ (doa)", my: "တံခါး", emoji: "🚪" },
        { target: "窓", roman: "မဒေါ (mado)", my: "ပြတင်းပေါက်", emoji: "🪟" },
        { target: "台所", roman: "ဒိုင်းဒေါ့ကောရော (daidokoro)", my: "မီးဖိုချောင်", emoji: "🍳" },
        { target: "寝室", roman: "ရှင်းရှိဆု (shinshitsu)", my: "အိပ်ခန်း", emoji: "🛌" },
        { target: "風呂", roman: "ဖုရော (furo)", my: "ရေချိုးခန်း", emoji: "🛁" },
        { target: "居間", roman: "အိမ (ima)", my: "ဧည့်ခန်း", emoji: "🛋️" },
        { target: "テーブル", roman: "တေးဘုရု (tēburu)", my: "စားပွဲ", emoji: "🍽️" },
        { target: "椅子", roman: "အိဆု (isu)", my: "ကုလားထိုင်", emoji: "🪑" },
        { target: "ベッド", roman: "ဘဲဒ္ဒို (beddo)", my: "ကုတင်", emoji: "🛏️" },
      ],
    },
    {
      slug: "transport",
      title: "သယ်ယူပို့ဆောင်ရေး",
      subtitle: "交通 (こうつう)",
      emoji: "🚗",
      items: [
        { target: "車", roman: "ကုရုမ (kuruma)", my: "ကား", emoji: "🚗" },
        { target: "バス", roman: "ဘဆု (basu)", my: "ဘတ်စ်ကား", emoji: "🚌" },
        { target: "電車", roman: "ဒဲန်ရှ (densha)", my: "ရထား", emoji: "🚆" },
        { target: "自転車", roman: "ဂျိတဲန်ရှ (jitensha)", my: "စက်ဘီး", emoji: "🚲" },
        { target: "バイク", roman: "ဘိုက်ကု (baiku)", my: "မော်တော်ဆိုင်ကယ်", emoji: "🏍️" },
        { target: "飛行機", roman: "ဟိကိုကိ (hikōki)", my: "လေယာဉ်", emoji: "✈️" },
        { target: "船", roman: "ဖုနဲ (fune)", my: "သင်္ဘော", emoji: "⛵" },
        { target: "タクシー", roman: "တကုရှီး (takushī)", my: "တက္ကစီ", emoji: "🚕" },
        { target: "トラック", roman: "တောရက်ကု (torakku)", my: "ကုန်တင်ကား", emoji: "🚚" },
        { target: "道", roman: "မိချိ (michi)", my: "လမ်း", emoji: "🛣️" },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Korean
// ---------------------------------------------------------------------------
const KOREAN: LangCourse = {
  slug: "korean",
  label: "Korean",
  nativeLabel: "한국어",
  flag: "🇰🇷",
  bcp47: "ko-KR",
  description: "ကိုရီးယားစကား — Hangul ဖြင့် အခြေခံ။",
  units: [
    {
      slug: "greetings",
      title: "နှုတ်ဆက်ခြင်း",
      subtitle: "인사",
      emoji: "🙇",
      items: [
        { target: "안녕하세요", roman: "အန်ညောင်ဟာဆေးယို (annyeonghaseyo)", my: "မင်္ဂလာပါ", emoji: "👋" },
        { target: "감사합니다", roman: "ကမ်ဆာဟမ်နီဒ (gamsahamnida)", my: "ကျေးဇူးတင်ပါတယ်", emoji: "🙏" },
        { target: "죄송합니다", roman: "ချွယ်ဆောင်ဟမ်နီဒ (joesonghamnida)", my: "တောင်းပန်ပါတယ်", emoji: "😔" },
        { target: "네", roman: "နဲ (ne)", my: "ဟုတ်ကဲ့", emoji: "✅" },
        { target: "아니요", roman: "အာနီယို (aniyo)", my: "မဟုတ်ဘူး", emoji: "❌" },
        { target: "잘 지내세요?", roman: "ချယ် ချီနဲဆေးယို (jal jinaeseyo)", my: "နေကောင်းလား", emoji: "🙂" },
        { target: "안녕히 가세요", roman: "အန်ညောင်ဟီ ကာဆေးယို (annyeonghi gaseyo)", my: "သွားတော့မယ်", emoji: "👋" },
        { target: "반갑습니다", roman: "ပန်ကပ်စမ်နီဒ (bangapseumnida)", my: "တွေ့ရတာ ဝမ်းသာပါတယ်", emoji: "😊" },
      ],
    },
    {
      slug: "numbers",
      title: "ဂဏန်းများ",
      subtitle: "숫자",
      emoji: "🔢",
      items: [
        { target: "일", roman: "အိလ် (il)", my: "တစ် (၁)", emoji: "1️⃣" },
        { target: "이", roman: "အီး (i)", my: "နှစ် (၂)", emoji: "2️⃣" },
        { target: "삼", roman: "ဆမ် (sam)", my: "သုံး (၃)", emoji: "3️⃣" },
        { target: "사", roman: "ဆာ (sa)", my: "လေး (၄)", emoji: "4️⃣" },
        { target: "오", roman: "အို (o)", my: "ငါး (၅)", emoji: "5️⃣" },
        { target: "육", roman: "ယွတ် (yuk)", my: "ခြောက် (၆)", emoji: "6️⃣" },
        { target: "칠", roman: "ချိလ် (chil)", my: "ခုနစ် (၇)", emoji: "7️⃣" },
        { target: "십", roman: "ရှစ်ပ် (sip)", my: "ဆယ် (၁၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "food",
      title: "အစားအသောက်",
      subtitle: "음식",
      emoji: "🍚",
      items: [
        { target: "물", roman: "မွုလ် (mul)", my: "ရေ", emoji: "💧" },
        { target: "밥", roman: "ပပ် (bap)", my: "ထမင်း", emoji: "🍚" },
        { target: "차", roman: "ချာ (cha)", my: "လက်ဖက်ရည်", emoji: "🍵" },
        { target: "맛있어요", roman: "မာရှိဆောယို (masisseoyo)", my: "စားလို့ကောင်းတယ်", emoji: "😋" },
        { target: "매워요", roman: "မဲဝေါယို (maewoyo)", my: "စပ်တယ်", emoji: "🌶️" },
        { target: "배고파요", roman: "ပဲကိုပါယို (baegopayo)", my: "ဗိုက်ဆာတယ်", emoji: "😩" },
        { target: "얼마예요", roman: "အောလ်မာယဲယို (eolmayeyo)", my: "ဘယ်လောက်လဲ", emoji: "💰" },
        { target: "계산해 주세요", roman: "ကယဆန်ဟဲ ဂျုဆေးယို (gyesanhae juseyo)", my: "ငွေရှင်းမယ်", emoji: "🧾" },
      ],
    },
    {
      slug: "travel",
      title: "ခရီးသွား",
      subtitle: "이동",
      emoji: "🧭",
      items: [
        { target: "화장실이 어디예요?", roman: "ဟွာဂျန်ရှီလိ အောဒီယဲယို (hwajangsiri eodiyeyo)", my: "အိမ်သာ ဘယ်မှာလဲ", emoji: "🚻" },
        { target: "도와주세요", roman: "တိုဝါဂျုဆေးယို (dowajuseyo)", my: "ကူညီပါ", emoji: "🆘" },
        { target: "왼쪽", roman: "ဝဲန်ချောက် (oenjjok)", my: "ဘယ်ဘက်", emoji: "⬅️" },
        { target: "오른쪽", roman: "အောရွန်ချောက် (oreunjjok)", my: "ညာဘက်", emoji: "➡️" },
        { target: "직진", roman: "ချစ်ဂျင် (jikjin)", my: "တည့်တည့်", emoji: "⬆️" },
        { target: "여기서 세워 주세요", roman: "ယောဂီဆော ဆယ်ဝေါ ဂျုဆေးယို (yeogiseo sewo juseyo)", my: "ဒီမှာ ရပ်ပါ", emoji: "🛑" },
        { target: "공항", roman: "ကွန်းဟန် (gonghang)", my: "လေဆိပ်", emoji: "✈️" },
        { target: "병원", roman: "ဗျောင်ဝွန် (byeongwon)", my: "ဆေးရုံ", emoji: "🏥" },
      ],
    },
    {
      slug: "colors",
      title: "အရောင်များ",
      subtitle: "색깔",
      emoji: "🎨",
      items: [
        { target: "빨간색", roman: "ပ္ပလ်ဂန်ဆဲ့ (ppalgansaek)", my: "အနီ", emoji: "🔴" },
        { target: "파란색", roman: "ဖါရန်ဆဲ့ (paransaek)", my: "အပြာ", emoji: "🔵" },
        { target: "초록색", roman: "ချိုရော့ဆဲ့ (choroksaek)", my: "အစိမ်း", emoji: "🟢" },
        { target: "노란색", roman: "နိုရန်ဆဲ့ (noransaek)", my: "အဝါ", emoji: "🟡" },
        { target: "검은색", roman: "ကောမွန်ဆဲ့ (geomeunsaek)", my: "အနက်", emoji: "⚫" },
        { target: "하얀색", roman: "ဟယန်ဆဲ့ (hayansaek)", my: "အဖြူ", emoji: "⚪" },
        { target: "주황색", roman: "ဂျုဟွမ်ဆဲ့ (juhwangsaek)", my: "လိမ္မော်ရောင်", emoji: "🟠" },
        { target: "분홍색", roman: "ပွန်ဟုံဆဲ့ (bunhongsaek)", my: "ပန်းရောင်", emoji: "🩷" },
      ],
    },
    {
      slug: "family",
      title: "မိသားစု",
      subtitle: "가족",
      emoji: "👨‍👩‍👧",
      items: [
        { target: "엄마", roman: "အောမ်မ (eomma)", my: "အမေ", emoji: "👩" },
        { target: "아빠", roman: "အာ့ပ္ပ (appa)", my: "အဖေ", emoji: "👨" },
        { target: "여동생", roman: "ယောဒုံဆဲင် (yeodongsaeng)", my: "ညီမ", emoji: "👧" },
        { target: "남동생", roman: "နမ်ဒုံဆဲင် (namdongsaeng)", my: "ညီ", emoji: "👦" },
        { target: "아들", roman: "အာဒွလ် (adeul)", my: "သား", emoji: "👦" },
        { target: "딸", roman: "တ္တလ် (ttal)", my: "သမီး", emoji: "👧" },
        { target: "할머니", roman: "ဟာလ်မောနီ (halmeoni)", my: "အဖွား", emoji: "👵" },
        { target: "할아버지", roman: "ဟာရာဗောဂျီ (harabeoji)", my: "အဖိုး", emoji: "👴" },
      ],
    },
    {
      slug: "days",
      title: "ရက်သတ္တပတ်",
      subtitle: "요일",
      emoji: "📅",
      items: [
        { target: "월요일", roman: "ဝေါ်ရိုအီလ် (woryoil)", my: "တနင်္လာ", emoji: "1️⃣" },
        { target: "화요일", roman: "ဟွာယိုအီလ် (hwayoil)", my: "အင်္ဂါ", emoji: "2️⃣" },
        { target: "수요일", roman: "ဆုယိုအီလ် (suyoil)", my: "ဗုဒ္ဓဟူး", emoji: "3️⃣" },
        { target: "목요일", roman: "မော့ဂျိုအီလ် (mogyoil)", my: "ကြာသပတေး", emoji: "4️⃣" },
        { target: "금요일", roman: "ကမ်ယိုအီလ် (geumyoil)", my: "သောကြာ", emoji: "5️⃣" },
        { target: "토요일", roman: "ထိုယိုအီလ် (toyoil)", my: "စနေ", emoji: "6️⃣" },
        { target: "일요일", roman: "အီရိုအီလ် (iryoil)", my: "တနင်္ဂနွေ", emoji: "7️⃣" },
      ],
    },
    {
      slug: "numbers-teens",
      title: "ဂဏန်း ၁၁–၂၀",
      subtitle: "숫자 11–20",
      emoji: "🔢",
      items: [
        { target: "십일", roman: "ဆိဗိလ် (sibil)", my: "ဆယ့်တစ် (၁၁)", emoji: "1️⃣" },
        { target: "십이", roman: "ဆိဗိ (sibi)", my: "ဆယ့်နှစ် (၁၂)", emoji: "2️⃣" },
        { target: "십삼", roman: "ဆိပ်ဆမ် (sipsam)", my: "ဆယ့်သုံး (၁၃)", emoji: "3️⃣" },
        { target: "십사", roman: "ဆိပ်ဆာ (sipsa)", my: "ဆယ့်လေး (၁၄)", emoji: "4️⃣" },
        { target: "십오", roman: "ဆိဗို (sibo)", my: "ဆယ့်ငါး (၁၅)", emoji: "5️⃣" },
        { target: "십육", roman: "ဆမ်ညွတ် (simnyuk)", my: "ဆယ့်ခြောက် (၁၆)", emoji: "6️⃣" },
        { target: "십칠", roman: "ဆိပ်ချိလ် (sipchil)", my: "ဆယ့်ခုနစ် (၁၇)", emoji: "7️⃣" },
        { target: "십팔", roman: "ဆိပ်ပါလ် (sippal)", my: "ဆယ့်ရှစ် (၁၈)", emoji: "8️⃣" },
        { target: "십구", roman: "ဆိပ်ကု (sipgu)", my: "ဆယ့်ကိုး (၁၉)", emoji: "9️⃣" },
        { target: "이십", roman: "အီဆိပ် (isip)", my: "နှစ်ဆယ် (၂၀)", emoji: "🔟" },
      ],
    },
    {
      slug: "months",
      title: "လများ (၁၂ လ)",
      subtitle: "월 (dal)",
      emoji: "📅",
      items: [
        { target: "일월", roman: "အီ ရွဲ (irwol)", my: "ဇန်နဝါရီ", emoji: "❄️" },
        { target: "이월", roman: "အီ ဝွဲ (iwol)", my: "ဖေဖော်ဝါရီ", emoji: "💝" },
        { target: "삼월", roman: "ဆမ် ဝွဲ (samwol)", my: "မတ်", emoji: "🌱" },
        { target: "사월", roman: "ဆာ ဝွဲ (sawol)", my: "ဧပြီ", emoji: "🌧️" },
        { target: "오월", roman: "အို ဝွဲ (owol)", my: "မေ", emoji: "🌸" },
        { target: "유월", roman: "ယု ဝွဲ (yuwol)", my: "ဇွန်", emoji: "☀️" },
        { target: "칠월", roman: "ချိ ရွဲ (chirwol)", my: "ဇူလိုင်", emoji: "🎆" },
        { target: "팔월", roman: "ဖါ ရွဲ (parwol)", my: "သြဂုတ်", emoji: "🏖️" },
        { target: "구월", roman: "ကု ဝွဲ (guwol)", my: "စက်တင်ဘာ", emoji: "🍂" },
        { target: "시월", roman: "ရှိ ဝွဲ (siwol)", my: "အောက်တိုဘာ", emoji: "🎃" },
        { target: "십일월", roman: "ရှိ ဗိ ရွဲ (sibirwol)", my: "နိုဝင်ဘာ", emoji: "🍁" },
        { target: "십이월", roman: "ရှိ ဗိ ဝွဲ (sibiwol)", my: "ဒီဇင်ဘာ", emoji: "🎄" },
      ],
    },
    {
      slug: "body-parts",
      title: "ခန္ဓာကိုယ် အစိတ်အပိုင်း",
      subtitle: "몸 (mom)",
      emoji: "🧍",
      items: [
        { target: "머리", roman: "မော်ရိ (meori)", my: "ခေါင်း", emoji: "👤" },
        { target: "머리카락", roman: "မော်ရိ ကရက် (meorikarak)", my: "ဆံပင်", emoji: "💇" },
        { target: "눈", roman: "နွန် (nun)", my: "မျက်လုံး", emoji: "👁️" },
        { target: "귀", roman: "ကွီ (gwi)", my: "နား", emoji: "👂" },
        { target: "코", roman: "ကို (ko)", my: "နှာခေါင်း", emoji: "👃" },
        { target: "입", roman: "အိပ် (ip)", my: "ပါးစပ်", emoji: "👄" },
        { target: "치아", roman: "ချီအာ (chia)", my: "သွား", emoji: "🦷" },
        { target: "손", roman: "ဆွန် (son)", my: "လက်", emoji: "✋" },
        { target: "팔", roman: "ဖါလ် (pal)", my: "လက်မောင်း", emoji: "💪" },
        { target: "다리", roman: "တာရိ (dari)", my: "ခြေထောက်", emoji: "🦵" },
        { target: "배", roman: "ပဲ (bae)", my: "ဗိုက်", emoji: "🫃" },
        { target: "심장", roman: "ရှင်း ဂျန် (simjang)", my: "နှလုံး", emoji: "❤️" },
      ],
    },
    {
      slug: "weather",
      title: "ရာသီဥတု",
      subtitle: "날씨 (nalssi)",
      emoji: "🌦️",
      items: [
        { target: "맑음", roman: "မဲလ်ဂွမ် (malgeum)", my: "နေသာ", emoji: "☀️" },
        { target: "비", roman: "ပီ (bi)", my: "မိုး", emoji: "🌧️" },
        { target: "구름", roman: "ကုရွမ် (gureum)", my: "တိမ်", emoji: "☁️" },
        { target: "바람", roman: "ပါရမ် (baram)", my: "လေ", emoji: "🌬️" },
        { target: "더위", roman: "တော်ဝီ (deowi)", my: "အပူ", emoji: "🔥" },
        { target: "추위", roman: "ချုဝီ (chuwi)", my: "အအေး", emoji: "🥶" },
        { target: "폭풍", roman: "ဖော့ပွန် (pokpung)", my: "မုန်တိုင်း", emoji: "⛈️" },
        { target: "눈", roman: "နွန် (nun)", my: "နှင်း", emoji: "❄️" },
        { target: "무지개", roman: "မုဂျိဂဲ (mujigae)", my: "သက်တံ့", emoji: "🌈" },
        { target: "안개", roman: "အန်ဂဲ (angae)", my: "မြူ", emoji: "🌫️" },
      ],
    },
    {
      slug: "house-rooms",
      title: "အိမ်နှင့် အခန်းများ",
      subtitle: "집 (jip)",
      emoji: "🏠",
      items: [
        { target: "집", roman: "ဂျိပ် (jip)", my: "အိမ်", emoji: "🏠" },
        { target: "문", roman: "မွန် (mun)", my: "တံခါး", emoji: "🚪" },
        { target: "창문", roman: "ချန်မွန် (changmun)", my: "ပြတင်းပေါက်", emoji: "🪟" },
        { target: "부엌", roman: "ပုအော့ (bueok)", my: "မီးဖိုချောင်", emoji: "🍳" },
        { target: "침실", roman: "ချင်ရှိလ် (chimsil)", my: "အိပ်ခန်း", emoji: "🛌" },
        { target: "욕실", roman: "ယော့ရှိလ် (yoksil)", my: "ရေချိုးခန်း", emoji: "🛁" },
        { target: "거실", roman: "ကော်ရှိလ် (geosil)", my: "ဧည့်ခန်း", emoji: "🛋️" },
        { target: "탁자", roman: "ထက်ဂျ (takja)", my: "စားပွဲ", emoji: "🍽️" },
        { target: "의자", roman: "အွီဂျ (uija)", my: "ကုလားထိုင်", emoji: "🪑" },
        { target: "침대", roman: "ချင်ဒဲ (chimdae)", my: "ကုတင်", emoji: "🛏️" },
      ],
    },
    {
      slug: "transport",
      title: "သယ်ယူပို့ဆောင်ရေး",
      subtitle: "교통 (gyotong)",
      emoji: "🚗",
      items: [
        { target: "자동차", roman: "ဂျ ဒွန် ချ (jadongcha)", my: "ကား", emoji: "🚗" },
        { target: "버스", roman: "ပေါ်ဆု (beoseu)", my: "ဘတ်စ်ကား", emoji: "🚌" },
        { target: "기차", roman: "ကိချ (gicha)", my: "ရထား", emoji: "🚆" },
        { target: "자전거", roman: "ဂျ ဂျွန် ဂေါ် (jajeongeo)", my: "စက်ဘီး", emoji: "🚲" },
        { target: "오토바이", roman: "အိုတိုဘိုင် (otobai)", my: "မော်တော်ဆိုင်ကယ်", emoji: "🏍️" },
        { target: "비행기", roman: "ပီ ဟဲင် ဂီ (bihaenggi)", my: "လေယာဉ်", emoji: "✈️" },
        { target: "배", roman: "ပဲ (bae)", my: "သင်္ဘော", emoji: "⛵" },
        { target: "택시", roman: "ထဲက်ရှိ (taeksi)", my: "တက္ကစီ", emoji: "🚕" },
        { target: "트럭", roman: "ထုရော့ (teureok)", my: "ကုန်တင်ကား", emoji: "🚚" },
        { target: "길", roman: "ကိလ် (gil)", my: "လမ်း", emoji: "🛣️" },
      ],
    },
  ],
};

export const LANG_COURSES: LangCourse[] = [
  ENGLISH,
  THAI,
  CHINESE,
  JAPANESE,
  KOREAN,
];

export function getLangCourse(slug: string): LangCourse | undefined {
  return LANG_COURSES.find((c) => c.slug === slug);
}

export function getLangUnit(
  courseSlug: string,
  unitSlug: string,
): { course: LangCourse; unit: LangUnit } | undefined {
  const course = getLangCourse(courseSlug);
  const unit = course?.units.find((u) => u.slug === unitSlug);
  if (!course || !unit) return undefined;
  return { course, unit };
}

// ---------------------------------------------------------------------------
// Bilingual on-screen labels
//
// The trainer's action words are shown in BOTH the language being studied and
// Burmese (e.g. "Listen · နားထောင်"), so a learner always sees the native term
// for the control they're using next to their own language.
// ---------------------------------------------------------------------------
export interface LangUiStrings {
  listen: string;
  speak: string;
  type: string;
  tapToSpeak: string;
  typeHint: string;
}

/** The Burmese half of every bilingual label (the audience's own language). */
export const MY_UI: LangUiStrings = {
  listen: "နားထောင်",
  speak: "အသံထွက်",
  type: "စာရိုက်",
  tapToSpeak: "နှိပ်ပြီးပြော",
  typeHint: "နားထောင်ပြီးရိုက်",
};

/** The target-language half, per course. */
export const LANG_UI: Record<string, LangUiStrings> = {
  english: {
    listen: "Listen",
    speak: "Speak",
    type: "Type",
    tapToSpeak: "Tap & speak",
    typeHint: "Listen, then type",
  },
  thai: {
    listen: "ฟัง",
    speak: "พูด",
    type: "พิมพ์",
    tapToSpeak: "แตะแล้วพูด",
    typeHint: "ฟังแล้วพิมพ์",
  },
  chinese: {
    listen: "听",
    speak: "说",
    type: "打字",
    tapToSpeak: "点击说话",
    typeHint: "边听边打",
  },
  japanese: {
    listen: "聞く",
    speak: "話す",
    type: "入力",
    tapToSpeak: "タップして話す",
    typeHint: "聞いて入力",
  },
  korean: {
    listen: "듣기",
    speak: "말하기",
    type: "입력",
    tapToSpeak: "눌러 말하기",
    typeHint: "듣고 입력",
  },
};

/** Bilingual labels for a course, falling back to English target words. */
export function getLangUi(courseSlug: string): LangUiStrings {
  return LANG_UI[courseSlug] ?? LANG_UI.english!;
}
