// Twenty "useful phrases" lessons, shared across every language course.
//
// Each phrase is written once by *meaning* (Burmese + emoji) with the target
// text and a pronunciation hint for all five languages side by side, so the
// English/Thai/Chinese/Japanese/Korean lessons always stay in sync. The builder
// below turns them into per-course `LangUnit`s that plug straight into the same
// listen / speak / type trainer used by the vocabulary units.
//
// Romanisation convention (matches the existing units):
//   • English  — Burmese-script phonetic hint (for a Burmese reader)
//   • Thai / Chinese / Japanese / Korean — Latin transliteration (RTGS / pinyin
//     with tone marks / rōmaji / Revised Romanisation)

import type { LangUnit, Phrase } from "./languages";

/** [target text, pronunciation hint] for one language. */
type L = [target: string, roman: string];

/** One phrase, defined by meaning and given in all five languages. */
interface PhraseRow {
  /** Burmese meaning (shared). */
  my: string;
  emoji: string;
  en: L;
  th: L;
  zh: L;
  ja: L;
  ko: L;
}

/** A themed useful-phrases lesson. */
interface PhraseLesson {
  slug: string;
  /** Burmese title. */
  title: string;
  /** English sub-label. */
  subtitle: string;
  emoji: string;
  rows: PhraseRow[];
}

export const PHRASE_LESSONS: PhraseLesson[] = [
  {
    slug: "phrases-politeness",
    title: "ယဉ်ကျေးမှု စကားစု",
    subtitle: "Politeness & courtesy",
    emoji: "🙏",
    rows: [
      {
        my: "ကျေးဇူးပြု၍",
        emoji: "🙏",
        en: ["Please", "ပလိစ်"],
        th: ["กรุณา", "karunaa"],
        zh: ["请", "qǐng"],
        ja: ["お願いします", "onegai shimasu"],
        ko: ["부탁합니다", "butakhamnida"],
      },
      {
        my: "ကျေးဇူးတင်ပါတယ်",
        emoji: "🙏",
        en: ["Thank you", "သန်ကျူး"],
        th: ["ขอบคุณ", "khop khun"],
        zh: ["谢谢", "xièxie"],
        ja: ["ありがとう", "arigatō"],
        ko: ["감사합니다", "gamsahamnida"],
      },
      {
        my: "ရပါတယ် / ကိစ္စမရှိပါ",
        emoji: "🙆",
        en: ["You're welcome", "ယုအာ ဝဲလ်ကမ်း"],
        th: ["ไม่เป็นไร", "mai pen rai"],
        zh: ["不客气", "bú kèqi"],
        ja: ["どういたしまして", "dō itashimashite"],
        ko: ["천만에요", "cheonmaneyo"],
      },
      {
        my: "တစ်ဆိတ်လောက်",
        emoji: "🙋",
        en: ["Excuse me", "အိတ်စ်ကျုးစ် မီ"],
        th: ["ขอโทษนะ", "kho thot na"],
        zh: ["请问一下", "qǐngwèn yíxià"],
        ja: ["すみません", "sumimasen"],
        ko: ["실례합니다", "sillyehamnida"],
      },
      {
        my: "တောင်းပန်ပါတယ်",
        emoji: "😔",
        en: ["I'm sorry", "အိုင်မ် ဆော်ရီ"],
        th: ["ขอโทษ", "kho thot"],
        zh: ["对不起", "duìbuqǐ"],
        ja: ["ごめんなさい", "gomen nasai"],
        ko: ["죄송합니다", "joesonghamnida"],
      },
      {
        my: "ရပါတယ် / အဆင်ပြေပါတယ်",
        emoji: "👌",
        en: ["No problem", "နိုး ပရော့ဘလမ်"],
        th: ["ไม่มีปัญหา", "mai mii panhaa"],
        zh: ["没问题", "méi wèntí"],
        ja: ["大丈夫です", "daijōbu desu"],
        ko: ["괜찮아요", "gwaenchanayo"],
      },
      {
        my: "ကျေးဇူးအများကြီးတင်ပါတယ်",
        emoji: "🙏",
        en: ["Thank you very much", "သန်ကျူး ဗယ်ရီ မပ်ချ်"],
        th: ["ขอบคุณมาก", "khop khun mak"],
        zh: ["非常感谢", "fēicháng gǎnxiè"],
        ja: ["どうもありがとうございます", "dōmo arigatō gozaimasu"],
        ko: ["정말 감사합니다", "jeongmal gamsahamnida"],
      },
    ],
  },
  {
    slug: "phrases-introductions",
    title: "မိတ်ဆက်ခြင်း",
    subtitle: "Introducing yourself",
    emoji: "🤝",
    rows: [
      {
        my: "ကျွန်တော့်နာမည် …",
        emoji: "🧑",
        en: ["My name is …", "မိုင် နိမ်း အီးဇ်"],
        th: ["ผมชื่อ …", "phom chue …"],
        zh: ["我叫 …", "wǒ jiào …"],
        ja: ["私の名前は …", "watashi no namae wa …"],
        ko: ["제 이름은 … 입니다", "je ireumeun … imnida"],
      },
      {
        my: "မင်း နာမည် ဘယ်လိုခေါ်လဲ",
        emoji: "❓",
        en: ["What is your name?", "ဝော့တ် အီးဇ် ယော် နိမ်း"],
        th: ["คุณชื่ออะไร", "khun chue arai"],
        zh: ["你叫什么名字？", "nǐ jiào shénme míngzi"],
        ja: ["お名前は何ですか", "onamae wa nan desu ka"],
        ko: ["이름이 뭐예요?", "ireumi mwoyeyo"],
      },
      {
        my: "တွေ့ရတာ ဝမ်းသာပါတယ်",
        emoji: "😊",
        en: ["Nice to meet you", "နိုက်စ် တု မိ့ ယူ"],
        th: ["ยินดีที่ได้รู้จัก", "yindii thii dai ruujak"],
        zh: ["很高兴认识你", "hěn gāoxìng rènshi nǐ"],
        ja: ["はじめまして", "hajimemashite"],
        ko: ["만나서 반가워요", "mannaseo bangawoyo"],
      },
      {
        my: "ဘယ်ကလာတာလဲ",
        emoji: "🌏",
        en: ["Where are you from?", "ဝဲယာ အာ ယူ ဖရွမ်"],
        th: ["คุณมาจากไหน", "khun maa jaak nai"],
        zh: ["你从哪里来？", "nǐ cóng nǎlǐ lái"],
        ja: ["どこから来ましたか", "doko kara kimashita ka"],
        ko: ["어디에서 왔어요?", "eodieseo wasseoyo"],
      },
      {
        my: "ကျွန်တော် မြန်မာလူမျိုးပါ",
        emoji: "🇲🇲",
        en: ["I am from Myanmar", "အိုင်မ် ဖရွမ် မြန်မာ"],
        th: ["ผมมาจากพม่า", "phom maa jaak Phamaa"],
        zh: ["我来自缅甸", "wǒ láizì Miǎndiàn"],
        ja: ["ミャンマーから来ました", "Myanmā kara kimashita"],
        ko: ["저는 미얀마에서 왔어요", "jeoneun Miyanma-eseo wasseoyo"],
      },
      {
        my: "အသက် ဘယ်လောက်ရှိပြီလဲ",
        emoji: "🎂",
        en: ["How old are you?", "ဟောင် အိုးလ်ဒ် အာ ယူ"],
        th: ["คุณอายุเท่าไหร่", "khun aayu thao rai"],
        zh: ["你多大了？", "nǐ duō dà le"],
        ja: ["何歳ですか", "nan sai desu ka"],
        ko: ["몇 살이에요?", "myeot sarieyo"],
      },
      {
        my: "ကျွန်တော် ဒီမှာ အလုပ်လုပ်ပါတယ်",
        emoji: "💼",
        en: ["I work here", "အိုင် ဝပ် ဟီးယား"],
        th: ["ผมทำงานที่นี่", "phom thamngaan thii nii"],
        zh: ["我在这里工作", "wǒ zài zhèlǐ gōngzuò"],
        ja: ["ここで働いています", "koko de hataraite imasu"],
        ko: ["저는 여기서 일해요", "jeoneun yeogiseo ilhaeyo"],
      },
    ],
  },
  {
    slug: "phrases-small-talk",
    title: "ရင်းနှီးစကား",
    subtitle: "Small talk",
    emoji: "💬",
    rows: [
      {
        my: "နေကောင်းလား",
        emoji: "🙂",
        en: ["How are you?", "ဟောင် အာ ယူ"],
        th: ["สบายดีไหม", "sabai dii mai"],
        zh: ["你好吗？", "nǐ hǎo ma"],
        ja: ["お元気ですか", "ogenki desu ka"],
        ko: ["잘 지내요?", "jal jinaeyo"],
      },
      {
        my: "ကောင်းပါတယ်၊ ကျေးဇူးပါ",
        emoji: "👍",
        en: ["I'm fine, thanks", "အိုင်မ် ဖိုင်း သန်ကျ်"],
        th: ["สบายดี ขอบคุณ", "sabai dii khop khun"],
        zh: ["我很好，谢谢", "wǒ hěn hǎo, xièxie"],
        ja: ["元気です、ありがとう", "genki desu, arigatō"],
        ko: ["잘 지내요, 고마워요", "jal jinaeyo, gomawoyo"],
      },
      {
        my: "အလုပ် အဆင်ပြေလား",
        emoji: "💼",
        en: ["How's work?", "ဟောင်း ဝပ်"],
        th: ["งานเป็นยังไงบ้าง", "ngaan pen yangngai baang"],
        zh: ["工作怎么样？", "gōngzuò zěnmeyàng"],
        ja: ["仕事はどうですか", "shigoto wa dō desu ka"],
        ko: ["일은 어때요?", "ireun eottaeyo"],
      },
      {
        my: "ဒီနေ့ ရာသီဥတု လှတယ်နော်",
        emoji: "☀️",
        en: ["Nice weather today", "နိုက်စ် ဝဲသာ တုဒေး"],
        th: ["วันนี้อากาศดี", "wan nii aakaat dii"],
        zh: ["今天天气很好", "jīntiān tiānqì hěn hǎo"],
        ja: ["今日はいい天気ですね", "kyō wa ii tenki desu ne"],
        ko: ["오늘 날씨가 좋네요", "oneul nalssiga jonneyo"],
      },
      {
        my: "ဘာလုပ်နေလဲ",
        emoji: "🤔",
        en: ["What are you doing?", "ဝော့တ် အာ ယူ ဒူးအင်း"],
        th: ["ทำอะไรอยู่", "tham arai yuu"],
        zh: ["你在做什么？", "nǐ zài zuò shénme"],
        ja: ["何をしていますか", "nani o shite imasu ka"],
        ko: ["뭐 하고 있어요?", "mwo hago isseoyo"],
      },
      {
        my: "အားလပ်ချိန် ဘာလုပ်ဖြစ်လဲ",
        emoji: "🎮",
        en: ["What do you do for fun?", "ဝော့တ် ဒူ ယူ ဒူ ဖော ဖန်း"],
        th: ["เวลาว่างทำอะไร", "welaa waang tham arai"],
        zh: ["你有空喜欢做什么？", "nǐ yǒu kòng xǐhuan zuò shénme"],
        ja: ["趣味は何ですか", "shumi wa nan desu ka"],
        ko: ["취미가 뭐예요?", "chwimiga mwoyeyo"],
      },
      {
        my: "နောက်မှ တွေ့မယ်နော်",
        emoji: "👋",
        en: ["See you later", "ဆီး ယူ လေးတာ"],
        th: ["ไว้เจอกันใหม่", "wai jer kan mai"],
        zh: ["回头见", "huítóu jiàn"],
        ja: ["また後で", "mata atode"],
        ko: ["나중에 봐요", "najunge bwayo"],
      },
    ],
  },
  {
    slug: "phrases-directions",
    title: "လမ်းညွှန် မေးခြင်း",
    subtitle: "Asking directions",
    emoji: "🧭",
    rows: [
      {
        my: "… ဘယ်မှာလဲ",
        emoji: "📍",
        en: ["Where is …?", "ဝဲယာ အီးဇ်"],
        th: ["… อยู่ที่ไหน", "… yuu thii nai"],
        zh: ["… 在哪里？", "… zài nǎlǐ"],
        ja: ["… はどこですか", "… wa doko desu ka"],
        ko: ["… 어디에 있어요?", "… eodie isseoyo"],
      },
      {
        my: "ဒီကို ဘယ်လိုသွားရမလဲ",
        emoji: "🗺️",
        en: ["How do I get there?", "ဟောင် ဒူ အိုင် ဂက် ဒဲယာ"],
        th: ["ไปที่นั่นยังไง", "pai thii nan yangngai"],
        zh: ["怎么去那里？", "zěnme qù nàlǐ"],
        ja: ["そこへどう行きますか", "soko e dō ikimasu ka"],
        ko: ["거기 어떻게 가요?", "geogi eotteoke gayo"],
      },
      {
        my: "ဘယ်ဘက်ကွေ့ပါ",
        emoji: "⬅️",
        en: ["Turn left", "တန်း လက်ဖ်"],
        th: ["เลี้ยวซ้าย", "liao sai"],
        zh: ["向左转", "xiàng zuǒ zhuǎn"],
        ja: ["左に曲がってください", "hidari ni magatte kudasai"],
        ko: ["왼쪽으로 도세요", "oenjjogeuro doseyo"],
      },
      {
        my: "ညာဘက်ကွေ့ပါ",
        emoji: "➡️",
        en: ["Turn right", "တန်း ရိုက်"],
        th: ["เลี้ยวขวา", "liao khwaa"],
        zh: ["向右转", "xiàng yòu zhuǎn"],
        ja: ["右に曲がってください", "migi ni magatte kudasai"],
        ko: ["오른쪽으로 도세요", "oreunjjogeuro doseyo"],
      },
      {
        my: "တည့်တည့်သွားပါ",
        emoji: "⬆️",
        en: ["Go straight ahead", "ဂို စတရိတ် အဟဲဒ်"],
        th: ["ตรงไป", "trong pai"],
        zh: ["一直走", "yìzhí zǒu"],
        ja: ["まっすぐ行ってください", "massugu itte kudasai"],
        ko: ["똑바로 가세요", "ttokbaro gaseyo"],
      },
      {
        my: "ဒါ ဝေးသလား",
        emoji: "📏",
        en: ["Is it far?", "အီးဇ် အစ် ဖာ"],
        th: ["ไกลไหม", "klai mai"],
        zh: ["远吗？", "yuǎn ma"],
        ja: ["遠いですか", "tōi desu ka"],
        ko: ["멀어요?", "meoreoyo"],
      },
      {
        my: "မြေပုံပေါ်မှာ ပြပေးနိုင်မလား",
        emoji: "🗺️",
        en: ["Can you show me on the map?", "ကန် ယူ ရှိုး မီ အွန် ဒ မဲ့ပ်"],
        th: ["ช่วยชี้บนแผนที่ได้ไหม", "chuai chii bon phaenthii dai mai"],
        zh: ["能在地图上指给我吗？", "néng zài dìtú shàng zhǐ gěi wǒ ma"],
        ja: ["地図で見せてもらえますか", "chizu de misete moraemasu ka"],
        ko: ["지도에서 보여줄 수 있어요?", "jidoeseo boyeojul su isseoyo"],
      },
    ],
  },
  {
    slug: "phrases-restaurant",
    title: "အစားအသောက် မှာယူခြင်း",
    subtitle: "Ordering food",
    emoji: "🍽️",
    rows: [
      {
        my: "မီနူး ပေးပါ",
        emoji: "📋",
        en: ["Menu, please", "မဲနျူး ပလိစ်"],
        th: ["ขอเมนูหน่อย", "kho menuu noi"],
        zh: ["请给我菜单", "qǐng gěi wǒ càidān"],
        ja: ["メニューをください", "menyū o kudasai"],
        ko: ["메뉴 주세요", "menyu juseyo"],
      },
      {
        my: "ဒါ တစ်ခု ယူမယ်",
        emoji: "👉",
        en: ["I'll have this one", "အိုင်လ် ဟဲ့ဗ် ဒစ် ဝမ်း"],
        th: ["ขออันนี้", "kho an nii"],
        zh: ["我要这个", "wǒ yào zhège"],
        ja: ["これをください", "kore o kudasai"],
        ko: ["이거 주세요", "igeo juseyo"],
      },
      {
        my: "စပ်တာ မလိုချင်ဘူး",
        emoji: "🌶️",
        en: ["Not spicy, please", "နော့တ် စပိုက်ဆီ ပလိစ်"],
        th: ["ไม่เผ็ดนะ", "mai phet na"],
        zh: ["不要辣", "búyào là"],
        ja: ["辛くしないでください", "karaku shinaide kudasai"],
        ko: ["안 맵게 해주세요", "an maepge haejuseyo"],
      },
      {
        my: "ဒါ အသားပါလား",
        emoji: "🥩",
        en: ["Does this have meat?", "ဒဇ် ဒစ် ဟဲ့ဗ် မိတ်"],
        th: ["อันนี้มีเนื้อไหม", "an nii mii nuea mai"],
        zh: ["这个有肉吗？", "zhège yǒu ròu ma"],
        ja: ["これは肉が入っていますか", "kore wa niku ga haitte imasu ka"],
        ko: ["이거 고기 들어 있어요?", "igeo gogi deureo isseoyo"],
      },
      {
        my: "ရေ တစ်ခွက် ပေးပါ",
        emoji: "💧",
        en: ["A glass of water, please", "အ ဂလပ်စ် အွဗ် ဝေါ်တာ"],
        th: ["ขอน้ำแก้วนึง", "kho nam kaeo nueng"],
        zh: ["请给我一杯水", "qǐng gěi wǒ yì bēi shuǐ"],
        ja: ["お水を一杯ください", "omizu o ippai kudasai"],
        ko: ["물 한 잔 주세요", "mul han jan juseyo"],
      },
      {
        my: "အရမ်းစားလို့ကောင်းတယ်",
        emoji: "😋",
        en: ["It's delicious", "အစ် ဒီးလစ်ရှပ်စ်"],
        th: ["อร่อยมาก", "aroi mak"],
        zh: ["很好吃", "hěn hǎochī"],
        ja: ["とても美味しいです", "totemo oishii desu"],
        ko: ["정말 맛있어요", "jeongmal masisseoyo"],
      },
      {
        my: "ငွေရှင်းမယ်",
        emoji: "🧾",
        en: ["The bill, please", "ဒ ဘေး ပလိစ်"],
        th: ["เก็บเงินด้วย", "kep ngoen duai"],
        zh: ["买单", "mǎidān"],
        ja: ["お会計をお願いします", "okaikei o onegai shimasu"],
        ko: ["계산해 주세요", "gyesanhae juseyo"],
      },
    ],
  },
  {
    slug: "phrases-shopping",
    title: "ဈေးဝယ်ခြင်းနှင့် ဈေးဆစ်ခြင်း",
    subtitle: "Shopping & bargaining",
    emoji: "🛍️",
    rows: [
      {
        my: "ဒါ ဘယ်လောက်လဲ",
        emoji: "💰",
        en: ["How much is this?", "ဟောင် မပ်ချ် အီးဇ် ဒစ်"],
        th: ["อันนี้เท่าไหร่", "an nii thao rai"],
        zh: ["这个多少钱？", "zhège duōshao qián"],
        ja: ["これはいくらですか", "kore wa ikura desu ka"],
        ko: ["이거 얼마예요?", "igeo eolmayeyo"],
      },
      {
        my: "စျေးကြီးလွန်းတယ်",
        emoji: "😮",
        en: ["It's too expensive", "အစ် တူး အိတ်စ်ပဲန်ဆစ်"],
        th: ["แพงไป", "phaeng pai"],
        zh: ["太贵了", "tài guì le"],
        ja: ["高すぎます", "taka sugimasu"],
        ko: ["너무 비싸요", "neomu bissayo"],
      },
      {
        my: "လျှော့ပေးလို့ရမလား",
        emoji: "🏷️",
        en: ["Can you lower the price?", "ကန် ယူ လိုးဝါ ဒ ပရိုက်စ်"],
        th: ["ลดได้ไหม", "lot dai mai"],
        zh: ["可以便宜点吗？", "kěyǐ piányi diǎn ma"],
        ja: ["安くできますか", "yasuku dekimasu ka"],
        ko: ["깎아 주실 수 있어요?", "kkakka jusil su isseoyo"],
      },
      {
        my: "အခြားအရောင် ရှိလား",
        emoji: "🎨",
        en: ["Do you have another color?", "ဒူ ယူ ဟဲ့ဗ် အနာသာ ကာလာ"],
        th: ["มีสีอื่นไหม", "mii sii uen mai"],
        zh: ["有别的颜色吗？", "yǒu biéde yánsè ma"],
        ja: ["他の色はありますか", "hoka no iro wa arimasu ka"],
        ko: ["다른 색 있어요?", "dareun saek isseoyo"],
      },
      {
        my: "စမ်းဝတ်ကြည့်လို့ရလား",
        emoji: "👗",
        en: ["Can I try it on?", "ကန် အိုင် ထရိုင် အစ် အွန်"],
        th: ["ลองได้ไหม", "long dai mai"],
        zh: ["可以试穿吗？", "kěyǐ shìchuān ma"],
        ja: ["試着できますか", "shichaku dekimasu ka"],
        ko: ["입어 봐도 돼요?", "ibeo bwado dwaeyo"],
      },
      {
        my: "ဒါ ယူမယ်",
        emoji: "🛒",
        en: ["I'll take it", "အိုင်လ် တိတ်ခ် အစ်"],
        th: ["เอาอันนี้", "ao an nii"],
        zh: ["我要买这个", "wǒ yào mǎi zhège"],
        ja: ["これにします", "kore ni shimasu"],
        ko: ["이걸로 할게요", "igeollo halgeyo"],
      },
      {
        my: "ကတ်နဲ့ ပေးလို့ရလား",
        emoji: "💳",
        en: ["Can I pay by card?", "ကန် အိုင် ပေး ဘိုင် ကတ်"],
        th: ["จ่ายบัตรได้ไหม", "jaai bat dai mai"],
        zh: ["可以刷卡吗？", "kěyǐ shuākǎ ma"],
        ja: ["カードで払えますか", "kādo de haraemasu ka"],
        ko: ["카드로 내도 돼요?", "kadeuro naedo dwaeyo"],
      },
    ],
  },
  {
    slug: "phrases-hotel",
    title: "ဟိုတယ်တွင်",
    subtitle: "At the hotel",
    emoji: "🏨",
    rows: [
      {
        my: "အခန်း ကြိုတင်မှာထားပါတယ်",
        emoji: "🛎️",
        en: ["I have a reservation", "အိုင် ဟဲ့ဗ် အ ရီဇာဗေးရှင်း"],
        th: ["ผมจองห้องไว้", "phom jong hong wai"],
        zh: ["我有预订", "wǒ yǒu yùdìng"],
        ja: ["予約しています", "yoyaku shite imasu"],
        ko: ["예약했어요", "yeyakhaesseoyo"],
      },
      {
        my: "အခန်းလွတ် ရှိလား",
        emoji: "🚪",
        en: ["Do you have a room available?", "ဒူ ယူ ဟဲ့ဗ် အ ရွမ်"],
        th: ["มีห้องว่างไหม", "mii hong waang mai"],
        zh: ["有空房吗？", "yǒu kòngfáng ma"],
        ja: ["空き部屋はありますか", "aki beya wa arimasu ka"],
        ko: ["빈 방 있어요?", "bin bang isseoyo"],
      },
      {
        my: "တစ်ညကို ဘယ်လောက်လဲ",
        emoji: "🌙",
        en: ["How much per night?", "ဟောင် မပ်ချ် ပါ နိုက်"],
        th: ["คืนละเท่าไหร่", "khuen la thao rai"],
        zh: ["一晚多少钱？", "yì wǎn duōshao qián"],
        ja: ["一泊いくらですか", "ippaku ikura desu ka"],
        ko: ["하룻밤에 얼마예요?", "harutbame eolmayeyo"],
      },
      {
        my: "Wi-Fi စကားဝှက် ဘယ်လိုလဲ",
        emoji: "📶",
        en: ["What's the Wi-Fi password?", "ဝော့တ်စ် ဒ ဝိုင်ဖိုင် ပတ်စ်ဝတ်"],
        th: ["รหัสไวไฟอะไร", "rahat waifai arai"],
        zh: ["Wi-Fi 密码是什么？", "Wi-Fi mìmǎ shì shénme"],
        ja: ["Wi-Fiのパスワードは何ですか", "Wi-Fi no pasuwādo wa nan desu ka"],
        ko: ["와이파이 비밀번호가 뭐예요?", "waipai bimilbeonhoga mwoyeyo"],
      },
      {
        my: "ဘယ်အချိန် Check-out လုပ်ရမလဲ",
        emoji: "⏰",
        en: ["What time is checkout?", "ဝော့တ် တိုင်း အီးဇ် ချက်အောက်"],
        th: ["เช็คเอาท์กี่โมง", "chek-ao kii mong"],
        zh: ["几点退房？", "jǐ diǎn tuìfáng"],
        ja: ["チェックアウトは何時ですか", "chekku auto wa nan ji desu ka"],
        ko: ["체크아웃은 몇 시예요?", "chekeuauseun myeot siyeyo"],
      },
      {
        my: "အခန်း အအေးစက် ပျက်နေတယ်",
        emoji: "❄️",
        en: ["The air-con isn't working", "ဒ အဲယာကွန်း အစ်ဇင့် ဝပ်ကင်း"],
        th: ["แอร์ไม่ทำงาน", "ae mai thamngaan"],
        zh: ["空调坏了", "kōngtiáo huài le"],
        ja: ["エアコンが壊れています", "eakon ga kowarete imasu"],
        ko: ["에어컨이 안 돼요", "eeokeoni an dwaeyo"],
      },
      {
        my: "အိတ်တွေ သိမ်းပေးလို့ရလား",
        emoji: "🧳",
        en: ["Can you keep my bags?", "ကန် ယူ ကိပ် မိုင် ဘဲဂ်စ်"],
        th: ["ฝากกระเป๋าได้ไหม", "faak krapao dai mai"],
        zh: ["可以帮我存行李吗？", "kěyǐ bāng wǒ cún xíngli ma"],
        ja: ["荷物を預かってもらえますか", "nimotsu o azukatte moraemasu ka"],
        ko: ["짐 좀 맡아 주실 수 있어요?", "jim jom mata jusil su isseoyo"],
      },
    ],
  },
  {
    slug: "phrases-transport",
    title: "လက်မှတ်နှင့် သယ်ယူပို့ဆောင်ရေး",
    subtitle: "Tickets & transport",
    emoji: "🚌",
    rows: [
      {
        my: "လက်မှတ်တစ်စောင် ပေးပါ",
        emoji: "🎫",
        en: ["One ticket, please", "ဝမ်း တစ်ကက် ပလိစ်"],
        th: ["ขอตั๋วหนึ่งใบ", "kho tua nueng bai"],
        zh: ["请给我一张票", "qǐng gěi wǒ yì zhāng piào"],
        ja: ["切符を一枚ください", "kippu o ichimai kudasai"],
        ko: ["표 한 장 주세요", "pyo han jang juseyo"],
      },
      {
        my: "ဒီ ဘတ်စ်ကား … ကို သွားလား",
        emoji: "🚌",
        en: ["Does this bus go to …?", "ဒဇ် ဒစ် ဘတ်စ် ဂို တု"],
        th: ["รถเมล์คันนี้ไป … ไหม", "rot mee khan nii pai … mai"],
        zh: ["这辆车去 … 吗？", "zhè liàng chē qù … ma"],
        ja: ["このバスは … へ行きますか", "kono basu wa … e ikimasu ka"],
        ko: ["이 버스 … 가요?", "i beoseu … gayo"],
      },
      {
        my: "ဘယ်ဘူတာမှာ ဆင်းရမလဲ",
        emoji: "🚉",
        en: ["Which stop do I get off?", "ဝှစ်ချ် စတော့ ဒူ အိုင် ဂက် အော့ဖ်"],
        th: ["ลงป้ายไหน", "long pai nai"],
        zh: ["在哪一站下车？", "zài nǎ yí zhàn xiàchē"],
        ja: ["どの駅で降りますか", "dono eki de orimasu ka"],
        ko: ["어느 정류장에서 내려요?", "eoneu jeongnyujangeseo naeryeoyo"],
      },
      {
        my: "ဒီမှာ ရပ်ပေးပါ",
        emoji: "🛑",
        en: ["Stop here, please", "စတော့ ဟီးယား ပလိစ်"],
        th: ["จอดตรงนี้", "jot trong nii"],
        zh: ["请在这里停", "qǐng zài zhèlǐ tíng"],
        ja: ["ここで止めてください", "koko de tomete kudasai"],
        ko: ["여기서 세워 주세요", "yeogiseo sewo juseyo"],
      },
      {
        my: "တက္ကစီ ခေါ်ပေးပါ",
        emoji: "🚕",
        en: ["Call a taxi, please", "ကော် အ တက်ဆီ ပလိစ်"],
        th: ["เรียกแท็กซี่ให้หน่อย", "riak thaeksii hai noi"],
        zh: ["请帮我叫出租车", "qǐng bāng wǒ jiào chūzūchē"],
        ja: ["タクシーを呼んでください", "takushī o yonde kudasai"],
        ko: ["택시 좀 불러 주세요", "taeksi jom bulleo juseyo"],
      },
      {
        my: "ရထား ဘယ်အချိန် ထွက်မလဲ",
        emoji: "🚆",
        en: ["What time does the train leave?", "ဝော့တ် တိုင်း ဒဇ် ဒ ထရိန်း လိစ်"],
        th: ["รถไฟออกกี่โมง", "rotfai ok kii mong"],
        zh: ["火车几点开？", "huǒchē jǐ diǎn kāi"],
        ja: ["電車は何時に出ますか", "densha wa nan ji ni demasu ka"],
        ko: ["기차 몇 시에 떠나요?", "gicha myeot sie tteonayo"],
      },
      {
        my: "… ကို ဘယ်လောက်ပေးရမလဲ",
        emoji: "💵",
        en: ["How much to …?", "ဟောင် မပ်ချ် တု"],
        th: ["ไป … เท่าไหร่", "pai … thao rai"],
        zh: ["到 … 多少钱？", "dào … duōshao qián"],
        ja: ["… までいくらですか", "… made ikura desu ka"],
        ko: ["… 까지 얼마예요?", "… kkaji eolmayeyo"],
      },
    ],
  },
  {
    slug: "phrases-phone",
    title: "ဖုန်းနှင့် မက်ဆေ့ချ်",
    subtitle: "Phone & messaging",
    emoji: "📱",
    rows: [
      {
        my: "ဟဲလို၊ ဘယ်သူပါလဲ",
        emoji: "📞",
        en: ["Hello, who is this?", "ဟဲလို ဟူး အီးဇ် ဒစ်"],
        th: ["ฮัลโหล ใครพูด", "hanlo khrai phuut"],
        zh: ["喂，请问是谁？", "wéi, qǐngwèn shì shéi"],
        ja: ["もしもし、どちら様ですか", "moshi moshi, dochira sama desu ka"],
        ko: ["여보세요, 누구세요?", "yeoboseyo, nuguseyo"],
      },
      {
        my: "ခဏစောင့်ပါ",
        emoji: "⏳",
        en: ["Just a moment, please", "ဂျပ်စ် အ မိုးမင့် ပလိစ်"],
        th: ["รอสักครู่", "ro sak khru"],
        zh: ["请稍等", "qǐng shāo děng"],
        ja: ["少々お待ちください", "shōshō omachi kudasai"],
        ko: ["잠깐만요", "jamkkanmanyo"],
      },
      {
        my: "ဖုန်းနံပါတ် ဘယ်လိုလဲ",
        emoji: "🔢",
        en: ["What's your phone number?", "ဝော့တ်စ် ယော် ဖုန်း နမ်ဘာ"],
        th: ["เบอร์โทรอะไร", "boe tho arai"],
        zh: ["你的电话号码是多少？", "nǐ de diànhuà hàomǎ shì duōshao"],
        ja: ["電話番号は何番ですか", "denwa bangō wa nan ban desu ka"],
        ko: ["전화번호가 뭐예요?", "jeonhwabeonhoga mwoyeyo"],
      },
      {
        my: "Message ပို့လိုက်မယ်",
        emoji: "✉️",
        en: ["I'll send you a message", "အိုင်လ် ဆဲန်ဒ် ယူ အ မက်ဆေ့ချ်"],
        th: ["จะส่งข้อความให้", "ja song khokhwaam hai"],
        zh: ["我给你发消息", "wǒ gěi nǐ fā xiāoxi"],
        ja: ["メッセージを送ります", "messēji o okurimasu"],
        ko: ["메시지 보낼게요", "mesiji bonaelgeyo"],
      },
      {
        my: "အသံ မကြားရဘူး",
        emoji: "🔇",
        en: ["I can't hear you", "အိုင် ကန့် ဟီးယား ယူ"],
        th: ["ได้ยินไม่ชัด", "dai yin mai chat"],
        zh: ["我听不清", "wǒ tīng bù qīng"],
        ja: ["よく聞こえません", "yoku kikoemasen"],
        ko: ["잘 안 들려요", "jal an deullyeoyo"],
      },
      {
        my: "နောက်မှ ပြန်ခေါ်မယ်",
        emoji: "🔁",
        en: ["I'll call you back", "အိုင်လ် ကော် ယူ ဘက်ခ်"],
        th: ["เดี๋ยวโทรกลับ", "diao tho klap"],
        zh: ["我等会儿回你电话", "wǒ děng huǐr huí nǐ diànhuà"],
        ja: ["後で電話します", "atode denwa shimasu"],
        ko: ["나중에 다시 전화할게요", "najunge dasi jeonhwahalgeyo"],
      },
      {
        my: "Charger ရှိလား",
        emoji: "🔌",
        en: ["Do you have a charger?", "ဒူ ယူ ဟဲ့ဗ် အ ချာဂျာ"],
        th: ["มีที่ชาร์จไหม", "mii thii chaat mai"],
        zh: ["你有充电器吗？", "nǐ yǒu chōngdiànqì ma"],
        ja: ["充電器はありますか", "jūdenki wa arimasu ka"],
        ko: ["충전기 있어요?", "chungjeongi isseoyo"],
      },
    ],
  },
  {
    slug: "phrases-emergency",
    title: "အရေးပေါ်",
    subtitle: "Emergencies",
    emoji: "🆘",
    rows: [
      {
        my: "ကူညီပါ",
        emoji: "🆘",
        en: ["Help!", "ဟဲ့ပ်"],
        th: ["ช่วยด้วย", "chuai duai"],
        zh: ["救命！", "jiùmìng"],
        ja: ["助けて", "tasukete"],
        ko: ["도와주세요", "dowajuseyo"],
      },
      {
        my: "ဆရာဝန် ခေါ်ပါ",
        emoji: "👨‍⚕️",
        en: ["Call a doctor", "ကော် အ ဒေါက်တာ"],
        th: ["เรียกหมอ", "riak mo"],
        zh: ["叫医生", "jiào yīshēng"],
        ja: ["医者を呼んでください", "isha o yonde kudasai"],
        ko: ["의사를 불러 주세요", "uisareul bulleo juseyo"],
      },
      {
        my: "ရဲ ခေါ်ပါ",
        emoji: "🚓",
        en: ["Call the police", "ကော် ဒ ပိုလိစ်"],
        th: ["เรียกตำรวจ", "riak tamruat"],
        zh: ["报警", "bàojǐng"],
        ja: ["警察を呼んでください", "keisatsu o yonde kudasai"],
        ko: ["경찰을 불러 주세요", "gyeongchareul bulleo juseyo"],
      },
      {
        my: "မတော်တဆမှု ဖြစ်တယ်",
        emoji: "🚑",
        en: ["There's been an accident", "ဒဲယာစ် ဘင်း အန် အက်ဆီးဒင့်"],
        th: ["มีอุบัติเหตุ", "mii ubatihet"],
        zh: ["出事故了", "chū shìgù le"],
        ja: ["事故が起きました", "jiko ga okimashita"],
        ko: ["사고가 났어요", "sagoga nasseoyo"],
      },
      {
        my: "လမ်းပျောက်နေတယ်",
        emoji: "🧭",
        en: ["I'm lost", "အိုင်မ် လော့စ်"],
        th: ["ผมหลงทาง", "phom long thaang"],
        zh: ["我迷路了", "wǒ mílù le"],
        ja: ["道に迷いました", "michi ni mayoimashita"],
        ko: ["길을 잃었어요", "gireul ireosseoyo"],
      },
      {
        my: "ဆေးရုံ ဘယ်မှာလဲ",
        emoji: "🏥",
        en: ["Where is the hospital?", "ဝဲယာ အီးဇ် ဒ ဟော့စ်ပီတယ်"],
        th: ["โรงพยาบาลอยู่ที่ไหน", "rong phayaabaan yuu thii nai"],
        zh: ["医院在哪里？", "yīyuàn zài nǎlǐ"],
        ja: ["病院はどこですか", "byōin wa doko desu ka"],
        ko: ["병원이 어디예요?", "byeongwoni eodiyeyo"],
      },
      {
        my: "ကျွန်တော် ဖုန်း ပျောက်သွားတယ်",
        emoji: "📵",
        en: ["I lost my phone", "အိုင် လော့စ် မိုင် ဖုန်း"],
        th: ["ผมทำโทรศัพท์หาย", "phom tham thorasap hai"],
        zh: ["我的手机丢了", "wǒ de shǒujī diū le"],
        ja: ["携帯をなくしました", "keitai o nakushimashita"],
        ko: ["휴대폰을 잃어버렸어요", "hyudaeponeul ireobeoryeosseoyo"],
      },
    ],
  },
  {
    slug: "phrases-health",
    title: "ဆရာဝန်နှင့် ဆေးဆိုင်",
    subtitle: "Doctor & pharmacy",
    emoji: "💊",
    rows: [
      {
        my: "နေမကောင်းဘူး",
        emoji: "🤒",
        en: ["I feel sick", "အိုင် ဖီးလ် ဆစ်ခ်"],
        th: ["ผมไม่สบาย", "phom mai sabai"],
        zh: ["我不舒服", "wǒ bù shūfu"],
        ja: ["気分が悪いです", "kibun ga warui desu"],
        ko: ["몸이 아파요", "momi apayo"],
      },
      {
        my: "ဒီမှာ နာတယ်",
        emoji: "😣",
        en: ["It hurts here", "အစ် ဟတ်စ် ဟီးယား"],
        th: ["เจ็บตรงนี้", "jep trong nii"],
        zh: ["这里疼", "zhèlǐ téng"],
        ja: ["ここが痛いです", "koko ga itai desu"],
        ko: ["여기가 아파요", "yeogiga apayo"],
      },
      {
        my: "ခေါင်းကိုက်တယ်",
        emoji: "🤕",
        en: ["I have a headache", "အိုင် ဟဲ့ဗ် အ ဟဲဒိတ်ခ်"],
        th: ["ปวดหัว", "puat hua"],
        zh: ["我头疼", "wǒ tóuténg"],
        ja: ["頭が痛いです", "atama ga itai desu"],
        ko: ["머리가 아파요", "meoriga apayo"],
      },
      {
        my: "အဖျားရှိတယ်",
        emoji: "🌡️",
        en: ["I have a fever", "အိုင် ဟဲ့ဗ် အ ဖီးဗာ"],
        th: ["เป็นไข้", "pen khai"],
        zh: ["我发烧", "wǒ fāshāo"],
        ja: ["熱があります", "netsu ga arimasu"],
        ko: ["열이 나요", "yeori nayo"],
      },
      {
        my: "ဆေး လိုချင်တယ်",
        emoji: "💊",
        en: ["I need medicine", "အိုင် နိဒ် မဲဒစင်"],
        th: ["ต้องการยา", "tongkaan yaa"],
        zh: ["我需要药", "wǒ xūyào yào"],
        ja: ["薬が必要です", "kusuri ga hitsuyō desu"],
        ko: ["약이 필요해요", "yagi piryohaeyo"],
      },
      {
        my: "ဒီဆေးဆိုင် ဓာတ်မတည့်ဘူး",
        emoji: "⚠️",
        en: ["I'm allergic to this", "အိုင်မ် အလာဂျစ် တု ဒစ်"],
        th: ["ผมแพ้อันนี้", "phom phae an nii"],
        zh: ["我对这个过敏", "wǒ duì zhège guòmǐn"],
        ja: ["これにアレルギーがあります", "kore ni arerugī ga arimasu"],
        ko: ["이거에 알레르기가 있어요", "igeoe allereugiga isseoyo"],
      },
      {
        my: "တစ်နေ့ ဘယ်နှစ်ကြိမ် သောက်ရမလဲ",
        emoji: "⏱️",
        en: ["How many times a day?", "ဟောင် မဲနီ တိုင်းမ်စ် အ ဒေး"],
        th: ["วันละกี่ครั้ง", "wan la kii khrang"],
        zh: ["一天几次？", "yì tiān jǐ cì"],
        ja: ["一日に何回ですか", "ichinichi ni nankai desu ka"],
        ko: ["하루에 몇 번이에요?", "harue myeot beonieyo"],
      },
    ],
  },
  {
    slug: "phrases-requests",
    title: "တောင်းဆိုခြင်း",
    subtitle: "Making requests",
    emoji: "🙋",
    rows: [
      {
        my: "ကူညီပေးလို့ရမလား",
        emoji: "🤝",
        en: ["Can you help me?", "ကန် ယူ ဟဲ့ပ် မီ"],
        th: ["ช่วยหน่อยได้ไหม", "chuai noi dai mai"],
        zh: ["你能帮我吗？", "nǐ néng bāng wǒ ma"],
        ja: ["手伝ってもらえますか", "tetsudatte moraemasu ka"],
        ko: ["도와줄 수 있어요?", "dowajul su isseoyo"],
      },
      {
        my: "ဒါ ပေးလို့ရမလား",
        emoji: "🤲",
        en: ["Could you give me this?", "ကွတ် ယူ ဂစ်ဗ် မီ ဒစ်"],
        th: ["ขออันนี้ได้ไหม", "kho an nii dai mai"],
        zh: ["能给我这个吗？", "néng gěi wǒ zhège ma"],
        ja: ["これをもらえますか", "kore o moraemasu ka"],
        ko: ["이거 주실 수 있어요?", "igeo jusil su isseoyo"],
      },
      {
        my: "ဖြည်းဖြည်း ပြောပေးပါ",
        emoji: "🐢",
        en: ["Please speak slowly", "ပလိစ် စပိစ် စလိုးလီ"],
        th: ["พูดช้าๆ หน่อย", "phuut chaa chaa noi"],
        zh: ["请说慢一点", "qǐng shuō màn yìdiǎn"],
        ja: ["ゆっくり話してください", "yukkuri hanashite kudasai"],
        ko: ["천천히 말해 주세요", "cheoncheonhi malhae juseyo"],
      },
      {
        my: "ထပ်ပြောပြပါဦး",
        emoji: "🔁",
        en: ["Can you repeat that?", "ကန် ယူ ရီပိထ် ဒဲ့တ်"],
        th: ["พูดอีกทีได้ไหม", "phuut iik thii dai mai"],
        zh: ["能再说一遍吗？", "néng zài shuō yí biàn ma"],
        ja: ["もう一度言ってください", "mō ichido itte kudasai"],
        ko: ["다시 말해 주세요", "dasi malhae juseyo"],
      },
      {
        my: "ရေးပြပေးပါ",
        emoji: "✍️",
        en: ["Please write it down", "ပလိစ် ရိုက် အစ် ဒေါင်း"],
        th: ["ช่วยเขียนให้หน่อย", "chuai khian hai noi"],
        zh: ["请写下来", "qǐng xiě xiàlái"],
        ja: ["書いてください", "kaite kudasai"],
        ko: ["적어 주세요", "jeogeo juseyo"],
      },
      {
        my: "ဓာတ်ပုံ ရိုက်ပေးလို့ရမလား",
        emoji: "📷",
        en: ["Can you take a photo?", "ကန် ယူ တိတ်ခ် အ ဖိုးတိုး"],
        th: ["ช่วยถ่ายรูปได้ไหม", "chuai thaai ruup dai mai"],
        zh: ["能帮我拍照吗？", "néng bāng wǒ pāizhào ma"],
        ja: ["写真を撮ってもらえますか", "shashin o totte moraemasu ka"],
        ko: ["사진 좀 찍어 주실 수 있어요?", "sajin jom jjigeo jusil su isseoyo"],
      },
      {
        my: "ခဏ သုံးလို့ရမလား",
        emoji: "🙏",
        en: ["May I use this?", "မေး အိုင် ယုးဇ် ဒစ်"],
        th: ["ขอใช้อันนี้ได้ไหม", "kho chai an nii dai mai"],
        zh: ["我可以用一下吗？", "wǒ kěyǐ yòng yíxià ma"],
        ja: ["これを使ってもいいですか", "kore o tsukatte mo ii desu ka"],
        ko: ["이거 써도 돼요?", "igeo sseodo dwaeyo"],
      },
    ],
  },
  {
    slug: "phrases-apologies",
    title: "တောင်းပန်ခြင်းနှင့် အကြောင်းပြချက်",
    subtitle: "Apologies & excuses",
    emoji: "🙇",
    rows: [
      {
        my: "အမှားအတွက် တောင်းပန်ပါတယ်",
        emoji: "🙇",
        en: ["I'm sorry for the mistake", "အိုင်မ် ဆော်ရီ ဖော ဒ မစ်စတိတ်ခ်"],
        th: ["ขอโทษที่ทำผิด", "kho thot thii tham phit"],
        zh: ["对不起，我错了", "duìbuqǐ, wǒ cuò le"],
        ja: ["間違えてすみません", "machigaete sumimasen"],
        ko: ["실수해서 죄송해요", "silsuhaeseo joesonghaeyo"],
      },
      {
        my: "ကျွန်တော် နောက်ကျသွားတယ်",
        emoji: "⏰",
        en: ["I'm late, sorry", "အိုင်မ် လိတ် ဆော်ရီ"],
        th: ["ผมมาสาย ขอโทษ", "phom maa sai kho thot"],
        zh: ["我迟到了，抱歉", "wǒ chídào le, bàoqiàn"],
        ja: ["遅れてすみません", "okurete sumimasen"],
        ko: ["늦어서 죄송해요", "neujeoseo joesonghaeyo"],
      },
      {
        my: "မတော်တဆပါ",
        emoji: "😳",
        en: ["It was an accident", "အစ် ဝေါ့ဇ် အန် အက်ဆီးဒင့်"],
        th: ["มันเป็นอุบัติเหตุ", "man pen ubatihet"],
        zh: ["那是不小心的", "nà shì bù xiǎoxīn de"],
        ja: ["わざとではありません", "wazato de wa arimasen"],
        ko: ["일부러 그런 게 아니에요", "ilbureo geureon ge anieyo"],
      },
      {
        my: "ကိစ္စမရှိပါဘူး",
        emoji: "🙆",
        en: ["It's okay", "အစ် အိုကေး"],
        th: ["ไม่เป็นไร", "mai pen rai"],
        zh: ["没关系", "méi guānxi"],
        ja: ["大丈夫です", "daijōbu desu"],
        ko: ["괜찮아요", "gwaenchanayo"],
      },
      {
        my: "စိတ်မဆိုးပါနဲ့",
        emoji: "🙏",
        en: ["Please don't be angry", "ပလိစ် ဒုန့် ဘီ အန်းဂရီ"],
        th: ["อย่าโกรธนะ", "yaa krot na"],
        zh: ["请别生气", "qǐng bié shēngqì"],
        ja: ["怒らないでください", "okoranaide kudasai"],
        ko: ["화내지 마세요", "hwanaeji maseyo"],
      },
      {
        my: "ကျွန်တော့် အမှားပါ",
        emoji: "🤲",
        en: ["It's my fault", "အစ် မိုင် ဖော့လ်"],
        th: ["เป็นความผิดผม", "pen khwaam phit phom"],
        zh: ["是我的错", "shì wǒ de cuò"],
        ja: ["私のせいです", "watashi no sei desu"],
        ko: ["제 잘못이에요", "je jalmosieyo"],
      },
      {
        my: "နောက်တစ်ခါ သတိထားပါမယ်",
        emoji: "✅",
        en: ["I'll be careful next time", "အိုင်လ် ဘီ ကဲယာဖွယ် နက်စ် တိုင်းမ်"],
        th: ["คราวหน้าจะระวัง", "khrao naa ja rawang"],
        zh: ["下次我会小心", "xiàcì wǒ huì xiǎoxīn"],
        ja: ["次は気をつけます", "tsugi wa ki o tsukemasu"],
        ko: ["다음엔 조심할게요", "daeumen josimhalgeyo"],
      },
    ],
  },
  {
    slug: "phrases-invitations",
    title: "ဖိတ်ခေါ်ခြင်းနှင့် အစီအစဉ်",
    subtitle: "Invitations & plans",
    emoji: "🎉",
    rows: [
      {
        my: "အတူ ထမင်းစားရအောင်",
        emoji: "🍽️",
        en: ["Let's eat together", "လက်စ် အိစ် တဂဲသာ"],
        th: ["ไปกินข้าวกัน", "pai kin khao kan"],
        zh: ["一起吃饭吧", "yìqǐ chīfàn ba"],
        ja: ["一緒に食べましょう", "issho ni tabemashō"],
        ko: ["같이 밥 먹어요", "gachi bap meogeoyo"],
      },
      {
        my: "အားလား",
        emoji: "🕓",
        en: ["Are you free?", "အာ ယူ ဖရီး"],
        th: ["ว่างไหม", "waang mai"],
        zh: ["你有空吗？", "nǐ yǒu kòng ma"],
        ja: ["時間ありますか", "jikan arimasu ka"],
        ko: ["시간 있어요?", "sigan isseoyo"],
      },
      {
        my: "အတူ သွားရအောင်",
        emoji: "🚶",
        en: ["Let's go together", "လက်စ် ဂို တဂဲသာ"],
        th: ["ไปด้วยกัน", "pai duai kan"],
        zh: ["一起去吧", "yìqǐ qù ba"],
        ja: ["一緒に行きましょう", "issho ni ikimashō"],
        ko: ["같이 가요", "gachi gayo"],
      },
      {
        my: "ဘယ်အချိန် တွေ့မလဲ",
        emoji: "⏰",
        en: ["What time shall we meet?", "ဝော့တ် တိုင်း ရှယ် ဝီ မိ့"],
        th: ["เจอกันกี่โมง", "jer kan kii mong"],
        zh: ["我们几点见？", "wǒmen jǐ diǎn jiàn"],
        ja: ["何時に会いましょうか", "nan ji ni aimashō ka"],
        ko: ["몇 시에 만날까요?", "myeot sie mannalkkayo"],
      },
      {
        my: "ဝမ်းသာလိုက်တာ၊ လာမယ်",
        emoji: "😄",
        en: ["Sure, I'll come", "ရှိုးရ် အိုင်လ် ကမ်း"],
        th: ["ได้เลย จะไป", "dai loei ja pai"],
        zh: ["好啊，我会去", "hǎo a, wǒ huì qù"],
        ja: ["いいですね、行きます", "ii desu ne, ikimasu"],
        ko: ["좋아요, 갈게요", "joayo, galgeyo"],
      },
      {
        my: "ဆောရီး၊ မအားဘူး",
        emoji: "🙏",
        en: ["Sorry, I'm busy", "ဆော်ရီ အိုင်မ် ဘီဇီ"],
        th: ["ขอโทษ ผมไม่ว่าง", "kho thot phom mai waang"],
        zh: ["抱歉，我很忙", "bàoqiàn, wǒ hěn máng"],
        ja: ["すみません、忙しいです", "sumimasen, isogashii desu"],
        ko: ["미안해요, 바빠요", "mianhaeyo, bappayo"],
      },
      {
        my: "နောက်တစ်ခါ ဖြစ်ကောင်းဖြစ်နိုင်",
        emoji: "🔜",
        en: ["Maybe next time", "မေးဘီ နက်စ် တိုင်းမ်"],
        th: ["ไว้คราวหน้า", "wai khrao naa"],
        zh: ["下次吧", "xiàcì ba"],
        ja: ["また今度", "mata kondo"],
        ko: ["다음에 봐요", "daeume bwayo"],
      },
    ],
  },
  {
    slug: "phrases-opinions",
    title: "ထင်မြင်ချက်နှင့် ခံစားချက်",
    subtitle: "Opinions & feelings",
    emoji: "💭",
    rows: [
      {
        my: "ဒါ ကြိုက်တယ်",
        emoji: "😍",
        en: ["I like it", "အိုင် လိုက် အစ်"],
        th: ["ผมชอบ", "phom chop"],
        zh: ["我喜欢", "wǒ xǐhuan"],
        ja: ["好きです", "suki desu"],
        ko: ["좋아요", "joayo"],
      },
      {
        my: "ဒါ မကြိုက်ဘူး",
        emoji: "🙁",
        en: ["I don't like it", "အိုင် ဒုန့် လိုက် အစ်"],
        th: ["ผมไม่ชอบ", "phom mai chop"],
        zh: ["我不喜欢", "wǒ bù xǐhuan"],
        ja: ["好きではありません", "suki de wa arimasen"],
        ko: ["안 좋아해요", "an joahaeyo"],
      },
      {
        my: "ဒါ အရမ်းကောင်းတယ်",
        emoji: "🤩",
        en: ["It's great", "အစ် ဂရိတ်"],
        th: ["เยี่ยมมาก", "yiam mak"],
        zh: ["太棒了", "tài bàng le"],
        ja: ["すばらしいです", "subarashii desu"],
        ko: ["정말 좋아요", "jeongmal joayo"],
      },
      {
        my: "ကျွန်တော် ထင်တာက…",
        emoji: "💭",
        en: ["I think that…", "အိုင် သင့်ခ် ဒဲ့တ်"],
        th: ["ผมคิดว่า…", "phom khit waa…"],
        zh: ["我觉得…", "wǒ juéde…"],
        ja: ["…と思います", "… to omoimasu"],
        ko: ["…라고 생각해요", "…rago saenggakhaeyo"],
      },
      {
        my: "ဟုတ်တယ်ထင်တယ်",
        emoji: "👍",
        en: ["I think so", "အိုင် သင့်ခ် ဆိုး"],
        th: ["คิดว่าใช่", "khit waa chai"],
        zh: ["我想是的", "wǒ xiǎng shì de"],
        ja: ["そう思います", "sō omoimasu"],
        ko: ["그런 것 같아요", "geureon geot gatayo"],
      },
      {
        my: "မသေချာဘူး",
        emoji: "🤷",
        en: ["I'm not sure", "အိုင်မ် နော့တ် ရှိုးရ်"],
        th: ["ไม่แน่ใจ", "mai nae jai"],
        zh: ["我不确定", "wǒ bú quèdìng"],
        ja: ["よくわかりません", "yoku wakarimasen"],
        ko: ["잘 모르겠어요", "jal moreugesseoyo"],
      },
      {
        my: "စိတ်ဝင်စားစရာ ကောင်းတယ်",
        emoji: "🧐",
        en: ["That's interesting", "ဒဲ့တ်စ် အင်ထရက်စတင်း"],
        th: ["น่าสนใจ", "naa sonjai"],
        zh: ["很有意思", "hěn yǒuyìsi"],
        ja: ["面白いですね", "omoshiroi desu ne"],
        ko: ["흥미롭네요", "heungmiromneyo"],
      },
    ],
  },
  {
    slug: "phrases-agree",
    title: "သဘောတူ / မတူ",
    subtitle: "Agreeing & disagreeing",
    emoji: "✅",
    rows: [
      {
        my: "ဟုတ်ကဲ့ / ဟုတ်တယ်",
        emoji: "✅",
        en: ["Yes / That's right", "ယက်စ် ဒဲ့တ်စ် ရိုက်"],
        th: ["ใช่", "chai"],
        zh: ["对", "duì"],
        ja: ["はい、そうです", "hai, sō desu"],
        ko: ["네, 맞아요", "ne, majayo"],
      },
      {
        my: "မဟုတ်ဘူး",
        emoji: "❌",
        en: ["No", "နိုး"],
        th: ["ไม่", "mai"],
        zh: ["不对", "bú duì"],
        ja: ["いいえ", "iie"],
        ko: ["아니요", "aniyo"],
      },
      {
        my: "သဘောတူတယ်",
        emoji: "🤝",
        en: ["I agree", "အိုင် အဂရီး"],
        th: ["ผมเห็นด้วย", "phom hen duai"],
        zh: ["我同意", "wǒ tóngyì"],
        ja: ["賛成です", "sansei desu"],
        ko: ["동의해요", "dongihaeyo"],
      },
      {
        my: "သဘောမတူဘူး",
        emoji: "🙅",
        en: ["I don't agree", "အိုင် ဒုန့် အဂရီး"],
        th: ["ผมไม่เห็นด้วย", "phom mai hen duai"],
        zh: ["我不同意", "wǒ bù tóngyì"],
        ja: ["賛成できません", "sansei dekimasen"],
        ko: ["동의하지 않아요", "dongihaji anayo"],
      },
      {
        my: "ဟုတ်ကဲ့၊ ရပါတယ်",
        emoji: "👌",
        en: ["Okay, that's fine", "အိုကေး ဒဲ့တ်စ် ဖိုင်း"],
        th: ["โอเค ได้เลย", "okhe dai loei"],
        zh: ["好的，可以", "hǎo de, kěyǐ"],
        ja: ["はい、大丈夫です", "hai, daijōbu desu"],
        ko: ["네, 괜찮아요", "ne, gwaenchanayo"],
      },
      {
        my: "ဟုတ်ချင်မှ ဟုတ်မယ်",
        emoji: "🤔",
        en: ["Maybe", "မေးဘီ"],
        th: ["อาจจะ", "aat ja"],
        zh: ["也许吧", "yěxǔ ba"],
        ja: ["たぶん", "tabun"],
        ko: ["아마도", "amado"],
      },
      {
        my: "မင်း ပြောတာ မှန်တယ်",
        emoji: "💯",
        en: ["You're right", "ယုအာ ရိုက်"],
        th: ["คุณพูดถูก", "khun phuut thuuk"],
        zh: ["你说得对", "nǐ shuō de duì"],
        ja: ["あなたの言う通りです", "anata no iu tōri desu"],
        ko: ["당신 말이 맞아요", "dangsin mari majayo"],
      },
    ],
  },
  {
    slug: "phrases-time",
    title: "အချိန်နှင့် ချိန်းဆိုမှု",
    subtitle: "Time & appointments",
    emoji: "🕐",
    rows: [
      {
        my: "အခု ဘယ်နှစ်နာရီရှိပြီလဲ",
        emoji: "🕐",
        en: ["What time is it now?", "ဝော့တ် တိုင်း အီးဇ် အစ် နောင်"],
        th: ["ตอนนี้กี่โมง", "ton nii kii mong"],
        zh: ["现在几点？", "xiànzài jǐ diǎn"],
        ja: ["今何時ですか", "ima nan ji desu ka"],
        ko: ["지금 몇 시예요?", "jigeum myeot siyeyo"],
      },
      {
        my: "ဘယ်အချိန် ဖွင့်လဲ",
        emoji: "🔓",
        en: ["What time do you open?", "ဝော့တ် တိုင်း ဒူ ယူ အိုးပင်"],
        th: ["เปิดกี่โมง", "poet kii mong"],
        zh: ["几点开门？", "jǐ diǎn kāimén"],
        ja: ["何時に開きますか", "nan ji ni akimasu ka"],
        ko: ["몇 시에 열어요?", "myeot sie yeoreoyo"],
      },
      {
        my: "ဘယ်အချိန် ပိတ်လဲ",
        emoji: "🔒",
        en: ["What time do you close?", "ဝော့တ် တိုင်း ဒူ ယူ ကလိုးဇ်"],
        th: ["ปิดกี่โมง", "pit kii mong"],
        zh: ["几点关门？", "jǐ diǎn guānmén"],
        ja: ["何時に閉まりますか", "nan ji ni shimarimasu ka"],
        ko: ["몇 시에 닫아요?", "myeot sie dadayo"],
      },
      {
        my: "ချိန်းချင်ပါတယ်",
        emoji: "📅",
        en: ["I'd like to make an appointment", "အိုင်ဒ် လိုက် တု မိတ်ခ် အန် အပွိုင့်မန့်"],
        th: ["ขอนัดหน่อย", "kho nat noi"],
        zh: ["我想预约", "wǒ xiǎng yùyuē"],
        ja: ["予約したいです", "yoyaku shitai desu"],
        ko: ["예약하고 싶어요", "yeyakhago sipeoyo"],
      },
      {
        my: "အချိန်မီ ရောက်ပါမယ်",
        emoji: "⏱️",
        en: ["I'll be on time", "အိုင်လ် ဘီ အွန် တိုင်းမ်"],
        th: ["จะมาตรงเวลา", "ja maa trong welaa"],
        zh: ["我会准时到", "wǒ huì zhǔnshí dào"],
        ja: ["時間通りに行きます", "jikan dōri ni ikimasu"],
        ko: ["제시간에 갈게요", "jesigane galgeyo"],
      },
      {
        my: "ခဏ စောင့်ပေးပါ",
        emoji: "⌛",
        en: ["Please wait a moment", "ပလိစ် ဝိတ် အ မိုးမင့်"],
        th: ["รอสักครู่นะ", "ro sak khru na"],
        zh: ["请稍等一下", "qǐng shāo děng yíxià"],
        ja: ["少しお待ちください", "sukoshi omachi kudasai"],
        ko: ["잠시만 기다려 주세요", "jamsiman gidaryeo juseyo"],
      },
      {
        my: "မနက်ဖြန် တွေ့မယ်",
        emoji: "📆",
        en: ["See you tomorrow", "ဆီး ယူ တုမောရိုး"],
        th: ["เจอกันพรุ่งนี้", "jer kan phrung nii"],
        zh: ["明天见", "míngtiān jiàn"],
        ja: ["また明日", "mata ashita"],
        ko: ["내일 봐요", "naeil bwayo"],
      },
    ],
  },
  {
    slug: "phrases-work",
    title: "အလုပ်ခွင်",
    subtitle: "At work / office",
    emoji: "🏢",
    rows: [
      {
        my: "မင်္ဂလာနံနက်ခင်းပါ၊ အားလုံး",
        emoji: "🌅",
        en: ["Good morning, everyone", "ဂွတ် မော်နင်း အဲဗရီဝမ်း"],
        th: ["สวัสดีตอนเช้าทุกคน", "sawatdii ton chao thuk khon"],
        zh: ["大家早上好", "dàjiā zǎoshang hǎo"],
        ja: ["皆さん、おはようございます", "minasan, ohayō gozaimasu"],
        ko: ["여러분, 좋은 아침이에요", "yeoreobun, joeun achimieyo"],
      },
      {
        my: "အစည်းအဝေး ဘယ်အချိန်လဲ",
        emoji: "📅",
        en: ["What time is the meeting?", "ဝော့တ် တိုင်း အီးဇ် ဒ မီးတင်း"],
        th: ["ประชุมกี่โมง", "prachum kii mong"],
        zh: ["会议几点？", "huìyì jǐ diǎn"],
        ja: ["会議は何時ですか", "kaigi wa nan ji desu ka"],
        ko: ["회의가 몇 시예요?", "hoiiga myeot siyeyo"],
      },
      {
        my: "အီးမေးလ် ပို့လိုက်ပါ",
        emoji: "📧",
        en: ["Please send me an email", "ပလိစ် ဆဲန်ဒ် မီ အန် အီးမေးလ်"],
        th: ["ส่งอีเมลมาด้วย", "song iimeo maa duai"],
        zh: ["请发邮件给我", "qǐng fā yóujiàn gěi wǒ"],
        ja: ["メールを送ってください", "mēru o okutte kudasai"],
        ko: ["이메일 보내 주세요", "imeil bonae juseyo"],
      },
      {
        my: "ဒီအလုပ် ကူညီပေးလို့ရမလား",
        emoji: "🤝",
        en: ["Can you help with this task?", "ကန် ယူ ဟဲ့ပ် ဝစ် ဒစ် တတ်စ်ခ်"],
        th: ["ช่วยงานนี้ได้ไหม", "chuai ngaan nii dai mai"],
        zh: ["能帮我做这个吗？", "néng bāng wǒ zuò zhège ma"],
        ja: ["この仕事を手伝ってもらえますか", "kono shigoto o tetsudatte moraemasu ka"],
        ko: ["이 일 좀 도와줄 수 있어요?", "i il jom dowajul su isseoyo"],
      },
      {
        my: "ပြီးသွားပါပြီ",
        emoji: "✅",
        en: ["It's done", "အစ် ဒန်း"],
        th: ["เสร็จแล้ว", "set laeo"],
        zh: ["做完了", "zuòwán le"],
        ja: ["終わりました", "owarimashita"],
        ko: ["다 됐어요", "da dwaesseoyo"],
      },
      {
        my: "နောက်ကျမယ်ထင်တယ်",
        emoji: "⏳",
        en: ["I think it'll be late", "အိုင် သင့်ခ် အစ်တဲ ဘီ လိတ်"],
        th: ["คิดว่าจะช้า", "khit waa ja chaa"],
        zh: ["我想会晚一点", "wǒ xiǎng huì wǎn yìdiǎn"],
        ja: ["遅れると思います", "okureru to omoimasu"],
        ko: ["늦을 것 같아요", "neujeul geot gatayo"],
      },
      {
        my: "ကြိုးစားလုပ်ပါမယ်",
        emoji: "💪",
        en: ["I'll do my best", "အိုင်လ် ဒူ မိုင် ဘက်စ်"],
        th: ["จะพยายามเต็มที่", "ja phayaayaam tem thii"],
        zh: ["我会尽力", "wǒ huì jìnlì"],
        ja: ["頑張ります", "ganbarimasu"],
        ko: ["최선을 다할게요", "choeseoneul dahalgeyo"],
      },
    ],
  },
  {
    slug: "phrases-weather-chat",
    title: "ရာသီဥတု စကားစမြည်",
    subtitle: "Weather small talk",
    emoji: "🌦️",
    rows: [
      {
        my: "ဒီနေ့ အရမ်းပူတယ်",
        emoji: "🥵",
        en: ["It's very hot today", "အစ် ဗယ်ရီ ဟော့တ် တုဒေး"],
        th: ["วันนี้ร้อนมาก", "wan nii ron mak"],
        zh: ["今天很热", "jīntiān hěn rè"],
        ja: ["今日はとても暑いです", "kyō wa totemo atsui desu"],
        ko: ["오늘 정말 더워요", "oneul jeongmal deowoyo"],
      },
      {
        my: "ဒီနေ့ အေးတယ်",
        emoji: "🥶",
        en: ["It's cold today", "အစ် ကိုးလ်ဒ် တုဒေး"],
        th: ["วันนี้หนาว", "wan nii nao"],
        zh: ["今天很冷", "jīntiān hěn lěng"],
        ja: ["今日は寒いです", "kyō wa samui desu"],
        ko: ["오늘 추워요", "oneul chuwoyo"],
      },
      {
        my: "မိုးရွာတော့မယ်",
        emoji: "🌧️",
        en: ["It's going to rain", "အစ် ဂိုးရင်း တု ရိန်း"],
        th: ["ฝนจะตก", "fon ja tok"],
        zh: ["要下雨了", "yào xiàyǔ le"],
        ja: ["雨が降りそうです", "ame ga furisō desu"],
        ko: ["비가 올 것 같아요", "biga ol geot gatayo"],
      },
      {
        my: "ထီး ယူသွားပါ",
        emoji: "☂️",
        en: ["Take an umbrella", "တိတ်ခ် အန် အမ်ဘရဲလာ"],
        th: ["เอาร่มไปด้วย", "ao rom pai duai"],
        zh: ["带把伞", "dài bǎ sǎn"],
        ja: ["傘を持って行ってください", "kasa o motte itte kudasai"],
        ko: ["우산 가져가세요", "usan gajyeogaseyo"],
      },
      {
        my: "ဒီနေ့ ရာသီဥတု လှတယ်",
        emoji: "🌤️",
        en: ["The weather is nice", "ဒ ဝဲသာ အီးဇ် နိုက်စ်"],
        th: ["อากาศดี", "aakaat dii"],
        zh: ["天气很好", "tiānqì hěn hǎo"],
        ja: ["いい天気ですね", "ii tenki desu ne"],
        ko: ["날씨가 좋아요", "nalssiga joayo"],
      },
      {
        my: "လေ ပြင်းတယ်",
        emoji: "🌬️",
        en: ["It's windy", "အစ် ဝင်းဒီ"],
        th: ["ลมแรง", "lom raeng"],
        zh: ["风很大", "fēng hěn dà"],
        ja: ["風が強いです", "kaze ga tsuyoi desu"],
        ko: ["바람이 세요", "barami seyo"],
      },
      {
        my: "မနက်ဖြန် ရာသီဥတု ဘယ်လိုလဲ",
        emoji: "🔮",
        en: ["How's the weather tomorrow?", "ဟောင်း ဒ ဝဲသာ တုမောရိုး"],
        th: ["พรุ่งนี้อากาศเป็นยังไง", "phrung nii aakaat pen yangngai"],
        zh: ["明天天气怎么样？", "míngtiān tiānqì zěnmeyàng"],
        ja: ["明日の天気はどうですか", "ashita no tenki wa dō desu ka"],
        ko: ["내일 날씨 어때요?", "naeil nalssi eottaeyo"],
      },
    ],
  },
  {
    slug: "phrases-farewells",
    title: "နှုတ်ဆက်ခြင်းနှင့် ဆုတောင်း",
    subtitle: "Goodbyes & good wishes",
    emoji: "👋",
    rows: [
      {
        my: "သွားတော့မယ်",
        emoji: "👋",
        en: ["Goodbye", "ဂွတ်ဘိုင်း"],
        th: ["ลาก่อน", "laa kon"],
        zh: ["再见", "zàijiàn"],
        ja: ["さようなら", "sayōnara"],
        ko: ["안녕히 계세요", "annyeonghi gyeseyo"],
      },
      {
        my: "ကိုယ်စောင့်ရှောက်ပါ",
        emoji: "🤗",
        en: ["Take care", "တိတ်ခ် ကဲယာ"],
        th: ["ดูแลตัวเองนะ", "duulae tua eeng na"],
        zh: ["保重", "bǎozhòng"],
        ja: ["お気をつけて", "oki o tsukete"],
        ko: ["몸조심하세요", "momjosimhaseyo"],
      },
      {
        my: "ကောင်းသော ခရီးဖြစ်ပါစေ",
        emoji: "✈️",
        en: ["Have a safe trip", "ဟဲ့ဗ် အ ဆိတ်ဖ် ထရစ်"],
        th: ["เดินทางปลอดภัยนะ", "doenthaang plotphai na"],
        zh: ["一路平安", "yílù píng'ān"],
        ja: ["良い旅を", "yoi tabi o"],
        ko: ["안전한 여행 되세요", "anjeonhan yeohaeng doeseyo"],
      },
      {
        my: "ကံကောင်းပါစေ",
        emoji: "🍀",
        en: ["Good luck", "ဂွတ် လပ်ခ်"],
        th: ["โชคดีนะ", "chok dii na"],
        zh: ["祝你好运", "zhù nǐ hǎoyùn"],
        ja: ["頑張ってね", "ganbatte ne"],
        ko: ["행운을 빌어요", "haenguneul bireoyo"],
      },
      {
        my: "ကျန်းမာပါစေ",
        emoji: "🙏",
        en: ["Stay healthy", "စတေး ဟဲ့လ်သီ"],
        th: ["สุขภาพแข็งแรงนะ", "sukkhaphaap khaengraeng na"],
        zh: ["身体健康", "shēntǐ jiànkāng"],
        ja: ["お元気で", "ogenki de"],
        ko: ["건강하세요", "geonganghaseyo"],
      },
      {
        my: "ကောင်းသောည ဖြစ်ပါစေ",
        emoji: "🌙",
        en: ["Have a good night", "ဟဲ့ဗ် အ ဂွတ် နိုက်"],
        th: ["ราตรีสวัสดิ์", "raatrii sawat"],
        zh: ["晚安", "wǎn'ān"],
        ja: ["おやすみなさい", "oyasumi nasai"],
        ko: ["안녕히 주무세요", "annyeonghi jumuseyo"],
      },
      {
        my: "ကြိုဆိုပါတယ် / ပြန်တွေ့ရတာ ဝမ်းသာတယ်",
        emoji: "😊",
        en: ["Nice to see you again", "နိုက်စ် တု ဆီး ယူ အဂိန်း"],
        th: ["ดีใจที่ได้เจอกันอีก", "dii jai thii dai jer kan iik"],
        zh: ["很高兴再见到你", "hěn gāoxìng zài jiàndào nǐ"],
        ja: ["また会えて嬉しいです", "mata aete ureshii desu"],
        ko: ["다시 만나서 반가워요", "dasi mannaseo bangawoyo"],
      },
    ],
  },
];

/** The five course slugs that have aligned phrase text. */
type PhraseLang = "en" | "th" | "zh" | "ja" | "ko";

const SLUG_TO_LANG: Record<string, PhraseLang> = {
  english: "en",
  thai: "th",
  chinese: "zh",
  japanese: "ja",
  korean: "ko",
};

/**
 * Build the twenty useful-phrase units for one course, picking the right
 * target/roman column for that language. Returns `[]` for an unknown course so
 * callers can safely spread the result.
 */
export function phraseUnitsFor(courseSlug: string): LangUnit[] {
  const lang = SLUG_TO_LANG[courseSlug];
  if (!lang) return [];
  return PHRASE_LESSONS.map((lesson) => ({
    slug: lesson.slug,
    title: lesson.title,
    subtitle: lesson.subtitle,
    emoji: lesson.emoji,
    items: lesson.rows.map<Phrase>((row) => {
      const [target, roman] = row[lang];
      return { target, roman, my: row.my, emoji: row.emoji };
    }),
  }));
}
