// Python course — expansion pack. Runnable lessons spliced into pythonTrack
// (webdev.ts) after the core lessons, taking the Python course to a full
// beginner→intermediate curriculum. Every lesson runs in the Pyodide
// playground (kind "python"); no input() is used since the sandbox has no
// stdin. All original content; Burmese overlay lives in i18n/my.ts.

import type { Lesson } from "@/lib/learn/lessons";

function py(
  slug: string,
  title: string,
  summary: string,
  heading: string,
  body: string,
  snippet: string,
  pythonCode: string,
  minutes = 10,
): Lesson {
  return {
    slug,
    title,
    summary,
    minutes,
    kind: "python",
    sections: [{ heading, body, code: snippet }],
    pythonCode,
  };
}

export const PY_EXTRA2: Lesson[] = [
  py(
    "py-numbers",
    "Numbers & Maths",
    "Integers, floats and the arithmetic operators.",
    "Two kinds of number",
    "Python has integers (whole numbers) and floats (with a decimal point). The operators are + - * /, plus // (floor division), % (remainder) and ** (power). Dividing with / always gives a float.",
    "7 // 2   # 3\n7 % 2    # 1\n2 ** 10  # 1024",
    'print(7 / 2)      # 3.5\nprint(7 // 2)     # 3\nprint(7 % 2)      # 1\nprint(2 ** 10)    # 1024\nprint(round(3.14159, 2))\nprint(abs(-5))',
  ),
  py(
    "py-operators",
    "Comparison & Logic",
    "Compare values and combine conditions.",
    "True or false",
    "Comparison operators (== != > < >= <=) return a boolean. Combine them with and, or and not. The in operator checks membership in a list, string or dict.",
    "3 > 2 and 5 == 5   # True\n'a' in 'cat'       # True",
    "print(3 > 2)\nprint(5 == 5 and 2 < 1)\nprint(not False)\nprint('a' in 'cat')\nprint(10 in [1, 2, 10])\nprint('OG' in {'OG': 8})",
  ),
  py(
    "py-fstrings",
    "f-strings",
    "Format text with embedded values.",
    "Readable formatting",
    "An f-string starts with f before the quote; inside, { } inserts any value or expression. You can format numbers too: {value:.2f} shows two decimals, {n:>5} right-aligns in 5 spaces.",
    'name = "Su"\nf"{name} grows {3*4} plants"',
    'name = "Su"\nplants = 20\nprint(f"{name} has {plants} plants")\nprice = 1234.5\nprint(f"Total: {price:.2f}")\nprint(f"{plants:>5} plants")',
  ),
  py(
    "py-lists-deep",
    "Lists in Depth",
    "append, insert, remove, sort and more.",
    "Growing and changing lists",
    "Lists are ordered and changeable. append adds to the end, insert at a position, remove deletes by value, pop by index. sort() orders in place, and len() counts. Lists can hold any mix of values.",
    "nums = [3, 1, 2]\nnums.append(4)\nnums.sort()  # [1, 2, 3, 4]",
    'plants = ["OG", "Blue Dream"]\nplants.append("Sour Diesel")\nplants.insert(0, "Northern Lights")\nprint(plants)\nplants.remove("OG")\nprint(plants)\nprint("count:", len(plants))\nnums = [3, 1, 2]\nnums.sort()\nprint(nums)',
  ),
  py(
    "py-tuples",
    "Tuples",
    "Fixed, unchangeable sequences.",
    "Like a list, but locked",
    "A tuple is an ordered collection written with parentheses. Unlike a list it can't be changed after creation — useful for fixed data like coordinates. You can unpack a tuple straight into variables.",
    "point = (4, 9)\nx, y = point",
    'point = (12, 5)\nx, y = point\nprint("x:", x, "y:", y)\nseasons = ("spring", "summer", "autumn", "winter")\nprint(len(seasons))\nprint(seasons[0])\n# tuples are immutable:\nprint("summer" in seasons)',
  ),
  py(
    "py-sets",
    "Sets",
    "Collections of unique items.",
    "No duplicates allowed",
    "A set holds unique values with no order. Adding a value that's already there does nothing. Sets are great for removing duplicates and for maths like union (|), intersection (&) and difference (-).",
    "{1, 2, 2, 3}       # {1, 2, 3}\n{1,2} & {2,3}      # {2}",
    'a = {1, 2, 2, 3, 3, 3}\nprint(a)               # duplicates gone\nb = {2, 3, 4}\nprint("union:", a | b)\nprint("common:", a & b)\nprint("only a:", a - b)\nprint("has 2?", 2 in a)',
  ),
  py(
    "py-dict-methods",
    "Dictionary Methods",
    "keys, values, items, get and update.",
    "Working with key/value data",
    "A dict maps keys to values. get(key, default) reads safely, keys()/values()/items() give the parts to loop over, and update() merges another dict in. Looping a dict yields its keys.",
    'grower = {"name": "Su", "city": "Yangon"}\ngrower.get("age", 0)  # 0',
    'grower = {"name": "Nilar", "plants": 15}\nprint(grower.get("name"))\nprint(grower.get("age", "unknown"))\ngrower["city"] = "Mandalay"\nfor key, value in grower.items():\n    print(f"{key} = {value}")',
  ),
  py(
    "py-comprehensions",
    "List & Dict Comprehensions",
    "Build a list or dict in a single line.",
    "Loops as expressions",
    "A comprehension builds a collection compactly: [expr for item in iterable if condition]. It replaces a whole for-loop for making new lists. Dict comprehensions use {key: value for ...}.",
    "[n*2 for n in range(4)]        # [0,2,4,6]\n[n for n in nums if n > 5]",
    'squares = [n * n for n in range(1, 6)]\nprint(squares)\nplants = [12, 5, 20, 8]\nbig = [p for p in plants if p > 10]\nprint("big:", big)\nlabels = {p: ("big" if p > 10 else "small") for p in plants}\nprint(labels)',
  ),
  py(
    "py-slicing",
    "Slicing",
    "Take parts of lists and strings.",
    "start : stop : step",
    "Slicing copies a part of a sequence: seq[start:stop] (stop is excluded). Leave a side blank for 'from the start' or 'to the end'. A step ([::2]) skips items, and [::-1] reverses.",
    'word = "GreenWave"\nword[0:5]   # "Green"\nword[::-1]  # reversed',
    'word = "GreenWave"\nprint(word[0:5])\nprint(word[5:])\nprint(word[-4:])\nprint(word[::-1])\nnums = [0, 1, 2, 3, 4, 5]\nprint(nums[1:4])\nprint(nums[::2])',
  ),
  py(
    "py-string-methods",
    "String Methods",
    "upper, split, replace, strip, join and find.",
    "Transforming text",
    "Strings have many methods: upper()/lower() change case, strip() trims spaces, replace() swaps text, split() breaks a string into a list, and join() glues a list back into a string. Strings are immutable, so these return new strings.",
    '"a,b,c".split(",")   # ["a","b","c"]\n"-".join(["a","b"])  # "a-b"',
    'text = "  Grow With GreenWave  "\nprint(text.strip().upper())\nprint(text.replace("Grow", "Learn").strip())\nparts = "OG,Blue,Sour".split(",")\nprint(parts)\nprint(" + ".join(parts))\nprint("green" in text.lower())',
  ),
  py(
    "py-booleans",
    "Booleans & Truthiness",
    "True, False and what counts as 'empty'.",
    "Truthy and falsy",
    "Besides True and False, Python treats some values as falsy in a condition: 0, '' (empty string), [] (empty list), {} and None. Everything else is truthy. This lets you write if my_list: to mean 'if it has items'.",
    "if items:      # True when items is non-empty\n    ...",
    'print(bool(0), bool(1))\nprint(bool(""), bool("hi"))\nprint(bool([]), bool([1]))\nvalues = []\nif values:\n    print("has items")\nelse:\n    print("empty list is falsy")\nprint(None is None)',
  ),
  py(
    "py-while",
    "while, break & continue",
    "Loop until a condition changes.",
    "Repeat while true",
    "A while loop runs as long as its condition is true. break stops the loop early; continue skips to the next turn. Always change something inside so the loop can end — an unchanging condition loops forever.",
    "while water > 0:\n    water -= 1",
    'water = 5\nwhile water > 0:\n    print(f"watering, {water} left")\n    water -= 1\nprint("done")\n\nfor n in range(10):\n    if n == 3:\n        continue   # skip 3\n    if n == 6:\n        break      # stop at 6\n    print(n, end=" ")',
  ),
  py(
    "py-range-enumerate-zip",
    "range, enumerate & zip",
    "Count, number your items, and pair two lists.",
    "Loop helpers",
    "range(n) counts 0..n-1. enumerate(list) gives index and value together. zip(a, b) pairs two lists item by item — perfect for looping over related data at once.",
    "for i, name in enumerate(names): ...\nfor a, b in zip(xs, ys): ...",
    'names = ["OG", "Blue Dream"]\nweeks = [8, 9]\nfor i, name in enumerate(names):\n    print(i, name)\nfor name, w in zip(names, weeks):\n    print(f"{name}: {w} weeks")\nprint(list(range(2, 10, 2)))',
  ),
  py(
    "py-func-args",
    "Function Arguments",
    "Defaults, keywords, *args and **kwargs.",
    "Flexible parameters",
    "Give a parameter a default (def f(x=1)) so callers can skip it. Call with keywords for clarity (f(x=5)). *args collects extra positional arguments into a tuple, and **kwargs collects extra keyword arguments into a dict.",
    "def greet(name, msg='Hi'): ...\ndef total(*nums): ...",
    'def water(plant, litres=1):\n    return f"{plant}: {litres}L"\nprint(water("OG"))\nprint(water("Blue Dream", litres=3))\n\ndef total(*nums):\n    return sum(nums)\nprint(total(5, 10, 15))',
  ),
  py(
    "py-lambda",
    "lambda, map & filter",
    "Tiny anonymous functions and functional tools.",
    "Functions without a name",
    "A lambda is a one-line function: lambda x: x * 2. It's handy as an argument. map(fn, list) applies a function to every item; filter(fn, list) keeps items that pass; both return iterators, so wrap in list().",
    "double = lambda x: x * 2\nlist(map(double, nums))",
    'nums = [1, 2, 3, 4]\ndouble = lambda x: x * 2\nprint(list(map(double, nums)))\nprint(list(filter(lambda n: n % 2 == 0, nums)))\nplants = [("OG", 8), ("Blue", 9)]\nplants.sort(key=lambda p: p[1])\nprint(plants)',
  ),
  py(
    "py-recursion",
    "Recursion",
    "A function that calls itself.",
    "Solving by shrinking",
    "A recursive function calls itself on a smaller problem until it hits a base case that stops the recursion. Factorial and countdowns are classic examples. Every recursion needs a base case, or it never ends.",
    "def fact(n):\n    if n <= 1: return 1\n    return n * fact(n - 1)",
    'def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\nprint(factorial(5))\n\ndef countdown(n):\n    if n == 0:\n        print("lift-off!")\n        return\n    print(n)\n    countdown(n - 1)\ncountdown(3)',
  ),
  py(
    "py-classes",
    "Classes & Objects",
    "Bundle data and behaviour into your own types.",
    "Blueprints for objects",
    "A class defines a type. __init__ is the constructor that sets each object's data via self. Methods are functions inside the class that use self to read that object's data. Create instances by calling the class.",
    "class Plant:\n    def __init__(self, name):\n        self.name = name",
    'class Plant:\n    def __init__(self, name, weeks):\n        self.name = name\n        self.weeks = weeks\n    def describe(self):\n        return f"{self.name} flowers in {self.weeks} weeks"\n\nog = Plant("OG Kush", 8)\nprint(og.describe())\nprint(Plant("Blue Dream", 9).describe())',
  ),
  py(
    "py-inheritance",
    "Inheritance",
    "Build a class on top of another.",
    "Sharing behaviour",
    "A class can inherit from another, reusing its methods and adding or overriding its own. The child calls super().__init__() to run the parent's constructor. This models 'is a' relationships without repeating code.",
    "class Herb(Plant):\n    def __init__(self, name):\n        super().__init__(name, 6)",
    'class Plant:\n    def __init__(self, name):\n        self.name = name\n    def water(self):\n        return f"{self.name} watered"\n\nclass Cannabis(Plant):\n    def water(self):\n        return f"{self.name} watered carefully 🌿"\n\nprint(Plant("Basil").water())\nprint(Cannabis("OG Kush").water())',
  ),
  py(
    "py-generators",
    "Generators & yield",
    "Produce values one at a time, on demand.",
    "Lazy sequences",
    "A generator function uses yield instead of return to hand back values one at a time, pausing between them. It doesn't build the whole list in memory — great for large or endless sequences. Loop over it like any iterable.",
    "def counter(n):\n    for i in range(n):\n        yield i",
    'def squares(n):\n    for i in range(1, n + 1):\n        yield i * i\n\nfor s in squares(5):\n    print(s, end=" ")\nprint()\ngen = squares(3)\nprint(next(gen))\nprint(next(gen))',
  ),
  py(
    "py-decorators",
    "Decorators",
    "Wrap a function to add behaviour.",
    "Functions that modify functions",
    "A decorator is a function that takes another function and returns a wrapped version with extra behaviour — logging, timing, checks — without changing the original. Apply one with the @name line above a function.",
    "@log\ndef greet(): ...",
    'def shout(func):\n    def wrapper(*args):\n        return func(*args).upper() + "!"\n    return wrapper\n\n@shout\ndef greet(name):\n    return f"hi {name}"\n\nprint(greet("su"))\nprint(greet("mai"))',
  ),
];
